### ISSUE TITLE
Documentation search is not working

### ISSUE THREAD

**Issue by yacobcz** [abpframework/abp#5132] opened 2020-08-20 10:34 UTC
Hi, I think the search in the [documentation](https://docs.abp.io/) is broken.
The result of searching for any term is empty.
I mean "Search in documents", not "Filter topics" feature.
It affects all versions, languages and browsers.

![image](https://user-images.githubusercontent.com/6282139/90759448-ba0a2480-e2e0-11ea-8aff-1caefc60da88.png)
![image](https://user-images.githubusercontent.com/6282139/90759942-706e0980-e2e1-11ea-9eb9-cbd9df4fc696.png)

**Comment by hikalkan** [comment] 2020-08-20 16:35
@maliming maybe related to change of the branching system?

**Comment by maliming** [comment] 2020-08-20 23:09
Duplicate of https://github.com/abpframework/abp/pull/4970

**Closed as completed** 2020-08-21 02:26 UTC
