### ISSUE TITLE
upgrade the highlight.js to latest

### ISSUE THREAD

**Issue by rqx110** [abpframework/abp#11485] opened 2022-01-27 02:03 UTC
currently we are using an old version of highlight.js 9.12.0, but the latest version is 11.4.0 https://highlightjs.org/,
pls consider to upgrade it. TKS

**Comment by realLiangshiwei** [comment] 2022-01-27 02:53
Duplicate of https://github.com/abpframework/abp/issues/11329

**Closed as completed** 2022-01-27 03:02 UTC
