### ISSUE TITLE
With "Require confirmed email", instant login should not happen after registration

### ISSUE THREAD

**Issue by michaelsudnik** [abpframework/abp#3541] opened 2020-04-10 06:44 UTC
When the "Require confirmed email" option is selected and a new user registers, they are logged in straight away. They should be presented with a message saying thank you for registering and to confirm their email before logging in.

**Comment by maliming** [comment] 2020-04-10 06:55
Duplicate of #https://github.com/abpframework/abp/issues/3542

**Closed by maliming** 2020-04-10 06:55 UTC

**Comment by michaelsudnik** [comment] 2020-04-10 13:46
I don't think this is a duplicate if the other one (I created). I don't see any reference of this issue in the referenced issue either. This is specifically referring to users being logged in straight away after registration. This should not happen with the Require confirmed email option selected.

**Comment by brunobertechini** [comment] 2020-12-13 02:39
I also think this is not a dupe of #3542 . I am able to reproduce this usingangular & separated identity server. After registering a new user, when "Required confirmed email" enabled, the user is automatically logged in and redirected to the application (Even before clicking on the confirmation link received via email).

cc @hikalkan

**Comment by Joncyzx** [comment] 2022-07-14 09:10
Any news about this? 😄
