### ISSUE TITLE
user is redirected to Account/AccessDenied?ReturnUrl=%2Ftasks%2Fcreate-task

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#7208] opened 2021-01-14 07:20 UTC
* Your **ABP Framework version** - 4.0.2.
* Your **User Interface** type (Angular/MVC/React... etc.) - MVC
* Your database provider(EF Core/MongoDB) - EF Core
* Steps needed to **reproduce** the problem.

When a user doesn't have permission to create, edit or delete pages the user is redirected to Account/AccessDenied?ReturnUrl=%2Ftasks%2Fcreate-task

How to handle this exception so the user doesn't get a 404 not found page?

![image](https://user-images.githubusercontent.com/15242923/104557255-10636f80-5695-11eb-84f3-6ccfdfadaf66.png)

**Comment by maliming** [comment] 2021-01-14 07:21
Duplicate of #7208

**Closed as completed by maliming** 2021-01-14 07:21 UTC
