### ISSUE TITLE
IUserValidator custom implementation can not localizing

### ISSUE THREAD

**Issue by wallee85** [abpframework/abp#14889] opened 2022-11-30 15:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when i implemented the IUserValidator<IdentityUser> to do my custom validation,i found that the localization didn't  work.
for example,the code in my UserValidaor:
`	
// ValidateAsync method
if (!phoneNumber.All(char.IsDigit))
			{
				errors.Add(new IdentityError
				{
					Code = NonNumericPhoneNumberErrorCode,
					Description = _localizer[$"Volo.Abp.Identity:{NonNumericPhoneNumberDescription}"]
				});
			}`
in the code above ,the interface method ValidateAsync returns a Task<IdentityResult>,and the NonNumericPhoneNumberErrorCode is a constant string,defined in my localization file. (it extanded the IdentityResource,).
when i call some code like:
`(await UserManager.CreateAsync(user, input.Password)).CheckErrors();`
if the IUserValidator which i implemented checked out some errors,then the Task<IdentityResult> what the IUserValidaor returned contained a Failed IdentityResult,but the  error code could not be localized.

i check the extension methods defined in AbpIdentityResultExtensions( namespace is Microsoft.AspNetCore.Identity) and found the follwing code:
`static AbpIdentityResultExtensions()
    {
        var identityResourceManager = new ResourceManager("Microsoft.Extensions.Identity.Core.Resources", typeof(UserManager<>).Assembly);
        var resourceSet = identityResourceManager.GetResourceSet(CultureInfo.InvariantCulture, true, false);
        if (resourceSet == null)
        {
            throw new AbpException("Can't get the ResourceSet of Identity.");
        }

        var iterator = resourceSet.GetEnumerator();
        while (true)
        {
            if (!iterator.MoveNext())
            {
                break;
            }

            var key = iterator.Key?.ToString();
            var value = iterator.Value?.ToString();
            if (key != null && value != null)
            {
                IdentityStrings.Add(key, value);
            }
        }

        if (!IdentityStrings.Any())
        {
            throw new AbpException("ResourceSet values of Identity is empty.");
        }
    }`
i guess some error in there? the IdentityStrings didn't contained my NonNumericPhoneNumberErrorCode(above)。

### Expected behavior

the IdentityResult can localize the error code what i defined and used in IUserValidaor

### Actual behavior

the IdentityResult extension methods can NOT localize the error code what i defined and used in IUserValidaor

### Regression?

not actually,my project is is to be completed

### Version

6.0.1

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by berkansasmaz** [comment] 2022-12-02 06:57
> Hi,
> 
> ABP is designed to be compatible with ASP.NET Core Identity and will try to localize error code, but it doesn't support custom errors.
> 
> The solution is very simple, you just need to throw a `BusinessException`:
> 
> ```csharp
> public const string PhoneNumberStartsWithZeroError = "MyProjectName:PhoneNumberStartsWithZero";
> 
> public Task<IdentityResult> ValidateAsync(UserManager<IdentityUser> manager, IdentityUser user)
> {
>     throw new BusinessException(PhoneNumberStartsWithZeroError);
> }
> Configure<AbpExceptionLocalizationOptions>(options =>
> {
>     options.MapCodeNamespace("MyProjectName", typeof(MyProjectNameResource));
> });
> ```

See more: https://support.abp.io/QA/Questions/3962/How-to-get-the-correct-message-instead-of-IdentityDefault-when-adding-more-validation-on-creating-user

**Comment by wallee85** [comment] 2022-12-02 08:42
em...i absolutly known this,but the IUserValidator method returns a IdentityResult,which contains the error code,but actually what you designed is that the IdentityResult always reutrn a non-error contained identityresult,if no exception is thrown in iuservalidator,it's looked wired,isn't it?

**Comment by berkansasmaz** [comment] 2022-12-05 06:50
> for example,the code in my UserValidaor:
> // ValidateAsync method if (!phoneNumber.All(char.IsDigit)) { errors.Add(new IdentityError { Code = NonNumericPhoneNumberErrorCode, Description = _localizer[$"Volo.Abp.Identity:{NonNumericPhoneNumberDescription}"] }); }

I understand what you are saying and I partially(or generally) agree. 
Actually, the problem is not with `UserValidator`, in general ABP will try to localize the error code, but you cannot see it localized because it does not support custom errors.

---

If you have no further questions I am closing the issue. Feel free to re-open or create a new issue if you have further questions.

**Closed as completed by berkansasmaz** 2022-12-05 06:50 UTC
Labels: bug
