### ISSUE TITLE
An error is received for the package "toastr.min.css"

### ISSUE THREAD

**Issue by gizemmutukurt** [abpframework/abp#14676] opened 2022-11-15 10:46 UTC
**Command** abp new Acme.BookStoreM71 -t app-nolayers -u blazor-server -d mongodb --preview
**Version:** `7.0.0-rc.1`
**Problem:** If the db is mongo db when the no layer project is created, an error is received for the "toastr.min.css" package.

![image](https://user-images.githubusercontent.com/99716457/201899657-b568c463-881c-430f-9369-be9ca4ff3513.png)

**Comment by enisn** [comment] 2022-11-16 08:25
Couldn't reproduce it with the same command: `abp new Acme.BookStoreM71 -t app-nolayers -u blazor-server -d mongodb --preview`

There might be an issue while running `abp install-libs`. Re-executing `abp install-libs` might solve the problem

**Comment by enisn** [comment] 2022-11-16 08:28
I reproduced it after clicking 'login' button

**Comment by hikalkan** [comment] 2022-11-22 10:55
Resolved by https://github.com/abpframework/abp/commit/54d417d1717b2767c2ab71756af2c90c40d197f8

**Closed as completed by hikalkan** 2022-11-22 10:55 UTC
Labels: bug, priority:high, effort-xs
