### ISSUE TITLE
No service for type 'Volo.Abp.DependencyInjection.ObjectAccessor`1[Microsoft.AspNetCore.Builder.IApplicationBuilder]' has been registered.

### ISSUE THREAD

**Issue by xiatiandegaga** [abpframework/abp#8089] opened 2021-03-17 07:09 UTC
version-4.2.2

Hi, team, i use apollo to  replace default configuration,the  main method like this

`public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((hostBuilderContext, configurationBuilder) =>
                {
                    configurationBuilder.AddApollo(configurationBuilder.Build().GetSection("apollo"));
                })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                })
                .UseSerilog();`

when run  app.InitializeApplication(),   it's error and tips No service for type 'Volo.Abp.DependencyInjection.ObjectAccessor`1[Microsoft.AspNetCore.Builder.IApplicationBuilder]' has been registered.

so i remove apollo configuration to moudle, like this 

`public class CloudApolloModule : AbpModule
    {
        public override void PreConfigureServices(ServiceConfigurationContext context)
        {
            var config = ConfigurationHelper.BuildConfiguration(builderAction: builder =>
             {
                 builder.AddApollo(builder.Build().GetSection("apollo"));
             });
            context.Services.ReplaceConfiguration(config);
            var configuration = context.Services.GetConfiguration();
        }
    }`
but  it doesnot work,can't get  apollo configuration,only the  default appsettings.json

**Comment by realLiangshiwei** [comment] 2021-03-17 07:12
duplicate of https://github.com/abpframework/abp/issues/8090

**Closed as completed by realLiangshiwei** 2021-03-17 07:12 UTC
