### ISSUE TITLE
Test fails when mock tenantId

### ISSUE THREAD

**Issue by Y2zz** [abpframework/abp#2029] opened 2019-10-28 15:31 UTC
![image](https://user-images.githubusercontent.com/252604/67692385-09423a00-f9db-11e9-8da7-2c6360a880a9.png)

I have prepared a [demo](https://github.com/Y2zz/abp-mock-tenant-issue/blob/master/test/demo.Application.Tests/Users/UserAppServiceTests.cs#L28)

**Comment by Y2zz** [comment] 2019-10-28 15:45
@hikalkan This problem is particularly serious and the test cannot be advanced.

**Comment by maliming** [comment] 2019-10-29 01:07
Please use the CLI to create a project and provide the steps needed to reproduce your problem.
`abp new MyProject`

**Comment by Y2zz** [comment] 2019-10-29 01:21
The project is created by cli, and the replay step only needs to run the test.

**Comment by Y2zz** [comment] 2019-10-29 01:42
There is now a simpler way to reproduce

1. Run `abp new project` 
2. Select the `SampleAppServiceTests` test class and add the Mock `ICurrentTenant` related test code.

Or replace with the following code:
```c#
public class SampleAppServiceTests : projectApplicationTestBase
    {
        private readonly IIdentityUserAppService _userAppService;
        private ICurrentTenant _currentTenant;

        public SampleAppServiceTests()
        {
            _userAppService = GetRequiredService<IIdentityUserAppService>();
        }

        protected override void AfterAddApplication(IServiceCollection services)
        {
            _currentTenant = Substitute.For<ICurrentTenant>();
            services.AddSingleton(_currentTenant);
        }

        [Fact]
        public async Task Initial_Data_Should_Contain_Admin_User()
        {
            _currentTenant.Id.Returns(Guid.NewGuid());
            
            //Act
            var result = await _userAppService.GetListAsync(new GetIdentityUsersInput());

            //Assert
            result.TotalCount.ShouldBeGreaterThan(0);
            result.Items.ShouldContain(u => u.UserName == "admin");
        }
    }
```

**Comment by maliming** [comment] 2019-10-29 03:43
The simulated `ICurrentTenant `component does not implement the `Change `function and will cause a loop call.

Try the following way to simulate `ICurrentTenant`: 

![image](https://user-images.githubusercontent.com/6908465/67736086-42ad9080-fa41-11e9-806c-eef6e68bf765.png)

**Comment by Y2zz** [comment] 2019-11-12 13:37
The root cause of this problem is due to use in [`Volo.Abp.MultiTenancy.MultiTenantConnectionStringResolver`](https://github.com/abpframework/abp/blob/8a74d4bca1b203af02bbde2a49225039cafac811/framework/src/Volo.Abp.MultiTenancy/Volo/Abp/MultiTenancy/MultiTenantConnectionStringResolver.cs#L36)
```
var tenantStore = serviceScope
                     .ServiceProvider
                     .GetRequiredService<ITenantStore>();

                 var tenant = tenantStore.Find(_currentTenant.Id.Value);
```

An infinite loop with [`TenantStore`](https://github.com/abpframework/abp/blob/8a74d4bca1b203af02bbde2a49225039cafac811/modules/tenant-management/src/Volo.Abp.TenantManagement.Domain/Volo/Abp/TenantManagement/TenantStore.cs#L73)

**Comment by hikalkan** [comment] 2019-11-28 12:30
I closed this since it is correctly explained by @maliming (https://github.com/abpframework/abp/issues/2029#issuecomment-547243057)

**Closed** 2019-11-28 12:29 UTC
Labels: problem

**Comment by GokhanAtilgan** [comment] 2022-12-29 15:11
Is there a any update for this problem? Because, my application tests are fail. Failed tests have same signatures; Create and Update. Perfectly works fine with Get or Delete operations. When the operations are Create or Update they are having infinite loop problem called on connection string name which is "AbpTenantManagement" and then throwing StackOwerflow Exception.
