### ISSUE TITLE
SmtpEmailSender error when using gmail

### ISSUE THREAD

**Issue by Goxiaoy** [abpframework/abp#1398] opened 2019-06-28 05:05 UTC
When I try to use SmtpEmailSender to send an e-mail with html body, then i got an error
```
[Error] Syntax error, command unrecognized. The server response was: 
System.Net.Mail.SmtpException: Syntax error, command unrecognized. The server response was: 
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result)
   at System.Net.Mail.SmtpTransport.EndGetConnection(IAsyncResult result)
   at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result)
```

So I have to replace ISmtpEmailSender with my own sender

```
     context.Services.Replace(
                ServiceDescriptor.Transient<ISmtpEmailSender, MySmtpEmailSender>());
```

```
    public class MySmtpEmailSender:SmtpEmailSender
    {

        public MySmtpEmailSender(ISmtpEmailSenderConfiguration smtpConfiguration, IBackgroundJobManager backgroundJobManager) : base(smtpConfiguration, backgroundJobManager)
        {
        }

        protected override async Task SendEmailAsync(MailMessage mail)
        {
            AlternateView textView;
            AlternateView htmlView;
            mail = Fix(mail, out textView, out htmlView);
            try
            {
                using (var smtpClient = await BuildClientAsync())
                {
                    await smtpClient.SendMailAsync(mail);
                }
            }
            catch (Exception e)
            {
                throw;
            }
            finally
            {
                textView?.Dispose();
                htmlView?.Dispose();
                mail.Dispose();
            }

        }

        protected override void SendEmail(MailMessage mail)
        {
            AsyncHelper.RunSync(() => SendEmailAsync(mail));
        }


        protected MailMessage Fix(MailMessage message, out AlternateView textView, out AlternateView htmlView)
        {
            htmlView = null;
            textView = null;
            //force set encoding to utf8
            message.BodyEncoding=Encoding.UTF8;
            if (message.IsBodyHtml)
            {
                var mimeType = new ContentType("text/html");
                htmlView = AlternateView.CreateAlternateViewFromString(message.Body, mimeType);
                message.AlternateViews.Add(htmlView);
            }
            else
            {
                const string mediaType = "text/plain";
                textView = AlternateView.CreateAlternateViewFromString(message.Body, message.BodyEncoding, mediaType);
                textView.TransferEncoding = TransferEncoding.SevenBit;
                message.AlternateViews.Add(textView);
            }
            return message;


        }
```

So this works for me.

And I notice that MailMessage BodyEncoding will be automatically set after Body set, so part of codes in 
[EmailSenderBase.cs](https://github.com/abpframework/abp/blob/662dc1d1990bb20f22135bbb83201dfb6df5b17d/framework/src/Volo.Abp.Emailing/Volo/Abp/Emailing/EmailSenderBase.cs#L138) will never run

**Comment by hikalkan** [comment] 2019-06-28 08:29
We'll work on that. Thanks.

**Comment by maliming** [comment] 2019-06-28 14:29
@Goxiaoy Can you share your mail settings? For example, host, port, etc.
I can successfully send html mail at other mail service providers, but gmail seems to have problems. The error you mentioned always appears.

**Comment by Goxiaoy** [comment] 2019-06-29 02:31
@maliming I replace ```ISmtpEmailSenderConfiguration``` so that I can change all the setting definition names and add a new SettingDefinitionProvider to read default value from injection of ```IOptions<SmtpClientOptions>```
So this is my SmtpClientOptions from config file

```
  "SmtpClient": {
    "Host": "smtp.gmail.com",
    "Port": 587,
    "From": "balabala@gmail.com",
    "CredentialsUserName": "balabala@gmail.com",
    "CredentialsPassword": "SUPER_STRONG_PASSWORD",
    "EnableSsl": true,
    "UseDefaultCredentials": false 
  }
```
I live in China which is Internet restricted to gmail but the error metioned happens in my HongKong server before I do those changes.

BTW, is there a convenient way to initial setting values from config file?

**Comment by Goxiaoy** [comment] 2019-06-29 02:37
And for anyone who want to use gmail as smtp sender, "Less secure app access" option in your gmail account setting should be turned on . This is gmail stuff but just in case  someone get here and looking for help

**Comment by maliming** [comment] 2019-06-29 03:37
Our situation is the same (gfw), I can't connect through the proxy.

**Comment by Xeevis** [comment] 2019-07-02 16:31
I have this exact same issue with my national provider. I believe the problem is in the underlying SmtpClient implementation because once I switched to MailKit it started working flawlessly with exact same settings. 

Abp appears to be using the `System.Net.Mail.SmtpClient` which is [marked as Obsolete](https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=netstandard-2.0) and it doesn't support modern protocols.
 
![image](https://user-images.githubusercontent.com/5835044/60529575-2bf76700-9cf7-11e9-951c-1937ab7440f1.png).

![image](https://user-images.githubusercontent.com/5835044/60529623-46c9db80-9cf7-11e9-909f-0e7b8f9dc76d.png)

**Comment by maliming** [comment] 2019-07-03 01:20
Maybe we can use [MailKit](https://github.com/jstedfast/MailKit) directly.

**Closed** 2019-07-18 14:38 UTC
Labels: framework, problem

**Comment by alexandis** [comment] 2020-10-28 21:29
> I have this exact same issue with my national provider (EU). I believe the problem is in the underlying SmtpClient implementation because once I switched to MailKit it started working flawlessly with exact same settings.
> 
> Abp appears to be using the `System.Net.Mail.SmtpClient` which is [marked as Obsolete](https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=netstandard-2.0) and it doesn't support modern protocols.
> 
> ![image](https://user-images.githubusercontent.com/5835044/60529575-2bf76700-9cf7-11e9-951c-1937ab7440f1.png).
> 
> ![image](https://user-images.githubusercontent.com/5835044/60529623-46c9db80-9cf7-11e9-909f-0e7b8f9dc76d.png)

Is it possible to set default option - "Ignore SSL certificate check" - for MailKit without overriding the class? I need to use some handmade certificate for testing purposes. And now I can't use it for "Forgot password" functionality, where I don't write any code for sending messages at all by myself.

**Comment by maliming** [comment] 2020-10-29 01:29
> Is it possible to set default option - "Ignore SSL certificate check" - for MailKit without overriding the class?

This is not good practice. Please create a new issue if you are still other question.
