### ISSUE TITLE
Dynamic Menu System

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#1091] opened 2019-05-05 22:46 UTC
Is a Dynamic Menu System on the devopment roadmap with personalisation for each user ?

**Comment by hikalkan** [comment] 2019-05-07 18:21
Duplicate of https://github.com/abpframework/abp/issues/384

It is not in the development. While we definitely want this, there are much more prioritized works before it.

**Closed by hikalkan** 2019-05-07 18:21 UTC
Labels: duplicate
