### ISSUE TITLE
I have finally deployed abpcentral.com on Azure 

### ISSUE THREAD

**Issue by vnetonline** [abpframework/abp#1203] opened 2019-06-06 06:02 UTC
I have installed the Blog module manually everything works fine on in development environment 

however i an getting a broken page when i navigate to

https://www.abpcentral.com/Blog/AbpCentral

with the following error

[500] Error!
An internal error occurred during your request!

how can i track down what this error relates to ?

**Comment by maliming** [comment] 2019-06-06 06:04
Please check the application log.

**Comment by vnetonline** [comment] 2019-06-06 06:04
where maliming?

**Comment by maliming** [comment] 2019-06-06 06:07
https://github.com/abpframework/abp/blob/master/templates/mvc/src/MyCompanyName.MyProjectName.Web/Program.cs#L21

**Comment by vnetonline** [comment] 2019-06-06 06:20
i am getting the following 

An unhandled exception has occurred while executing the request.
Volo.Abp.AbpException: Could not find file '/libs/owl.carousel/assets/owl.carousel.min.css' using IWebContentFileProvider
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundlerBase.GetFileInfo(IBundlerContext context, String file)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.Styles.StyleBundler.GetFileContent(IBundlerContext context, String file)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundlerBase.Bundle(IBundlerContext context)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundleManager.<>c__DisplayClass17_0.<GetBundleFiles>b__0()
   at System.Collections.Generic.AbpDictionaryExtensions.<>c__DisplayClass6_0`2.<GetOrAdd>b__0(TKey k)
   at System.Collections.Generic.AbpDictionaryExtensions.GetOrAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, Func`2 factory)
   at System.Collections.Generic.AbpDictionaryExtensions.GetOrAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, Func`1 factory)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundleCache.GetOrAdd(String bundleName, Func`1 factory)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundleManager.GetBundleFiles(BundleConfigurationCollection bundles, String bundleName, IBundler bundler)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.BundleManager.GetStyleBundleFiles(String bundleName)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpTagHelperStyleService.GetBundleFiles(String bundleName)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpTagHelperResourceService.ProcessAsync(TagHelperContext context, TagHelperOutput output, List`1 bundleItems, String bundleName)
   at Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpBundleTagHelperService`1.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.RunAsync(TagHelperExecutionContext executionContext)
   at AspNetCore._Pages_Blog_Posts_Index.<ExecuteAsync>b__21_1() in /Pages/Blog/Posts/Index.cshtml:line 19
   at Microsoft.AspNetCore.Mvc.Razor.RazorPage.RenderSectionAsyncCore(String sectionName, Boolean required)
   at AspNetCore._Themes_Basic_Layouts_Application.<>c__DisplayClass15_0.<<ExecuteAsync>b__0>d.MoveNext() in /Themes/Basic/Layouts/Application.cshtml:line 26
--- End of stack trace from previous location where exception was thrown ---

**Comment by vnetonline** [comment] 2019-06-06 06:28
shouldn't running dotnet restore and then yarn have installed all these ?

**Comment by vnetonline** [comment] 2019-06-06 06:54
okay fixed that by uploading files which i know is not the way to fix it 

now when i click on new blog post i am getting the same error

**Comment by maliming** [comment] 2019-06-06 07:49
It seems to be the same problem as #1204

**Comment by vnetonline** [comment] 2019-06-06 07:57
Yes you are correct the packages in the libs fit under wwwroot are not installing when I used publish to azure.

Works on local machine though 

It may have something to do with the virtual file system and embedded files and hence packages are not installing ??? What do you think @maliming

**Comment by 274188A** [comment] 2019-06-06 08:01
I'm seeing exactly the same issue...been hammering this for 2 days...

**Comment by vnetonline** [comment] 2019-06-07 00:21
Okay so I have uploaded all the folders under the wwwroot/libs from the app_io project and the pages are no longer broken.

So the problem is definitely with the css, js files which the blogging module references.

what I don't understand is why does it work locally without these files and why doesn't when you build and publish to azure.

Before publishing to azure I run a yarn and dotnet restore under the Web project and these css, js files under wwwroot/libs are not being downloaded automagically??

can someone please explain this to me?

**Comment by hikalkan** [comment] 2019-06-13 11:11
Closing this since it is duplicate of https://github.com/abpframework/abp/issues/1204 and I will be working on it.

**Closed by hikalkan** 2019-06-13 11:11 UTC
