### ISSUE TITLE
ABP & CMS

### ISSUE THREAD

**Issue by Eliakos** [abpframework/abp#11592] opened 2022-02-16 06:35 UTC
Hello, 

Can ABP work with a .NET CMS such as Orchard or Squidex?
Any example of a supported CMS or a CMS using ABP ?

**Comment by realLiangshiwei** [comment] 2022-02-16 06:52
Duplicate of https://github.com/abpframework/abp/issues/11593

**Comment by realLiangshiwei** [comment] 2022-02-16 06:52
By the way ,we have a cms-kit module: https://github.com/abpframework/abp/tree/dev/modules/cms-kit

**Closed as completed by realLiangshiwei** 2022-02-16 06:52 UTC

**Comment by Eliakos** [comment] 2022-02-16 06:56
> Duplicate of #11593

Orleans and CMS are 2 different universes, having nothing in common, so no duplicate here
