### ISSUE TITLE
Multi-threaded safety

### ISSUE THREAD

**Issue by tangdf** [abpframework/abp#9645] opened 2021-07-24 11:40 UTC
https://github.com/abpframework/abp/blob/5879885deedfe4aadc529cf9c29aa95aec13e342/framework/src/Volo.Abp.RabbitMQ/Volo/Abp/RabbitMQ/RabbitMqMessageConsumer.cs#L132-L139

Whether thread safety needs to be considered here？

**Comment by maliming** [comment] 2021-07-24 12:25
Duplicate of #9644

**Closed as completed by maliming** 2021-07-24 12:25 UTC
