### ISSUE TITLE
After logging in, keep turning around

### ISSUE THREAD

**Issue by sheepx258** [abpframework/abp#6690] opened 2020-12-17 09:41 UTC
api test success
![image](https://user-images.githubusercontent.com/45529787/102470368-d8194300-408e-11eb-9fc3-e91bb9ffec77.png)
angular test fail.(After logging in, keep turning around)
![image](https://user-images.githubusercontent.com/45529787/102470347-cfc10800-408e-11eb-8046-2dbec7c5a1ee.png)
why!?How to solve this problem!?

**Comment by realLiangshiwei** [comment] 2020-12-17 09:46
Duplicate of #6657

**Closed as completed by realLiangshiwei** 2020-12-17 09:46 UTC
