### ISSUE TITLE
The property 'AppUser.ExtraProperties' could not be mapped

### ISSUE THREAD

**Issue by souselesslove** [abpframework/abp#4111] opened 2020-05-27 05:17 UTC
I have a class
```
public class Module: AggregateRoot<Guid>,IHasCreationTime,IModificationAuditedObject
    {
        public virtual Guid? ParentId { get; private set; }
        public virtual string Name { get; private set; }
        public virtual DateTime CreationTime { get; set; }
        public virtual DateTime? LastModificationTime { get; set; }
        public virtual Guid? LastModifierId { get; set; }
   }
```
I want to add PK between "Module" and "AppUser"
```
public static class AuthDbContextModelCreatingExtensions
    {
        public static void ConfigureAuth(this ModelBuilder builder)
        {
            Check.NotNull(builder, nameof(builder));

            builder.Entity<Module>(a =>
            {
                a.ToTable(AuthConsts.DbPrefix + nameof(Module));
                a.ConfigureByConvention();
                a.HasOne<AppUser>().WithMany().HasForeignKey(nameof(Module.LastModifierId));
                a.Property(x => x.Name).IsRequired().HasMaxLength(AuthConsts.ModuleNameMaxLen);
            });
  }
```
when I use "Add-Migration Init",I got error
```
The property 'AppUser.ExtraProperties' could not be mapped, because it is of type 'Dictionary<string, object>' which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
```
then I change "AppUser" to "IdentityUser" , it works...
```
public static class AuthDbContextModelCreatingExtensions
    {
        public static void ConfigureAuth(this ModelBuilder builder)
        {
            Check.NotNull(builder, nameof(builder));

            builder.Entity<Module>(a =>
            {
                a.ToTable(AuthConsts.DbPrefix + nameof(Module));
                a.ConfigureByConvention();
                a.HasOne<IdentityUser>().WithMany().HasForeignKey(nameof(Module.LastModifierId));
                a.Property(x => x.Name).IsRequired().HasMaxLength(AuthConsts.ModuleNameMaxLen);
            });
  }
```
but when I query
```
public class ModuleManager:DomainService
    {
        private readonly IRepository<Module,Guid> _repModule;

        public ModuleManager(IRepository<Module, Guid> repModule)
        {
            _repModule = repModule;
        }
        public async Task<Module> CreateAsync(Guid id, Guid? parentId,string name)
        {
            var exist = await Task.FromResult(_repModule.FirstOrDefault(x => x.Id == id));
            if (exist != null) return exist;
            var m = new Module(id, parentId, name);
            var ret = await _repModule.InsertAsync(m);
            return ret;
        }
    }
```
it is still got error
```
System.InvalidOperationException: 'The property 'IdentityUser.ExtraProperties' could not be mapped, because it is of type 'Dictionary<string, object>' which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using 
```

Abp verison is  [2.8.0](https://github.com/abpframework/abp/releases/tag/2.8.0),I have tried [#1414](https://github.com/abpframework/abp/issues/1414)
Please help me...

**Comment by maliming** [comment] 2020-05-27 06:11
Duplicate of https://github.com/abpframework/abp/issues/3807#issuecomment-627694184

**Closed by maliming** 2020-05-27 06:11 UTC

**Comment by souselesslove** [comment] 2020-05-27 07:41
> Duplicate of [#3807 (comment)](https://github.com/abpframework/abp/issues/3807#issuecomment-627694184)

I'm sorry,it does not work,I download [demo-modified.zip](https://github.com/abpframework/abp/files/4619326/demo-modified.zip)
,I do not change anything,just "add-migration init" "update-database" then run



![1590565204(1)](https://user-images.githubusercontent.com/26608215/82991603-82b51000-a030-11ea-809c-69c9d36dbdd3.jpg)

**Comment by liangshiw** [comment] 2020-06-16 10:17
@souselesslove  https://github.com/abpframework/abp-samples/pull/12 This example contains the correct implementation
