### ISSUE TITLE
Abp does not support connection by account with mongodb

### ISSUE THREAD

**Issue by nguyendev** [abpframework/abp#1534] opened 2019-07-26 08:00 UTC
![image](https://user-images.githubusercontent.com/10234503/61935835-882b6f00-afb5-11e9-9a7a-832bfda2a8f4.png)

**Comment by maliming** [comment] 2019-07-26 08:01
Please provide some logs.

**Comment by nguyendev** [comment] 2019-07-26 08:13
![image](https://user-images.githubusercontent.com/10234503/61936925-e5c0bb00-afb7-11e9-95cb-7b0a03423e4f.png)
It's here

**Comment by nguyendev** [comment] 2019-07-26 08:14
`MongoDB.Driver.MongoAuthenticationException: Unable to authenticate using sasl protocol mechanism SCRAM-SHA-1. ---> MongoDB.Driver.MongoCommandException: Command saslStart failed: Authentication failed..
   at MongoDB.Driver.Core.WireProtocol.CommandUsingQueryMessageWireProtocol`1.ProcessReply(ConnectionId connectionId, ReplyMessage`1 reply)
   at MongoDB.Driver.Core.WireProtocol.CommandUsingQueryMessageWireProtocol`1.ExecuteAsync(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Authentication.SaslAuthenticator.AuthenticateAsync(IConnection connection, ConnectionDescription description, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelperAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.GetChannelAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.AggregateOperation`1.ExecuteAsync(IReadBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteReadOperationAsync[TResult](IReadBinding binding, IReadOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteReadOperationAsync[TResult](IClientSessionHandle session, IReadOperation`1 operation, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.AggregateAsync[TResult](IClientSessionHandle session, PipelineDefinition`2 pipeline, AggregateOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSessionAsync[TResult](Func`2 funcAsync, CancellationToken cancellationToken)
   at MongoDB.Driver.AsyncCursorHelper.FirstOrDefaultAsync[T](Task`1 cursorTask, CancellationToken cancellationToken)
   at Volo.Abp.SettingManagement.MongoDB.MongoSettingRepository.FindAsync(String name, String providerName, String providerKey) in D:\github\abp\modules\setting-management\src\Volo.Abp.SettingManagement.MongoDB\Volo\Abp\SettingManagement\MongoDB\MongoSettingRepository.cs:line 21
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation) in D:\github\abp\framework\src\Volo.Abp.Uow\Volo\Abp\Uow\UnitOfWorkInterceptor.cs:line 47
   at Volo.Abp.Castle.DynamicProxy.CastleAbpInterceptorAdapter`1.ExecuteWithReturnValueAsync[T](IInvocation invocation, IInvocationProceedInfo proceedInfo) in D:\github\abp\framework\src\Volo.Abp.Castle.Core\Volo\Abp\Castle\DynamicProxy\CastleAbpInterceptorAdapter.cs:line 86
   at Volo.Abp.SettingManagement.SettingManagementStore.GetCacheItemAsync(String name, String providerName, String providerKey) in D:\github\abp\modules\setting-management\src\Volo.Abp.SettingManagement.Domain\Volo\Abp\SettingManagement\SettingManagementStore.cs:line 73
   at Volo.Abp.SettingManagement.SettingManagementStore.GetOrNullAsync(String name, String providerName, String providerKey) in D:\github\abp\modules\setting-management\src\Volo.Abp.SettingManagement.Domain\Volo\Abp\SettingManagement\SettingManagementStore.cs:line 29
   at Volo.Abp.Settings.TenantSettingValueProvider.GetOrNullAsync(SettingDefinition setting) in D:\github\abp\framework\src\Volo.Abp.Settings\Volo\Abp\Settings\TenantSettingValueProvider.cs:line 22
   at Volo.Abp.Settings.SettingProvider.GetOrNullValueFromProvidersAsync(IEnumerable`1 providers, SettingDefinition setting) in D:\github\abp\framework\src\Volo.Abp.Settings\Volo\Abp\Settings\SettingProvider.cs:line 91
   at Volo.Abp.Settings.SettingProvider.GetOrNullAsync(String name) in D:\github\abp\framework\src\Volo.Abp.Settings\Volo\Abp\Settings\SettingProvider.cs:line 51
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException[TResult](Task`1 task)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Nito.AsyncEx.Synchronous.TaskExtensions.WaitAndUnwrapException[TResult](Task`1 task)
   at Nito.AsyncEx.AsyncContext.Run[TResult](Func`1 action)
   at Microsoft.AspNetCore.Builder.AbpApplicationBuilderExtensions.UseAbpRequestLocalization(IApplicationBuilder app, Action`1 optionsAction) in D:\github\abp\framework\src\Volo.Abp.AspNetCore\Microsoft\AspNetCore\Builder\AbpApplicationBuilderExtensions.cs:line 56
   at NguyenIT.ThanhNienThuDuc.Web.ThanhNienThuDucWebModule.OnApplicationInitialization(ApplicationInitializationContext context) in E:\Projects\ThanhNienThuDuc\web\src\NguyenIT.ThanhNienThuDuc.Web\ThanhNienThuDucWebModule.cs:line 278
   at Volo.Abp.Modularity.ModuleManager.InitializeModules(ApplicationInitializationContext context) in D:\github\abp\framework\src\Volo.Abp.Core\Volo\Abp\Modularity\ModuleManager.cs:line 39
   at Volo.Abp.AbpApplicationBase.InitializeModules() in D:\github\abp\framework\src\Volo.Abp.Core\Volo\Abp\AbpApplicationBase.cs:line 72
   at NguyenIT.ThanhNienThuDuc.Web.Startup.Configure(IApplicationBuilder app, ILoggerFactory loggerFactory) in E:\Projects\ThanhNienThuDuc\web\src\NguyenIT.ThanhNienThuDuc.Web\Startup.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
2019-07-26 15:12:34.990 +07:00 [INF] Request starting HTTP/2.0 GET https://localhost:44326/  `

**Comment by maliming** [comment] 2019-07-26 08:37
I can't reproduce using MongoDb 4. (docker: `mongo:4`)

`MongoAuthenticationException: Unable to authenticate using sasl protocol mechanism SCRAM-SHA-1.`
It seems to be a problem with your database configuration.

```
"ConnectionStrings": {
    "Default": "mongodb://mongoadmin:secret@192.168.0.2:27018|BookStore"
}
```

**Comment by nguyendev** [comment] 2019-07-26 08:42
how to fix it ?

**Comment by maliming** [comment] 2019-07-26 08:46
I am not familiar with mongodb, abp uses the [MongoDB.Driver](https://www.nuget.org/packages/MongoDB.Driver/2.8.1) component.

https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/framework/src/Volo.Abp.MongoDB/Volo/Abp/Uow/MongoDB/UnitOfWorkMongoDbContextProvider.cs#L50

Maybe you can google it

**Comment by nguyendev** [comment] 2019-07-26 08:55
I found a way
`var connectionString = @"mongodb://usr:pwd@srv1.acme.net,srv2.acme.net,srv3.acme.net/dbName?replicaSet=rset";
var mongoUrl = new MongoUrl(connectionString);
var dbname = mongoUrl.DatabaseName;
var db = new MongoClient(mongoUrl).GetDatabase(dbname);`

**Comment by maliming** [comment] 2019-07-26 09:03
This seems more standard, @hikalkan  why do we use **|** to split the database connection string and database name?

**Comment by nguyendev** [comment] 2019-07-29 01:26
can you fix it in the next version ?

**Comment by hikalkan** [comment] 2019-08-02 13:24
It will be fixed in the next version, as a breaking change.

**Closed** 2019-08-05 15:22 UTC
Labels: breaking change

**Comment by rickcoder** [comment] 2019-09-28 01:38
try to specified parameters authSource=admin, like this
var connectionString = "mongodb://usr:pwd@host/dbName?authSource=admin";
