### ISSUE TITLE
GCP Blob Storage Provider

### ISSUE THREAD

**Issue by ImranHugoWT** [abpframework/abp#16260] opened 2023-04-13 05:15 UTC
2 of the big storage providers are already implemented. (Azure and AWS).  It would be ideal if Google were added to the list of supported providers.

Some solutions for certain clients are hosted on GCP.

**Comment by EngincanV** [comment] 2024-08-21 17:25
> 2 of the big storage providers are already implemented. (Azure and AWS). It would be ideal if Google were added to the list of supported providers.

> Some solutions for certain clients are hosted on GCP.

I created a provider package for [Google Cloud Storage](https://github.com/EngincanV/Volo.Abp.BlobStoring.Gcp) and published it on [NuGet](https://www.nuget.org/packages/BlobStoring.Providers.GoogleCloudStorage):

```bash
dotnet add package BlobStoring.Providers.GoogleCloudStorage --version 1.0.0
```

I'll create an article soon, but you can check it out now. I explained the related configuration that you need to do in README.md.

**Comment by hikalkan** [comment] 2024-09-03 12:42
Duplicate of https://github.com/abpframework/abp/issues/20618

**Closed as completed by hikalkan** 2024-09-03 12:42 UTC
Labels: duplicate
