### ISSUE TITLE
Document Dynamic features

### ISSUE THREAD

**Issue by EngincanV** [abpframework/abp#14871] opened 2022-11-29 08:58 UTC
Based on https://github.com/abpframework/abp/issues/13760

**Comment by maliming** [comment] 2022-11-30 02:27
Wait for https://github.com/abpframework/abp/issues/13758

**Comment by hikalkan** [comment] 2022-12-27 09:05
I think this is duplicate of https://github.com/abpframework/abp/issues/13758

**Closed as completed by hikalkan** 2022-12-27 09:05 UTC
Labels: duplicate
