### ISSUE TITLE
What types of entities have the ConcurrencyStamp on them?

### ISSUE THREAD

**Issue by djlaney3** [abpframework/abp#737] opened 2019-01-16 17:49 UTC
What types of entities have the ConcurrencyStamp on them?  I created two audited entities, in a parent child relationship, but the child threw an exception that it needed the ConcurrencyStamp field.  What types of entities require it?

**Comment by hitaspdotnet** [comment] 2019-01-17 07:52
Aggregate entities

**Comment by djlaney3** [comment] 2019-01-17 13:46
I'm not sure I fully understand.  I have two entities which both inherit from AuditedEntity<int>, and I both underlying tables did not have ConcurrencyStamp field.  When I tried to do a CRUD operation, abp errored with "Invalid field ConcurrencyStamp".  I then added that field to the one table, and it worked.   As stated before, these are a parent child set of entities.  And it was the child that required the field.

**Comment by djlaney3** [comment] 2019-01-17 19:30
My design in this case doesn't call for Aggregates.  These are simple entities, country and state.

**Comment by hikalkan** [comment] 2019-01-19 16:45
@djlaney3 if it's inherited from AuditedEntity then you don't have to deal with the `ConcurrencyStamp` stuff since AuditedEntity does not implement it. It would be good if you can share some code so we can reproduce it.

**Comment by djlaney3** [comment] 2019-01-20 14:33
Do you still need a sample?  I worked past my issue by changing them to aggretate audited entities.

**Comment by hikalkan** [comment] 2019-01-20 18:50
OK, I'm moving this to backlog to check later.

**Comment by hitaspdotnet** [comment] 2019-01-20 19:12
@hikalkan I had same problem with `Entity<Key>` and using `IRepository<Entity, Key>` when I missed default repositories configuration. Then I changed the type to aggregate and problem solves. I'm not sure the problem is the `AddDefaultRepositories(includeAllEntities: true)` in module configuration cuz I haven't the type of entities anymore.

**Closed** 2023-08-20 10:48 UTC
Labels: question
