### ISSUE TITLE
Identify Server 4-v4 support 

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#4723] opened 2020-07-11 00:10 UTC
https://www.identityserver.com/articles/migrating-your-identityserver4-v3-database-to-identityserver4-v4

Any plans to support identify server 4 v4?

**Comment by liangshiw** [comment] 2020-07-11 00:41
Duplicate of https://github.com/abpframework/abp/issues/4461

**Closed by liangshiw** 2020-07-11 00:41 UTC
Labels: duplicate
