### ISSUE TITLE
Error loading the theme after some inactive time

### ISSUE THREAD

**Issue by ageiter** [abpframework/abp#15681] opened 2023-02-13 08:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If the user was logged in and comes back to the page after a long time (e.g. the next day), there is an error loading the page. 

Theme is not displayed properly, the user is not loaded and an error message appears.

![image](https://user-images.githubusercontent.com/17644153/218404440-1cc327dc-b6c7-4e58-b32b-99a82a375e62.png)

If you then refresh the page (F5), then everything works normally again.

Logfile: 
[logs.txt](https://github.com/abpframework/abp/files/10720010/logs.txt)

### Reproduction Steps

Is difficult to reproduce. For me, however, the error occurs frequently with the following procedure:
1. open page and log in
2. close browser tab
3. reopen the page the next day / the day after (note: PC was in sleep mode, browser is not reopened, only the tab ... if that would make a difference)

### Expected behavior

Either show login window or log the user in again and show page correctly

### Actual behavior

Page is loaded incompletely (see screenshot), login window is NOT displayed.

### Regression?

Problem occurred with version 5.3.1, 6.0.1 and 7.0.1

### Known Workarounds

Reload page (F5)

### Version

7.0.1

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

### Other information

- Site runs on Azure. 
- Screenshot and log file was anonymized.
- Maybe same problem as with this issue: [Issue15676](https://github.com/abpframework/abp/issues/15676)

**Comment by berkansasmaz** [comment] 2023-02-21 10:47
I don't think this is related to ABP. Because, blazor server user sessions will go away after a few minutes when the client has disconnected the underlying SignalR connection. What's happening here is the browser is stopping the connection when the the sleep mode is activated and after a while the server will discard the session. When the client tries to reconnect, say 10 minutes later, the session is gone and the user needs to refresh the page to start a new session. Maybe the problem can be solved by changing [Circuit handler options](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-7.0#circuit-handler-options-for-blazor-server-apps) or customizing the reconnection handler, but I'm not entirely sure.


See more: 
- https://github.com/dotnet/aspnetcore/issues/29728
- https://learn.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-7.0#blazor-server
- https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-7.0#circuit-handler-options-for-blazor-server-apps

---
Closing the issue. Feel free to re-open or create a new issue if you have further questions.

**Comment by ageiter** [comment] 2023-02-21 13:06
Yes, I'm already understanding that. But the point is not that the page would still be open in the browser and I just redisplay it. I enter the URL in a new browser tab and THEN the error comes. 

I would imagine that the redirect to the login page is not working. I have now added the following in the OnInitializedAsync method:

```
protected override async Task OnInitializedAsync()
{
   if (!CurrentUser.IsAuthenticated)
   {
       NavigationManager.NavigateTo("/Account/Login", true);
   } 
}
```

But it can't be the solution that I have to add this on every page myself?

PS: I can't confirm that this works yet, I couldn't do the deployment yet.

**Comment by berkansasmaz** [comment] 2023-02-21 14:00
Can you confirm @enisn?

**Comment by enisn** [comment] 2023-02-21 20:01
I reproduced the issue. We'll try to figure out the reason and solve asap

**Comment by ebicoglu** [comment] 2023-03-08 09:01
can we resolve this in 7.1 stable?

**Comment by stristan** [comment] 2023-03-08 16:21
Probably this issue is also related?
https://github.com/abpframework/abp/issues/14068#event-8107012524

**Comment by enisn** [comment] 2023-03-09 06:16
> Probably this issue is also related? [#14068 (comment)](https://github.com/abpframework/abp/issues/14068#event-8107012524)

@maliming any idea on this?

**Comment by maliming** [comment] 2023-03-09 06:40
hi @stristan 

Can you try this? https://github.com/abpframework/abp/pull/15876

**Closed as completed** 2023-03-09 07:13 UTC
Labels: bug, ui-blazor, effort-xs
