### ISSUE TITLE
Unauthorized application method doesn't return 401

### ISSUE THREAD

**Issue by cocosip** [abpframework/abp#11311] opened 2022-01-13 13:40 UTC
Why abp api doesn't return 401 with json format?

ABP version: ABP 5.1.1
Create a angular temp by Abp Cli , then add application service and controller

application service
```c#
[Authorize]
    public class Test1AppService : AbpDemo111AppService, ITest1AppService
    {
        public virtual Task<string> GetNameAsync()
        {
            return Task.FromResult("123");
        }
    }
```

controller
```c#
 [Area("demo111")]
    [Route("api/test1")]
    public class Test1Controller : AbpDemo111Controller, ITest1AppService, IRemoteService
    {
        private readonly ITest1AppService _test1AppService;

        public Test1Controller(ITest1AppService test1AppService)
        {
            _test1AppService = test1AppService;
        }

        [HttpGet]
        public async Task<string> GetNameAsync()
        {
            return await _test1AppService.GetNameAsync();
        }
    }
```

When call the url  `/api/test1`, it redirect to `/Account/Login` page, and  in an internal error is thrown .

```c#
[21:16:15 INF] Authorization failed. These requirements were not met:
PermissionRequirement: xxx
[21:16:16 WRN] ---------- RemoteServiceErrorInfo ----------
{
  "code": "Volo.Authorization:010001",
  "message": "Authorization failed! Given policy has not granted.",
  "details": null,
  "data": {},
  "validationErrors": null
}

[21:16:16 WRN] Exception of type 'Volo.Abp.Authorization.AbpAuthorizationException' was thrown.
Volo.Abp.Authorization.AbpAuthorizationException: Exception of type 'Volo.Abp.Authorization.AbpAuthorizationException' was thrown.
   at Microsoft.AspNetCore.Authorization.AbpAuthorizationServiceExtensions.CheckAsync(IAuthorizationService authorizationService, AuthorizationPolicy policy)

...


[21:16:16 WRN] Code:Volo.Authorization:010001
[21:16:16 INF] AuthenticationScheme: Identity.Application was challenged.
[21:16:16 INF] Executed action AbpDemo111.Controllers.Test1Controller.GetNameAsync (AbpDemo111.HttpApi) in 440.5948ms

```

**Comment by realLiangshiwei** [comment] 2022-01-13 14:37
Duplicate of https://github.com/abpframework/abp/issues/5235

**Closed as completed by realLiangshiwei** 2022-01-13 14:37 UTC

**Comment by cocosip** [comment] 2022-01-13 14:52
> Duplicate of https://github.com/abpframework/abp/issues/5235

Are you sure?!
