### ISSUE TITLE
define ICollection<ValueObject> into appuser

### ISSUE THREAD

**Issue by cqgis** [abpframework/abp#2192] opened 2019-11-17 15:23 UTC
I define valueobject called DataUser
``` c#
   public class DataUser : ValueObject
    {
        public string Name { get; set; }
        protected override IEnumerable<object> GetAtomicValues()
        {
            return new[] { Name };
        }
    }
```
I add it to AppUser
``` c#
   public class AppUser : FullAuditedAggregateRoot<Guid>, IUser
    {
       ...
        public ICollection<DataUser> DataUsers { get; protected set; }
    }

```

and configure
``` c#
        public static void ConfigureCustomUserProperties<TUser>(this EntityTypeBuilder<TUser> b)
            where TUser : class, IUser
        {

            b.OwnsMany(nameof(ICollection<DataUser>), nameof(AppUser.DataUsers), t =>
                           {
                               t.Property<int>("Id");
                               t.HasKey("Id");
                           });
        }
```

I got error on test 

```
 System.InvalidOperationException : The navigation property 'DataUsers' cannot be added to the entity type 'IdentityUser' because the target entity type 'ICollection' is defined in shadow state and navigations properties cannot point to shadow state entities.
```

abp version is 1.0.2， how can I solve it, thanks

**Comment by maliming** [comment] 2019-11-18 01:11
Please check the documentation for EF Core.
https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities

**Comment by maliming** [comment] 2019-11-18 01:14
Please check the documentation for EF Core. https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities

If you use EF Core directly. Does the above code work?

**Comment by cqgis** [comment] 2019-11-18 01:31
> Please check the documentation for EF Core. https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities
> 
> If you use EF Core directly. Does the above code work?

yes ,it's will work if I define in other entity, but not in appuser

**Comment by maliming** [comment] 2019-11-18 08:08
This seems to be a limitation of EF Core.

**Comment by cqgis** [comment] 2019-11-20 12:58
I think it's problem about  appuser and identityuser   database migration. In other entity ,it's ok

**Comment by newacc12** [comment] 2020-02-18 04:54
@cqgis did you ever find a solution for this?

**Comment by hikalkan** [comment] 2020-03-05 15:56
Duplicate of https://github.com/abpframework/abp/issues/1414

**Closed by hikalkan** 2020-03-05 15:56 UTC
