### ISSUE TITLE
Pages Books Index ExecuteAsync() no suitable method found to override

### ISSUE THREAD

**Issue by yurii-shchehliuk** [abpframework/abp#4511] opened 2020-06-28 10:22 UTC
* version**2.9.0(latest)**.
*_ui_: Razor Pages
*_Exception message_: Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0115	'Pages_Books_Index.ExecuteAsync()': no suitable method found to override	Acme.BookStore.Web	C:\Users\Jerzy\Acme.BookStore\aspnet-core\src\Acme.BookStore.Web\obj\Debug\netcoreapp3.1\Razor\Pages\Books\Index.cshtml.g.cs	50	Active
** 

Firstly, I want to note that this problem occurs in two places. The first is “index.cshtml.g.cs” and “index.cshtml”.
By the way, such a class as "BookStorePage" does not exist, but there is a "BookStorePageModel" where this problem occurs.
I am doing the first project step by step on the documentation, but I can not deal with it myself.
thank

**Comment by hikalkan** [comment] 2020-06-28 10:32
If that's a sample project, can you share its source code?

**Comment by liangshiw** [comment] 2020-06-28 11:51
Duplicate of https://github.com/abpframework/abp/issues/4333

**Closed by liangshiw** 2020-06-28 11:51 UTC
