### ISSUE TITLE
CurrentUser.UserName is null in Blazor Server + SignalR project

### ISSUE THREAD

**Issue by Kobus-Smit** [abpframework/abp#8683] opened 2021-04-19 10:45 UTC
* ABP Framework version: 4.3.0-rc.2
* User Interface type: Blazor Server (not tiered)
* Database provider: MongoDB

1. Creating a new Blazor WebAssembly project and [adding SignalR-Integration](https://docs.abp.io/en/abp/4.3/SignalR-Integration)
works fine and the `CurrentUser.UserName` is populated:
`abp new Test -u blazor -d mongodb -v 4.3.0-rc.2 --preview`
https://github.com/Kobus-Smit/abp-blazor-wasm-signalr
![image](https://user-images.githubusercontent.com/11263864/115223862-9dfca280-a14f-11eb-9a2a-4138dd5d96eb.png)

2. but doing the same in a Blazor Server project,  then `CurrentUser.UserName` is null 
`abp new Test -u blazor-server -d mongodb -v 4.3.0-rc.2 --preview`
https://github.com/Kobus-Smit/abp-blazor-server-signalr
![image](https://user-images.githubusercontent.com/11263864/115223955-b5d42680-a14f-11eb-9558-9d445761b9f7.png)

PS: Many thanks for this great framework!

**Comment by ebicoglu** [comment] 2021-04-19 21:13
@cotur will try to reproduce it.

**Comment by hikalkan** [comment] 2021-04-19 23:31
Maybe related to https://github.com/abpframework/abp/issues/8240 (while it is WASM)

**Comment by cotur** [comment] 2021-04-19 23:34
It's reproducible,

By the way, @Kobus-Smit thanks so much for this well explained issue.

We should show this issue everywhere as a "How the bug report should be". :)

**Comment by Kobus-Smit** [comment] 2021-04-20 01:03
@cotur ;) No worries mate! I believe [Minimal Reproducible Examples](https://stackoverflow.com/help/minimal-reproducible-example) are always helpful.


@hikalkan , might be related, but with #8240 the username is available after refreshing the page, in contrast , `CurrentUser.UserName` stays null after refreshing the page in my sample projects.

**Comment by Kobus-Smit** [comment] 2021-04-20 01:51
Reading Microsoft's docs [Authentication and authorization in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-5.0#cookie-authentication) it sounds like `Cookie authentication` should just work, no additional configuration needed?

Alternatively, `Bearer token authentication` can be used by setting the [AccessTokenProvider ](https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-5.0&tabs=dotnet#configure-bearer-authentication)

```csharp
var connection = new HubConnectionBuilder()
    .WithUrl("https://example.com/chathub", options =>
    { 
        options.AccessTokenProvider = () => Task.FromResult(_myAccessToken);
    })
    .Build();
```

In WASM I can get the access token with [IAccessTokenProvider.RequestAccessToken](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.webassembly.authentication.iaccesstokenprovider.requestaccesstoken?view=aspnetcore-5.0#Microsoft_AspNetCore_Components_WebAssembly_Authentication_IAccessTokenProvider_RequestAccessToken_Microsoft_AspNetCore_Components_WebAssembly_Authentication_AccessTokenRequestOptions_), but apparently not as straight forward with Blazor Server:
* Can't get the token from HttpContext 
  * as [HttpContext is not available in a Blazor Server App](https://stackoverflow.com/a/60429643/119789) 
  * From [docs.microsoft.com](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-5.0#blazor-and-shared-state): Additionally, again for security reasons, you must not use IHttpContextAccessor within Blazor apps. Blazor apps run outside of the context of the ASP.NET Core pipeline. The HttpContext isn't guaranteed to be available within the IHttpContextAccessor, nor is it guaranteed to be holding the context that started the Blazor app
* I had a look at [Pass tokens to a Blazor Server app](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-5.0#pass-tokens-to-a-blazor-server-app) but `HttpContext.GetTokenAsync("access_token")` is null.  Is the `options.Scope.Add("offline_access")` a clue?
* Should I add `AddAbpOpenIdConnect` in my `Blazor Not Tiered` as in the `Blazor Server Tiered` project? Probably not? https://github.com/abpframework/abp/blob/62e1b238ced052f37f8c65695b867870b22768d8/templates/app/aspnet-core/src/MyCompanyName.MyProjectName.Blazor.Server.Tiered/MyProjectNameBlazorModule.cs#L166

Other related links that might help:
  * https://stackoverflow.com/questions/59891352/how-do-i-get-the-access-token-from-a-blazor-server-side-web-app
  * https://stackoverflow.com/questions/59638965/how-to-add-openidconnect-via-identityserver4-to-asp-net-core-serverside-blazor-w
  * https://github.com/enetstudio/SignalRServerIdentityAuthentication looks promising

**Comment by hikalkan** [comment] 2021-04-20 23:21
It worked when I pass cookies to the server:

````csharp
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.SignalR.Client;

namespace Test.Blazor.Pages
{
    public partial class Index 
    {
        [Inject]
        public IHttpContextAccessor HttpContextAccessor { get; set; }
        
        private HubConnection hubConnection;

        protected override async Task OnInitializedAsync()
        {
            await base.OnInitializedAsync();

            if (CurrentUser.IsAuthenticated)
            {
                hubConnection = new HubConnectionBuilder()
                    .WithUrl("https://localhost:44313/signalr-hubs/messaging", options =>
                    {
                        if (HttpContextAccessor.HttpContext != null)
                        {
                            foreach (var cookie in HttpContextAccessor.HttpContext.Request.Cookies)
                            {
                                options.Cookies.Add(new Cookie(cookie.Key, cookie.Value, null, "localhost"));  
                            }
                        }
                    }).Build();
                await hubConnection.StartAsync();
            }
        }

        public async ValueTask DisposeAsync()
        {
            if (hubConnection != null)
            {
                await hubConnection.DisposeAsync();
            }
        }
    }
}
````

Result:

![image](https://user-images.githubusercontent.com/1210527/115474843-05494e00-a247-11eb-99a0-6d81f35f1adb.png)

From the [Microsoft's documentation](url), we should consider the second part, because in blazor app, we are using .NET Client. Request is not coming from browser (interestingly, server connects to itself):

![image](https://user-images.githubusercontent.com/1210527/115474961-4f323400-a247-11eb-89f0-84d1d5a5b5bd.png)

However, I accessed the current `HttpContext` to get cookies. I am not sure where to get them (maybe from browser if somehow possible).

ABP's startup template uses cookie auth for blazor server app, so there is no bearer token that we can grab in the blazor app. Authentication stuff is done in the startup template actually, not related to the framework, so you can setup a different authentication method. We will continue to investigate alternative ways in the next milestone. If you've any suggestion, please write here. Thanks for your detailed descriptions.

**Comment by Kobus-Smit** [comment] 2021-04-21 01:09
Thanks @hikalkan , I'll pass the cookies to the server for now.

**Comment by hikalkan** [comment] 2021-05-11 01:10
I am closing this. You can reopen if you need.

**Closed as completed by hikalkan** 2021-05-11 01:10 UTC
Labels: abp-template-app, problem, ui-blazor
