### ISSUE TITLE
The "IdentityServerApiSecrets" table creates an index error

### ISSUE THREAD

**Issue by wisplan** [abpframework/abp#2330] opened 2019-12-07 19:16 UTC
When I migrated the database to mariadb10.3 (mysql), the IdentityServerApiSecrets table created an index error, and the error was as follows:
Failed executing DbCommand (3ms) [Parameters = [], CommandType = 'Text', CommandTimeout = '30 ']
CREATE TABLE `IdentityServerApiSecrets` (
     `Type` varchar (250) NOT NULL,
     `Value` longtext NOT NULL,
     `ApiResourceId` char (36) NOT NULL,
     `Description` varchar (2000) NULL,
     `Expiration` datetime (6) NULL,
     CONSTRAINT `PK_IdentityServerApiSecrets` PRIMARY KEY (` ApiResourceId`, `Type`,` Value`),
     CONSTRAINT `FK_IdentityServerApiSecrets_IdentityServerApiResources_ApiResou ~` FOREIGN KEY (`ApiResourceId`) REFERENCES` IdentityServerApiResources` (`Id`) ON DELETE CASCADE
);
MySql.Data.MySqlClient.MySqlException (0x80004005): BLOB / TEXT column 'Value' used in key specification without a key length
![image](https://user-images.githubusercontent.com/32763748/70379558-17379300-1969-11ea-904a-6348b00f9bc8.png)

**Comment by maliming** [comment] 2019-12-08 02:24
Duplicate of https://github.com/abpframework/abp/issues/1920#issuecomment-543551659 https://github.com/abpframework/abp/issues/2053#issuecomment-548626182

**Closed by maliming** 2019-12-08 02:24 UTC
