### ISSUE TITLE
Using __tenant on query string does not change the tenant.

### ISSUE THREAD

**Issue by andre-artus** [abpframework/abp#7349] opened 2021-01-19 20:40 UTC
I wish to have my [Angular] homepage show a list of tenants with each one being a link to the related tenant.

When I pass `__tenant` on the query string (e.g. `http://localhost:4200/?__tenant=tenant1` it does not do anything.

The documantation indicates that `QueryStringTenantResolveContributor` is part of the tenant resolution pipeline by default, but I've even tried adding the following to `ConfigureServices` with no joy. 

```
 services.Configure<AbpTenantResolveOptions>(options =>
            {
                options.TenantResolvers.Add(new QueryStringTenantResolveContributor());
            });
```

When I attempt to list the resolvers I only get "CurrentUser".

```
    var ro = new AbpTenantResolveOptions(); 
    foreach (var tenantResolveContributor in ro.TenantResolvers)
    {
        Console.WriteLine(tenantResolveContributor);
    }
```

**Comment by davidzwa** [comment] 2021-01-19 21:13
Angular provides the tenantId in the Header field.

https://github.com/abpframework/abp/blob/badad8d59f02bb0ccba433b49a7fc24ee7bf3b5a/npm/ng-packs/packages/core/src/lib/interceptors/api.interceptor.ts#L43

Docs on Angular and the header
https://docs.abp.io/en/abp/latest/UI/Angular/Multi-Tenancy#see-also

Can you check whether this HTTP header __tenant is not set? This could explain your situation. But in all cases, please provide more code, as the authors might not be able to effectively answer your question without.

**Comment by andre-artus** [comment] 2021-01-19 21:38
Thank you @davidzwa,

I've read the docs, and from it concluded (perhaps mistakenly) that I can change the tenant using either the query string, or if the domain resolver has been added, from the domain/subdomain. But it does not work for me.

 The header is set, but only when I switch (and log in) tenants on the login page.

I wish to have a list of links on my page that can take a user to a tenant (likely to the login screen), but passing it on the query string does nothing. I cannot set the header from the link.

I'm not sure what code I could add, I'm passing the url (`http://localhost:4200/?__tenant=tenant1`) straight to the browser for now, with the intention of later listing it on my page.

**Comment by davidzwa** [comment] 2021-01-19 22:38
Ah now that I read your initial `Console.WriteLine(...)` result better I see that your conclusion is not entirely correct. I got the same when checking the options the line after, but the result was completely different when I injected the options in a controller for test (when the application was fully booted):

``` 
    public class VersionController : BaseV2Controller
    {
        private readonly IOptions<AbpTenantResolveOptions> abptenantResolveOptions;

        public VersionController(
            IOptions<AbpTenantResolveOptions> abptenantResolveOptions
        )
        {
            this.abptenantResolveOptions = abptenantResolveOptions;
        }

        [HttpGet]
        [AllowAnonymous]
        public OpenApiInfo Version()
        {
            return APIDefinition.APIVersionInfo;
        }
    }
    public class VersionController : AbpController
    {
        private readonly IOptions<AbpTenantResolveOptions> abptenantResolveOptions;

        public VersionController(
            IOptions<AbpTenantResolveOptions> abptenantResolveOptions
        )
        {
            this.abptenantResolveOptions = abptenantResolveOptions;
        }

        [HttpGet]
        [AllowAnonymous]
        public string Version()
        {
            // Breakpoint here and check this.abptenantResolveOptions.value above
            return "fake_version";
        }
    }
```

Now what I think might be going wrong is that the tenantId in your JWT or access token claims is checked before everything else. This would mean the tenant is resolved before any other resolver can do this. The reason I think this is because `CurrentUserTenantResolveContributor` is on the top of the list.
![image](https://user-images.githubusercontent.com/6005355/105102306-287d2980-5aaf-11eb-82ee-84aea6a74bf7.png)
So if you look carefully at the image, you see that I was able to append my QueryStringTenantResolverContributor (ok ok it's double, but it shows how the system works)! This means the question is: how to reorder this list or remove some you dont want 👍🏼 

So the cause for your problem is not yet 100% clear to me as I dont fully know if you're logged in or not, but not having a login token is a start to debug it: clear the session/localstorage, restart the webapp page and try by adding the `__tenant=TENANT_ID_HERE` where TENANT_ID_HERE should be a valid and existing TenantId (Guid).
As a final test make sure to add the HTTP Header as well as the Query string tenant. The tenantId in the query string should then have preference.

I will try the same tomorrow if I can. Also working out this system myself.

**Comment by davidzwa** [comment] 2021-01-19 22:44
```
        public override void OnPostApplicationInitialization(ApplicationInitializationContext context)
        {
            base.OnPostApplicationInitialization(context);

            var ro = context.ServiceProvider.GetRequiredService<IOptions<AbpTenantResolveOptions>>().Value;
            //var ro = new AbpTenantResolveOptions();
            foreach (var tenantResolveContributor in ro.TenantResolvers)
            {
                Console.WriteLine(tenantResolveContributor);
            }
        }
```
I believe injecting is always the best way to check as direct instantiation might (as you saw) give unreliable results.
The code above gives me 6 tenant resolvers by debugging/logging in the module itself at startup (so you dont have to call a Controller or something alike). In this case I didnt add any resolver, so 6 of them makes sense.

**Comment by davidzwa** [comment] 2021-01-19 22:53
Ugh I feel stupid now.

```
Configure<AbpTenantResolveOptions>(options =>
{
    var allResolvers = options;
    // allResolvers contains all 6 default resolvers. Adjusting or overwriting this list with a new order gives you full control
});
```
See my comment within the Configure() call above.
Do note ABP suggests you to not change the order for security reasons "CurrentUserTenantResolveContributor. This should always be the first contributor for the security.". Does not mean you have to follow everything they say ;)

**Comment by ilkayilknur** [comment] 2021-01-22 14:38
Closing the issue. Feel free to re-open or create a new issue if you have further questions.

**Closed as completed by ilkayilknur** 2021-01-22 14:38 UTC

**Comment by andre-artus** [comment] 2021-01-28 15:07
Thanks @davidzwa
