### ISSUE TITLE
Unable to change profile picture on abp.io

### ISSUE THREAD

**Issue by Trojaner** [abpframework/abp#11971] opened 2022-03-15 11:14 UTC
![](https://i.imgur.com/ODXqEjW.gif)

Maybe related; this error shows up in console
![image](https://user-images.githubusercontent.com/1809172/158365219-8832fa61-983a-4d3f-8d1d-31e5f8a2a07e.png)

**Comment by berkansasmaz** [comment] 2022-03-15 11:16
Thanks for the report @Trojaner  🎉

We will fix this issue as soon as possible.

**Comment by johan-developer** [comment] 2022-03-15 23:39
Hello, I had this problem in Blazor Wasm, exists any workaround.
Thank you,

**Comment by berkansasmaz** [comment] 2022-03-16 07:43
The problem is in version `5.2.0-rc.1`, you can downgrade to `5.1.4` version if you want, or wait for the new version to come out for `5.2.0-rc.*`.

The easiest workaround would be to just downgrade the `@abp/uppy` package to `5.1.4`.

For example, downloading a template with version 5.1.4 and copying the `wwwroot/libs/uppy` folder, and replacing it with the wrong one will solve the problem.

<img width="1680" alt="Screen Shot 2022-03-16 at 10 26 05" src="https://user-images.githubusercontent.com/31216880/158540451-aeac4c83-8539-46ff-85c4-31a90ddea346.png">

**Disclaimer:** Copying will solve your problem but if you run `abp install-libs` again the problem will occur again.

My recommendation would be to make this copying process permanent by following [this document](https://docs.abp.io/en/abp/latest/UI/AspNetCore/Client-Side-Package-Management).

**Note**: Do not forget to revert this operation when the new version is released.

**Comment by berkansasmaz** [comment] 2022-03-16 07:47
Since this issue is related to the app-pro template I'm closing this issue and creating an internal issue, FYI.

**Closed as completed by berkansasmaz** 2022-03-16 07:47 UTC

**Comment by EngincanV** [comment] 2022-03-16 07:51
> Hello, I had this problem in Blazor Wasm, exists any workaround. Thank you,

For a quick-workaround, you can add a [resolutions section](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/#toc-how-to-use-it) to your package.json file and downgrade the `@abp/uppy` package to 5.1.4 as below:

```json
"resolutions": {
   "@abp/uppy": "5.1.4"
}
```

And then run the `abp install-libs` comand on the directory.

**Comment by berkansasmaz** [comment] 2022-03-16 08:06
> > Hello, I had this problem in Blazor Wasm, exists any workaround. Thank you,
> 
> For a quick-workaround, you can add a [resolutions section](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/#toc-how-to-use-it) to your package.json file and downgrade the `@abp/uppy` package to 5.1.4 as below:
> 
> ```json
> "resolutions": {
>    "@abp/uppy": "5.1.4"
> }
> ```
> 
> And then run the `abp install-libs` comand on the directory.

Yes, this solution definitely makes more sense, thanks @EngincanV for the correction.
