### ISSUE TITLE
Implementing CQRS Pattern using ABP Framework

### ISSUE THREAD

**Issue by naushadkhalid** [abpframework/abp#6740] opened 2020-12-21 14:39 UTC
we are developing an HR Management Software and have planned to use ABP Commercial. wanted to see some documentation or working demo if any available for the same.

**Comment by realLiangshiwei** [comment] 2020-12-22 01:16
Duplicate of https://github.com/abpframework/abp/issues/57

**Closed as completed by realLiangshiwei** 2020-12-22 01:16 UTC
