### ISSUE TITLE
The query parameter named action is automatically replaced with the method name in the application service

### ISSUE THREAD

**Issue by 2hao** [abpframework/abp#15021] opened 2022-12-08 09:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

```
public class TestAppService: ApplicationService
{
    public string GetWrongQueryParam(string action)
    {
        Console.WriteLine(action);
        return action;
    }
}

```
the method always receive `GetWrongQueryParam` when i input any string;

### Version

6.0.2

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment] 2022-12-08 09:08
Duplicate of #13241

**Closed as completed by maliming** 2022-12-08 09:08 UTC

**Comment by 2hao** [comment] 2022-12-08 09:44
Thanks
