### ISSUE TITLE
ABP CLI get-source fails for Volo.Docs.Admin

### ISSUE THREAD

**Issue by sanghel-payoff** [abpframework/abp#12433] opened 2022-05-04 11:27 UTC
ABP Commercial 2.5.1 Angular EFCore

Download sources fails for _Volo.Docs.Admin_

`abp get-source Volo.Docs.Admin`

stack trace in abp CLI

```
[13:23:45 INF] ABP CLI (https://abp.io)
[13:23:45 INF] Version 5.2.1 (Stable)
[13:23:45 INF] Output folder: C:\Payoff\abp_source\Volo.Docs.Admin
[13:23:46 INF] Downloading source code of Volo.Docs.Admin
[13:23:46 INF] Version: Latest
[13:23:46 INF] Output folder: C:\Payoff\abp_source\Volo.Docs.Admin
[13:23:46 INF] Downloading module: Volo.Docs.Admin, version: 5.2.1
Error occured while downloading source-code from https://abp.io/api/download/module/ : StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Date: Wed, 04 May 2022 11:23:43 GMT
  Transfer-Encoding: chunked
  Connection: keep-alive
  Cache-Control: no-cache,no-store
  Pragma: no-cache
  Set-Cookie: .AspNetCore.Antiforgery.VyLW6ORzMgk=CfDJ8I5U7W_ULp9FkBu31d_z6adImQbWk9g-om2_toR4HZ9Cjuai04LnoiOy_ulNHnYift3NzbRfg02vTIw-iFr2BAS2HKYS7Fg5nNWaUPcP9_XM3panHPSJwDaiohEtpifKXm5MeVstbQbd-nIDUUzWfrE; path=/; samesite=strict; httponly
  Set-Cookie: XSRF-TOKEN=CfDJ8I5U7W_ULp9FkBu31d_z6aea28VHaQPznFEIc9_vRY6oh-NTlmgMKpfA9WJJnQ3YoabYohh43dueTJ7tyh18IZgaz3UXZ_5xZhnllPdM-aCCodz-cuKMOBCsNLJEuomtvqNSquB9fqarygK0lXhCOH32z3MjX7FpnIXhtQfRzlQ8j3eseEg3inRkCpLQkuVSAw; expires=Sat, 01 May 2032 11:23:43 GMT; path=/; secure; samesite=none
  Strict-Transport-Security: max-age=2592000
  X-Frame-Options: SAMEORIGIN
  X-Powered-By: ARR/3.0
  X-Powered-By: ASP.NET
  CF-Cache-Status: DYNAMIC
  Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
  Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=DDORFHrIFYtitESW6tQvbyXlOZ5FbRV2jX5uJOsWBgRb%2BQmpwzPKE5UogqJ2m1Vn6cvUTWvlNn9WFdTVzwkGNhuJf5%2BD%2BQmxwm4LoKY0A0NeBx6fjkafzQ%3D%3D"}],"group":"cf-nel","max_age":604800}
  NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
  Server: cloudflare
  CF-RAY: 7060ddacdf5e375b-MXP
  Content-Type: text/html; charset=utf-8
  Expires: -1
}
'<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
[13:23:46 ERR] '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Volo.Abp.Json.SystemTextJson.AbpSystemTextJsonSerializerProvider.Deserialize[T](String jsonString, Boolean camelCase) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Json\Volo\Abp\Json\SystemTextJson\AbpSystemTextJsonSerializerProvider.cs:line 35
   at Volo.Abp.Json.AbpHybridJsonSerializer.Deserialize[T](String jsonString, Boolean camelCase) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Json\Volo\Abp\Json\AbpHybridJsonSerializer.cs:line 37
   at Volo.Abp.Cli.ProjectBuilding.RemoteServiceExceptionHandler.GetAbpRemoteServiceErrorAsync(HttpResponseMessage responseMessage) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\RemoteServiceExceptionHandler.cs:line 52
   at Volo.Abp.Cli.ProjectBuilding.RemoteServiceExceptionHandler.EnsureSuccessfulHttpResponseAsync(HttpResponseMessage responseMessage) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\RemoteServiceExceptionHandler.cs:line 38
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.DownloadSourceCodeContentAsync(SourceCodeDownloadInputDto input) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 251
   at Volo.Abp.Cli.ProjectBuilding.AbpIoSourceCodeStore.GetAsync(String name, String type, String version, String templateSource, Boolean includePreReleases) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoSourceCodeStore.cs:line 119
   at Volo.Abp.Cli.ProjectBuilding.ModuleProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\ModuleProjectBuilder.cs:line 48
   at Volo.Abp.Cli.Commands.Services.SourceCodeDownloadService.DownloadModuleAsync(String moduleName, String outputFolder, String version, String gitHubAbpLocalRepositoryPath, String gitHubVoloLocalRepositoryPath, AbpCommandLineOptions options) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\Services\SourceCodeDownloadService.cs:line 40
   at Volo.Abp.Cli.Commands.GetSourceCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\GetSourceCommand.cs:line 64
   at Volo.Abp.Cli.CliService.RunInternalAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 161
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 69
```

**Comment by realLiangshiwei** [comment] 2022-05-04 11:56
Hi,

Try `abp get-source Volo.Docs` instead of `abp get-source Volo.Docs.Admin`

**Comment by sanghel-payoff** [comment] 2022-05-04 11:59
_Volo.Docs_ and _Volo.Docs.Admin_ are two **different** modules, as listed by the abp CLI

![image](https://user-images.githubusercontent.com/77339756/166677047-2b2d66e4-4978-4d7c-8125-d1d52e2c2e8c.png)

The get-source command fails for _Volo.Docs.Admin_ as detailed above

**Comment by realLiangshiwei** [comment] 2022-05-04 12:10
Hi,

Actually, they are the same module, it's wrong in the list.

**Comment by realLiangshiwei** [comment] 2022-05-04 12:11
Duplicate of https://github.com/abpframework/abp/issues/10974

**Closed as completed by realLiangshiwei** 2022-05-04 12:11 UTC
