### ISSUE TITLE
CMS Kit - Error while adding blogpost

### ISSUE THREAD

**Issue by enisn** [abpframework/abp#12007] opened 2022-03-18 07:49 UTC
Uncaught TypeError: Class constructor Dl cannot be invoked without 'new'

![image](https://user-images.githubusercontent.com/23705418/158958763-9174465f-4086-41f3-bf91-4793b8b8d74d.png)

**Comment by maliming** [comment] 2022-03-18 08:05
Duplicate of #11971

**Closed as completed by maliming** 2022-03-18 08:05 UTC
Labels: priority:high, abp-module-cms-kit
