### ISSUE TITLE
Add wwwroot/libs folder to .gitignore for templates

### ISSUE THREAD

**Issue by mtozlu** [abpframework/abp#8369] opened 2021-04-03 11:04 UTC
`wwwroot/libs` folder can be filled with gulp by running `yarn install && gulp` command so there is no need to include them in git.
This reduces initial tracked git file count from 455 to 113 in new apps that are generated from templates.

**Comment by maliming** [comment] 2021-04-12 09:15
Duplicate of https://github.com/abpframework/abp/issues/8528

**Closed as completed by maliming** 2021-04-12 09:15 UTC
