### ISSUE TITLE
CLI: Failure when receiving data from the peer

### ISSUE THREAD

**Issue by epgeroy** [abpframework/abp#1447] opened 2019-07-07 01:27 UTC
Hi, I'm having some issues creating a new project using the CLI
sometimes I got
```
> abp new Test
[20:22:45 INF] ABP CLI (https://abp.io)
[20:22:45 INF] Version 0.18.1 (Stable channel)
[20:22:46 WRN] Unable to retrieve the latest version
[20:22:46 WRN] Remote server returns error! HTTP status code: Forbidden
[20:22:48 INF] Creating a new project...
[20:22:48 INF] Project name: Test
[20:22:49 INF] Downloading template: mvc, version: 0.18.1
[20:22:59 ERR] Error while copying content to a stream.
System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: The read operation failed, see inner exception. ---> System.Net.Http.CurlException: Failure when receiving data from the peer
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.NoWriteNoSeekStreamContent.<>c.<SerializeToStreamAsync>b__4_0(Task t, Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Volo.Abp.Cli.ProjectBuilding.AbpIoTemplateStore.DownloadTemplateFileContentAsync(TemplateDownloadInputDto input) in D:\github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoTemplateStore.cs:line 110
   at Volo.Abp.Cli.ProjectBuilding.AbpIoTemplateStore.GetAsync(String name, DatabaseProvider databaseProvider, String projectName, String version) in D:\github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoTemplateStore.cs:line 63
   at Volo.Abp.Cli.ProjectBuilding.ProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\ProjectBuilder.cs:line 39
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 39
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 56

```
and sometimes
```
> abp new Test

[20:18:26 INF] ABP CLI (https://abp.io)
[20:18:26 INF] Version 0.18.1 (Stable channel)
[20:18:27 WRN] Unable to retrieve the latest version
[20:18:27 WRN] Remote server returns error! HTTP status code: Forbidden
[20:18:28 INF] Creating a new project...
[20:18:28 INF] Project name: Test
[20:18:30 INF] Downloading template: mvc, version: 0.18.1
[20:19:00 ERR] A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.NoWriteNoSeekStreamContent.<>c.<SerializeToStreamAsync>b__4_0(Task t, Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Volo.Abp.Cli.ProjectBuilding.AbpIoTemplateStore.DownloadTemplateFileContentAsync(TemplateDownloadInputDto input) in D:\github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoTemplateStore.cs:line 110
   at Volo.Abp.Cli.ProjectBuilding.AbpIoTemplateStore.GetAsync(String name, DatabaseProvider databaseProvider, String projectName, String version) in D:\github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\AbpIoTemplateStore.cs:line 63
   at Volo.Abp.Cli.ProjectBuilding.ProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\ProjectBuilder.cs:line 39
   at Volo.Abp.Cli.Commands.NewCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\NewCommand.cs:line 39
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\github\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 56
```
Never been able to run the CLI correctly

`dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.105
 Commit:    7cecb35b92

Runtime Environment:
 OS Name:     manjaro
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /opt/dotnet/sdk/2.2.105/

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

.NET Core SDKs installed:
  2.2.105 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.2.3 [/opt/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

thxs in advance

**Comment by liangshiw** [comment] 2019-07-08 00:10
Related to the network environment, maybe you can use the proxy

**Comment by epgeroy** [comment] 2019-07-08 00:21
Thxs, is this proxy somewhere documented?
 I'm not usign proxies or any special network configuration. 

Thxs in avance.

**Comment by maliming** [comment] 2019-07-08 00:48
The server for abp.io is located in Turkey. Connection speeds may be slow in some countries or regions. You can try downloading it from the https://abp.io website.

**Comment by xyfy** [comment] 2019-08-09 07:30
@epgeroy you can buy a proxy, or just buy a cloud server or vpn
I just want to know where the cli commnad to download,and can it been
Duplicate of #1608

**Comment by maliming** [comment] 2019-08-09 07:33
> I just want to know where the cli commnad to download

https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/CliUrls.cs
https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Cli.Core/Volo/Abp/Cli/ProjectBuilding/AbpIoTemplateStore.cs#L106

**Closed by maliming** 2019-08-09 07:33 UTC

**Comment by xyfy** [comment] 2019-08-09 07:41
Can the cli command be excuted offline.
why you do not release it locally?

**Comment by maliming** [comment] 2019-08-09 07:44
When you successfully download a version, cli will cache the downloaded template.

![image](https://user-images.githubusercontent.com/6908465/62762814-9355c300-babc-11e9-9f9d-24e3c6a725fd.png)

**Comment by epgeroy** [comment] 2019-08-09 17:20
Can I do something to improve connectivity in this region (North America and Caribbean), many people from Mexico and Cuba use volosoft tech and documentation, lately the docs has been giving timeouts  from your websites @hikalkan

**Comment by hikalkan** [comment] 2019-08-11 17:16
Thanks @epgeroy for informing this. We will increase CDN usage which my help. We will also try to check speed from various regions. I have taken note for it. Thanks.
BTW, when you have problem to read docs, use https://github.com/abpframework/abp/tree/dev/docs/en as a workaround :)

**Comment by wocar** [comment] 2019-09-23 09:03
> When you successfully download a version, cli will cache the downloaded template.

What is the direct link to download the module.zip?

**Comment by hikalkan** [comment] 2019-09-25 18:55
>What is the direct link to download the module.zip?

Close https://github.com/abpframework/abp repository, zip the https://github.com/abpframework/abp/tree/dev/templates/module folder. It simply works like that.
