### ISSUE TITLE
CMS Kit / Blogging: Convert "Blog" textbox to dropdown

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/abp#19333] opened 2024-03-17 20:09 UTC
Convert "Blog" textbox -> dropdown.
![image](https://github.com/abpframework/abp/assets/9526587/c794a733-23df-47d6-b965-1e0422bb9dd8)

- [x] Blazor: @realLiangshiwei 
- [ ] MVC: @EngincanV 

> Reported at https://support.abp.io/QA/Questions/6260/Bugs--Issues-v80x?CurrentPage=4#answer-3a1159d4-eec4-6e17-5e18-289c1b382cc3

**Comment by Sinan997** [comment] 2024-03-17 20:18
There is no CMS kit module in angular

**Comment by EngincanV** [comment] 2024-03-18 05:55
Currently, we use an autocomplete component on this page for the blog input (in MVC):

![image](https://github.com/abpframework/abp/assets/43685404/9d0aad13-a98f-4014-98b3-1dc23091353e)

~~I have written to the customer. I think we don't need to make any changes here but I'll wait for an answer from the customer to close this issue.~~

It seems the problem is in the Blazor UI: https://support.abp.io/qa/questions/6260/3a1162aa-87e6-7d02-2a4e-3c039761d84b

**Comment by enisn** [comment] 2024-03-18 06:58
It's already dropdown with Select2

**Comment by enisn** [comment] 2024-03-18 06:59
It's kind of dropdown on MVC with select2.

> Currently, we use an autocomplete component on this page for the blog input:
> 
> ![image](https://private-user-images.githubusercontent.com/43685404/313563808-9d0aad13-a98f-4014-98b3-1dc23091353e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDU0MDgsIm5iZiI6MTcxMDc0NTEwOCwicGF0aCI6Ii80MzY4NTQwNC8zMTM1NjM4MDgtOWQwYWFkMTMtYTk4Zi00MDE0LTk4YjMtMWRjMjMwOTEzNTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA2NTgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxNTg5NjYxN2U5ODU2NThmMTNiZjViYjE1NTNkNzgzNmRkY2UyNDI3NWJmN2RjMDkxZTg4ZjQ5MGYxYTQ5NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pzfvDGpc-pWjKLoJQP6BACtGl3dIcjbozqyhxmHLySw)
> 
> I have written to the customer. I think we don't need to make any changes here but I'll wait for an answer from the customer to close this issue.

Maybe we can make the threshold as 0 to show everything on the first click.

**Comment by sturlath** [comment] 2024-05-01 08:05
Is there no way to get this small thing into 8.2? 🙏

**Comment by realLiangshiwei** [comment] 2024-07-22 02:19
> Maybe we can make the threshold as 0 to show everything on the first click.

MVC is already like this and doesn't need to change, so I'm closing this issue.
<img width="965" alt="image" src="https://github.com/user-attachments/assets/10474212-2981-4d7a-9fbb-32cf5e5c8dc9">

**Closed as completed by realLiangshiwei** 2024-07-22 02:19 UTC
Labels: enhancement, abp-module-blogging, effort-xs

**Comment by sturlath** [comment] 2024-07-24 12:51
But you are going to fix it in Blazor, correct? @realLiangshiwei Just want to be sure...

**Comment by realLiangshiwei** [comment] 2024-07-24 12:52
> But you are going to fix it in Blazor, correct? @realLiangshiwei Just want to be sure...

yes
