### ISSUE TITLE
Problem with docs

### ISSUE THREAD

**Issue by michalstepien** [abpframework/abp#814] opened 2019-02-17 10:41 UTC
Hi, I have problem with open docs on yours site:

https://abp.io/documents/abp/latest/Index
502 - Web server received an invalid response while acting as a gateway or proxy server.
There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.

**Comment by hikalkan** [comment] 2019-02-17 11:40
It is now fixed with an application pool restart :). However, we had this problem before and should investigate the root cause.

**Comment by hikalkan** [comment] 2019-02-21 13:40
I'm closing this since it has been fixed for abp.io web site. However, I created a related issue: https://github.com/abpframework/abp/issues/836

**Closed by hikalkan** 2019-02-21 13:40 UTC
Labels: abp_io, problem
