### ISSUE TITLE
MySql BLOB/TEXT column 'Value' used in key specification without a key length

### ISSUE THREAD

**Issue by sdjnzjz** [abpframework/abp#2077] opened 2019-11-05 02:40 UTC
IdentityServerApiSecrets Value

**Comment by sdjnzjz** [comment] 2019-11-05 02:41
![TIM图片20191105103848](https://user-images.githubusercontent.com/5534101/68174350-c4a93680-ffb8-11e9-8f66-80a01714c3c3.png)

**Comment by maliming** [comment] 2019-11-05 02:43
Duplicate of https://github.com/abpframework/abp/issues/1920#issuecomment-543551659 https://github.com/abpframework/abp/issues/2053#issuecomment-548626182

**Closed by maliming** 2019-11-05 02:43 UTC

**Comment by sdjnzjz** [comment] 2019-11-05 03:24
thanks !!
