### ISSUE TITLE
Tenant Auth not working on Blazor wasm using both CLI and direct download.

### ISSUE THREAD

**Issue by StlobyAdmin** [abpframework/abp#13574] opened 2022-08-05 03:42 UTC
The standard project blazor wasm template is not authenticating tenants. I am getting an error "There was an error trying to log you in." with 401 "Invalid_token". 

I also realised that the LeptonX Lite Blazor wasm UI template vs LeptonX Lite Blazor server UI  seems different.  The language and login name are swapped around, perhaps we are scaffolding to different templates. I tested the blazor server, it is working.

* **ABP Framework version** 6.0.0-rc.1.
* **User Interface** type Blazor Web Assembly
* Database provider EFCore Postgres
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem - create standard blazor template, create tenant and try to login using tenant.

**Comment by maliming** [comment] 2022-08-05 04:14
I can't reproduce.

**Comment by StlobyAdmin** [comment] 2022-08-05 05:35
I just used getting started via https://abp.io/get-started to create WASM, logged in via admin account, created tenant A, but tenant A cannot log in. See the flow in pic below...

![image](https://user-images.githubusercontent.com/12781809/183008350-7217822a-0416-43d8-8f4b-22248ccf073d.png)

![image](https://user-images.githubusercontent.com/12781809/183008387-51f0f202-9841-4a44-9ac4-c595bed75c5c.png)


![image](https://user-images.githubusercontent.com/12781809/183008393-5e117323-24f6-499c-b34a-28898dee654a.png)

![image](https://user-images.githubusercontent.com/12781809/183008410-f10fd360-3e62-4dc5-bae3-e1f7d24ca85d.png)

![image](https://user-images.githubusercontent.com/12781809/183008421-41d0d363-d97b-4eb2-a2d9-ca0612d90039.png)

![image](https://user-images.githubusercontent.com/12781809/183008426-9c6cf93d-4a86-46de-a3da-29cc170ceb5d.png)

![image](https://user-images.githubusercontent.com/12781809/183008485-8eb32481-e2d8-4222-b536-ec929c5dbfcb.png)

![image](https://user-images.githubusercontent.com/12781809/183008506-0b73e904-f5f4-4bcd-9986-37350e7dd569.png)

![image](https://user-images.githubusercontent.com/12781809/183008540-13c60d5f-9689-4f71-b46a-488af6b82b62.png)

**Comment by maliming** [comment] 2022-08-05 06:17
hi

This issue will be fixed in RC2. https://github.com/abpframework/abp/pull/13435

**Closed as completed by maliming** 2022-08-05 06:17 UTC
