### ISSUE TITLE
MVC UI (Tiered): Login button on top navigation bar

### ISSUE THREAD

**Issue by yekalkan** [abpframework/abp#5829] opened 2020-10-16 08:40 UTC
![image](https://user-images.githubusercontent.com/5793291/96236098-431d9f00-0fa4-11eb-81b1-ba01ca12357a.png)

**Comment by hikalkan** [comment] 2020-10-18 12:31
duplicate of https://github.com/volosoft/volo/issues/3579

**Closed as completed by hikalkan** 2020-10-18 12:31 UTC
Labels: duplicate
