### ISSUE TITLE
Can not debug with source link.Do i need to add external symbol server？

### ISSUE THREAD

**Issue by CAH-FlyChen** [abpframework/abp#2137] opened 2019-11-10 12:18 UTC
![image](https://user-images.githubusercontent.com/1214546/68543814-f118e480-03f6-11ea-8e01-8a3f542a4c24.png)
![image](https://user-images.githubusercontent.com/1214546/68544128-d8123280-03fa-11ea-9e53-1d6bfb4cb22e.png)

Part of the log shows that microsoft dll symbol can be loaded .but abp can't.
===========================================
'Zion.AFW.Web.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.0.0\Microsoft.Extensions.Localization.dll'. **Symbols loaded.**
'Zion.AFW.Web.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.0.0\Microsoft.Extensions.Localization.Abstractions.dll'. **Symbols loaded.**
'D:\Code\MyProject\zion\src\Zion.AFW.Web\bin\Debug\netcoreapp3.0\Volo.Abp.Identity.Web.dll'. 
'Zion.AFW.Web.exe' (CoreCLR: clrhost): **Loaded** 'D:\Code\MyProject\zion\src\Zion.AFW.Web\bin\Debug\netcoreapp3.0\Volo.Abp.Account.Web.IdentityServer.dll'. 
'Zion.AFW.Web.exe' (CoreCLR: clrhost): Loaded 'D:\Code\MyProject\zion\src\Zion.AFW.Web\bin\Debug\netcoreapp3.0\Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic.dll'. 
'Zion.AFW.Web.exe' (CoreCLR: clrhost): Loaded 'D:\Code\MyProject\zion\src\Zion.AFW.Web\bin\Debug\netcoreapp3.0\Volo.Abp.AspNetCore.Authentication.JwtBearer.dll'. 
'Zion.AFW.Web.exe' (CoreCLR: clrhost): Loaded 'D:\Code\MyProject\zion\src\Zion.AFW.Web\bin\Debug\netcoreapp3.0\Volo.Abp.TenantManagement.Web.dll'. 
'Zion.AFW.Web.exe' (CoreCLR: clrhost): Loaded 'D:\Code\MyProject\zion\src\Zion.AFW.Web\bin\Debug\netcoreapp3.0\Zion.AFW.Application.Contracts.dll'. Symbols loaded.
'Zion.AFW.Web.exe' (CoreCLR: clrhost): Loaded 'D:\Code\MyProject\zion\src\Zion.AFW.Web\bin\Debug\netcoreapp3.0\Volo.Abp.Account.HttpApi.dll'. 
'Zion.AFW.Web.exe' (CoreCLR: clrhost): Loaded 'D:\Code\MyProject\zion\src\Zion.AFW.Web\bin\Debug\netcoreapp3.0\Volo.Abp.Identity.HttpApi.dll'. 
'Zion.AFW.Web.exe' (CoreCLR: clrhost): Loaded 'D:\Code\MyProject\zion\src\Zion.AFW.Web\bin\Debug\netcoreapp3.0\Volo.Abp.PermissionManagement.HttpApi.dll'. 
'Zion.AFW.Web.exe' (CoreCLR: clrhost): Loaded 'D:\Code\MyProject\zion\src\Zion.AFW.Web\bin\Debug\netcoreapp3.0\Volo.Abp.TenantManagement.HttpApi.dll'. 
'Zion.AFW.Web.exe' (CoreCLR: clrhost): Loaded 'D:\Code\MyProject\zion\src\Zion.AFW.Web\bin\Debug\netcoreapp3.0\Volo.Abp.FeatureManagement.HttpApi.dll'. 
'Zion.AFW.Web.exe' (CoreCLR: clrhost): Loaded 'D:\Code\MyProject\zion\src\Zion.AFW.Web\bin\Debug\netcoreapp3.0\Zion.AFW.Domain.Shared.dll'. Symbols loaded.
'Zion.AFW.Web.exe' (CoreCLR: clrhost): Loaded 'D:\Code\MyProject\zion\src\Zion.AFW.Web\bin\Debug\netcoreapp3.0\Volo.Abp.Account.Application.Contracts.dll'. 

![image](https://user-images.githubusercontent.com/1214546/68543875-d5faa480-03f7-11ea-85fd-aaa028625e14.png)

![image](https://user-images.githubusercontent.com/1214546/68543898-093d3380-03f8-11ea-8017-15687f93fa01.png)
![image](https://user-images.githubusercontent.com/1214546/68543906-2b36b600-03f8-11ea-8167-852d45284f2e.png)

but command shows correct..
![image](https://user-images.githubusercontent.com/1214546/68544597-dac35680-03ff-11ea-81a9-a17369cebd0b.png)

may be the issue. https://github.com/dotnet/core/issues/3587

**Comment by flomader** [comment] 2020-06-19 15:17
I think Source Link doen not work because the repository metadata does not have a commit identifier: 
![image](https://user-images.githubusercontent.com/40666690/85148693-b90d3600-b250-11ea-991c-81cc40d0591e.png)
This is required as described here: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink#using-source-link

**Comment by maliming** [comment] 2020-06-22 01:01
Duplicate of #3462

**Closed by maliming** 2020-06-22 01:01 UTC
Labels: question
