### ISSUE TITLE
How to reset or update tenant admin password ?

### ISSUE THREAD

**Issue by wjkhappy14** [abpframework/abp#4191] opened 2020-06-03 03:22 UTC
Can't find any way to resest tenant **admin** password !

**Comment by liangshiw** [comment] 2020-06-03 03:46
Duplicate of https://github.com/abpframework/abp/issues/2608

**Closed by liangshiw** 2020-06-03 03:46 UTC
Labels: duplicate

**Comment by olicooper** [comment] 2020-06-03 09:10
Abp uses [IdentityUserManager](https://github.com/abpframework/abp/blob/dev/modules/identity/src/Volo.Abp.Identity.Domain/Volo/Abp/Identity/IdentityUserManager.cs) which implements Microsoft's [UserManager](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.usermanager-1?view=aspnetcore-3.1) e.g.:

```csharp
(await _userManager.ResetPasswordAsync(user, resetTokenString, input.NewPassword)).CheckErrors();
```

Also, although this might not help you with updating the password, when creating new tenants you can pass the admin email and password through with the `IDataSeeder` like:
```csharp
await DataSeeder.SeedAsync(new DataSeedContext(tenant.Id)
    .WithProperty("AdminEmail", "e@mail")
    .WithProperty("AdminPassword", "password"));
```
