### ISSUE TITLE
input type="date" changed to type="text"

### ISSUE THREAD

**Issue by juchunwei** [abpframework/abp#7571] opened 2021-02-02 10:12 UTC
Hello,

I'm using abp4.2 MVC Razor template.  I setup the input element  with type="date", but I changed to type="text" when I run the page. Why like this? how can I avoid this?

Thanks!

**Comment by maliming** [comment] 2021-02-02 10:39
* Steps needed to **reproduce** the problem.

**Comment by juchunwei** [comment] 2021-02-02 10:48
@maliming , 
Here're the code in the page. When I open the page, the input changed to` <input type="text" class="form-control">` and seems it's using the datepickier.

`<abp-card>`    
    `<abp-card-body> `      
        `<form method="post">`
           `<input type="date" class="form-control" />           `
       ` </form>`
   ` </abp-card-body>`
`</abp-card>`

**Comment by juchunwei** [comment] 2021-02-02 10:50
@maliming 
Sorry, the code disappeared.
Here're the code
<abp-card>    
    <abp-card-body>
        <input type="date" class="form-control" />
       
    </abp-card-body>
</abp-card>

**Comment by juchunwei** [comment] 2021-02-02 10:51
`<abp-card>`
   `<abp-card-body>`  
        `<input type="date" class="form-control" />`      
   ` </abp-card-body>`
`</abp-card>`

**Comment by yekalkan** [comment] 2021-02-02 11:08
@juchunwei 

https://github.com/abpframework/abp/issues/7196#issuecomment-764541352 may this help you?

**Comment by juchunwei** [comment] 2021-02-02 11:13
@yekalkan 
that doesn't work either, that's what I tried the first time, it's changed to type="text", then I tried to use the input element directly without the abp-input, and get the same result.  the code changed to `<input type="text" class="form-control">`

**Comment by yekalkan** [comment] 2021-02-02 11:15
As you said, this is not a behaviour of Abp Framework.

**Comment by juchunwei** [comment] 2021-02-02 11:26
@yekalkan 
Not sure what's wrong. But I tried to use `<input type="date" class="form-control"/>` without abp, it works. not changed to type="text"

**Comment by yekalkan** [comment] 2021-02-02 11:47
AspNet Core Input tag helper converts it to `text`. Therefore `abp-input` converts as well.

**Comment by juchunwei** [comment] 2021-02-02 11:57
@yekalkan 

I just created a complete new project with the standard Microsoft template. here're the code, and no problems.

` public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }
        public void OnGet()
        {

        }

        [BindProperty]
        public TestModel MyModel { get; set; } = new TestModel();
       
        public class TestModel
        {
            [DataType(DataType.Date)]
            public DateTime Date { get; set; }
        }
    }`

`<div class="text-center">`
    `<div style="width:300px">`
        `<input type="date" class="form-control" />`
       ` <input class="form-control" asp-for="MyModel.Date" />`
    `</div>`
`</div>`

**Comment by yekalkan** [comment] 2021-02-02 12:17
As i tested: If you remove `[DataType(DataType.Date)]` `type` is not changed to `text`.

I'm closing this issue since it is not related to ABP Framework.

**Closed as completed** 2021-02-02 18:53 UTC
