### ISSUE TITLE
Single json file for each language?

### ISSUE THREAD

**Issue by KevinFarrow** [abpframework/abp#2005] opened 2019-10-24 19:31 UTC
In Zero we have one file for each language that we can easily export and have someone translate it for us. Now it looks there are so many (in different modules) that it's hard to ensure duplication doesn't creep in. Is it possible to have a single entry point with one file for each language?

When adding a new module the system could check each string and merge the data?

**Comment by maliming** [comment] 2019-10-25 01:10
Each module has its own localized resources, which is fine. The localization system supports Inherit and extends other localized resources (including localized resources in the module).

https://docs.abp.io/en/abp/latest/Localization

**Comment by KevinFarrow** [comment] 2019-10-28 09:05
@maliming Unfortunately that's not fine, it is a backward step. I need to be able to send a complete single file for translation just like we do in Zero. Best practises (DRY) suggest we don't repeat ourselves but the way it is implemented in abp.io goes against this.

**Comment by maliming** [comment] 2019-10-31 01:26
Yes, for example, someone developed a new module, the module contains some language translation, may not have the language you want to use, or you think his translation needs improvement.

The framework allows you to add new language translations or modify existing translations. This is enough. You know, for modularity.

**Comment by hikalkan** [comment] 2019-11-01 09:02
I am closing this since this is a result of the modularity, and it is by design.
@KevinFarrow if you want, you can copy all texts to your json file, from modules you are using (while I definitely don't suggest it).

**Closed by hikalkan** 2019-11-01 09:02 UTC
Labels: question
