### ISSUE TITLE
The Future of IdentityServer

### ISSUE THREAD

**Issue by jogoertzen-stantec** [abpframework/abp#6298] opened 2020-11-20 18:29 UTC
As indicated in https://github.com/dotnet/aspnetcore/issues/26489, Identity Server 4 will lose support in November 2022 (.NET Core 3.1 EOL).

Is ABP Framework planning on switching to another free and open source identity management project, or is the plan to stick with Identity Server?

**Comment by realLiangshiwei** [comment] 2020-11-21 09:30
Duplicate of https://github.com/abpframework/abp/issues/5735

**Closed as completed by realLiangshiwei** 2020-11-21 09:30 UTC
