### ISSUE TITLE
[Commercial] LeptonX - No option to change Tenant on Login Page

### ISSUE THREAD

**Issue by hellorms** [abpframework/abp#12655] opened 2022-05-18 21:37 UTC
5.2.2 / MVC / EF Core

Installed LeptonX using version 5.2.2 recommended by @enisn and looks excellent. I added a new Tenant and logout but there is nowhere to change Tenant on login page - also there is nowhere to change language on login page

![2022-05-18_22-28-53](https://user-images.githubusercontent.com/93287086/169159416-4346f60a-801a-4bb1-93c2-e5c2cc3df62c.jpg)

**Note:  MultiTenancyConsts.IsEnabled = true;**

**Comment by ismcagdas** [comment] 2022-06-23 07:33
Duplicate of https://github.com/abpframework/abp/issues/13022

**Closed as completed by ismcagdas** 2022-06-23 07:33 UTC
