### ISSUE TITLE
Quartz integration got System.MissingMethodException: Method not found: 'Void Quartz.IPropertyConfigurer.SetProperty(System.String, System.String)

### ISSUE THREAD

**Issue by Laff80** [abpframework/abp#6794] opened 2020-12-24 06:37 UTC
Volo.Abp.AbpInitializationException: An error occurred during ConfigureServices phase of the module Volo.Abp.Quartz.AbpQuartzModule, Volo.Abp.Quartz, Version=4.0.2.0, Culture=neutral, PublicKeyToken=null. See the inner exception for details.
 ---> System.MissingMethodException: Method not found: 'Void Quartz.IPropertyConfigurer.SetProperty(System.String, System.String)'.
   at Quartz.TimeZonePluginConfigurationExtensions.UseTimeZoneConverter[T](T schedulerBuilder)
   at Volo.Abp.Quartz.AbpQuartzModule.<>c__DisplayClass1_0.<ConfigureServices>b__0(IServiceCollectionQuartzConfigurator build)
   at Quartz.ServiceCollectionExtensions.AddQuartz(IServiceCollection services, NameValueCollection properties, Action`1 configure)
   at Volo.Abp.Quartz.AbpQuartzModule.ConfigureServices(ServiceConfigurationContext context)
   at Volo.Abp.AbpApplicationBase.ConfigureServices()
   --- End of inner exception stack trace ---
   at Volo.Abp.AbpApplicationBase.ConfigureServices()
   at Volo.Abp.AbpApplicationBase..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationWithExternalServiceProvider..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.Create(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.Create[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionApplicationExtensions.AddApplication[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Laff.BackgroundDemo.Web.Startup.ConfigureServices(IServiceCollection services) in G:\example\AbpVnext\4.0\src\Laff.BackgroundDemo.Web\Startup.cs:line 10
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()

**Comment by realLiangshiwei** [comment] 2020-12-24 06:47
* Steps needed to **reproduce** the problem.

**Comment by Laff80** [comment] 2020-12-26 10:42
I integrate according to the official documentation
**1、** Add the Volo.Abp.BackgroundWorkers.Quartz NuGet package to the .Application project.
**2、** Add the AbpBackgroundWorkersQuartzModule ：
   `[DependsOn(
        typeof(BackgroundDemoDomainModule),
        typeof(AbpAccountApplicationModule),
        typeof(BackgroundDemoApplicationContractsModule),
        typeof(AbpIdentityApplicationModule),
        typeof(AbpPermissionManagementApplicationModule),
        typeof(AbpTenantManagementApplicationModule),
        typeof(AbpFeatureManagementApplicationModule)
        )]
    [DependsOn(typeof(AbpBackgroundWorkersQuartzModule))]
    public class BackgroundDemoApplicationModule : AbpModule
    {
        public override void PreConfigureServices(ServiceConfigurationContext context)
        {
            var configuration = context.Services.GetConfiguration();

            PreConfigure<AbpQuartzOptions>(options =>
            {
                options.Properties = new NameValueCollection
                {
                    ["quartz.jobStore.dataSource"] = "BackgroundJobsDemoApp",
                    ["quartz.jobStore.type"] = "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz",
                    ["quartz.jobStore.tablePrefix"] = "QRTZ_",
                    ["quartz.serializer.type"] = "json",
                    ["quartz.dataSource.BackgroundJobsDemoApp.connectionString"] = configuration.GetConnectionString("Default"),
                    ["quartz.dataSource.BackgroundJobsDemoApp.provider"] = "SqlServer",
                    ["quartz.jobStore.driverDelegateType"] = "Quartz.Impl.AdoJobStore.SqlServerDelegate, Quartz",
                };
            });
        }
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            Configure<AbpAutoMapperOptions>(options =>
            {
                options.AddMaps<BackgroundDemoApplicationModule>();
            });
        }
    }`
**3、** Create a Background Worker ：
`public  class MyTestBackgroundWorder: QuartzBackgroundWorkerBase
    {
        public MyTestBackgroundWorder()
        {
            JobDetail = JobBuilder.Create<MyTestBackgroundWorder>().WithIdentity(nameof(MyTestBackgroundWorder)).Build();
            Trigger = TriggerBuilder.Create().WithIdentity(nameof(MyTestBackgroundWorder)).StartNow().Build();
        }

        public override Task Execute(IJobExecutionContext context)
        {
            Logger.LogInformation("Executed MyLogWorker..!");
            return Task.CompletedTask;
        }
    }`
**4、** Add the Quartz.Serialization.Json package

**Comment by maliming** [comment] 2020-12-27 07:08
Duplicate of #6542

**Closed as completed by maliming** 2020-12-27 07:08 UTC
