### ISSUE TITLE
Abp generate-Proxy

### ISSUE THREAD

**Issue by awahbahplana** [abpframework/abp#11075] opened 2021-12-26 15:02 UTC
When i try to generate proxy via cli i get 
`"SchematicsAbpGenerateProxy" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.`
and when using abp suite it generating with out any problem

i search alot but i do not find any solution

after i get above message the API hanging and don't response until i re run the api again.
thanks

**Comment by realLiangshiwei** [comment] 2021-12-27 01:15
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Steps needed to **reproduce** the problem.

**Comment by yinchang0626** [comment] 2021-12-27 03:24
@realLiangshiwei 
version: `dev branch`

@mehmet-erim 
It's about angular schematics
We should modify property name `id` to `$id` in such as those code [schematics](https://github.com/abpframework/abp/blob/dev/npm/ng-packs/packages/schematics/src/commands/proxy-add/schema.json)

**Comment by awahbahplana** [comment] 2021-12-27 05:26
Dear Thank you,
I have proplem on application` v 4.4.4`
UI Angular 
DB `Oracle`
This Problem I faced on this app onley i create another one v` 5.0.0` it is worked an generating Proxy with same warning
`"SchematicsAbpGenerateProxy" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.`

the proxy is generated from abp suite if i change the entity, but if i add new apis to controller i cant update proxy manually.

thanks

**Comment by awahbahplana** [comment] 2021-12-27 06:11
I have a question for `abp generate-proxy`

how to determine my module name exactly i think it solve the problem 
eg.: 
I have name space Requestes i create entity in it RequestFlow so how can i tell the `abp generate-proxy -m ????`

thanks

**Comment by awahbahplana** [comment] 2021-12-27 06:53
The Problem is from Elsa Integration and i think from versioning in Url i remove elsa and every thing are working
do you have any advice?

**Comment by mehmet-erim** [comment] 2022-01-21 11:43
I assume that the problem is resolved in v5.1.2. I'm closing this one. If you encounter any errors, feel free to create a new issue.

**Closed as completed by mehmet-erim** 2022-01-21 11:43 UTC
