### ISSUE TITLE
Navigation Properties - Related data not being loaded with eager loading

### ISSUE THREAD

**Issue by Znow** [abpframework/abp#3007] opened 2020-03-06 10:56 UTC
Heya,

I have the following structure:

DashboardCategories 
1..N 
Dashboards

1 DashboardCategory can have N Dashboards

Below is code samples of a pretty basic setup of entities, the db builder, and an app service that retrieves "DashboardCategories". I have tried searching through issues for similar, and also on StackOverflow.

DashboardCategory.cs
```
public class DashboardCategory : AuditedAggregateRoot<Guid>, IMultiTenant
    {
        public string Name { get; set; }
        public int Priority { get; set; }
        public List<Dashboard> Dashboards { get; set; }

        public Guid? TenantId { get; set; }

        protected DashboardCategory()
        {

        }

        public DashboardCategory(Guid id)
         : base(id)
        {

        }
    }
```

Dashboard.cs
```
public class Dashboard : AuditedAggregateRoot<Guid>, IMultiTenant
    {


        public DashboardCategory DashboardCategory { get; set; }
        public Guid? DashboardCategoryId { get; set; }

        public Guid? TenantId { get; set; }

        protected Dashboard()
        {

        }

        public Dashboard(Guid id)
         : base(id)
        {

        }
    }
```

DTO's are similar, and mapped together with entities in Application project

```
builder.Entity<DashboardCategory>(b =>
            {
                b.ToTable(XConsts.DbTablePrefix + "DashboardCategories", XConsts.DbSchema);
                b.ConfigureByConvention();
                b.Property(x => x.Name).IsRequired().HasMaxLength(128);
                b.HasMany(x => x.Dashboards).WithOne(x => x.DashboardCategory).HasForeignKey(x => x.DashboardCategoryId);
            });

            builder.Entity<Dashboard>(b =>
            {
                b.ToTable(XConsts.DbTablePrefix + "Dashboards", XConsts.DbSchema);
                b.ConfigureByConvention();
                b.Property(x => x.Name).IsRequired().HasMaxLength(128);
                b.Property(x => x.ADGroupId).IsRequired();
                b.HasOne(x => x.ADGroup);
                b.HasOne(x => x.DashboardCategory).WithMany(x => x.Dashboards).HasForeignKey(c => c.DashboardCategoryId);
            });
```

Sample code
```
var dashboardCategories = await _dashboardCategoryAppService.GetListAsync(new PagedAndSortedResultRequestDto());

            if (dashboardCategories.Items.Any())
            {
                foreach (var dashboardCategory in dashboardCategories.Items.OrderBy(x => x.Priority))
                {
                    sideMenuDashboardCategories.AddItem(
                        new ApplicationMenuItem(dashboardCategory.Name, dashboardCategory.Name, $"/DashboardCategories/Details/{dashboardCategory.Id}")
                    );
                }
            }
```

![image](https://user-images.githubusercontent.com/265719/76077581-4332d680-5fa1-11ea-997d-0c65c59f6b56.png)

DB:
![image](https://user-images.githubusercontent.com/265719/76077606-504fc580-5fa1-11ea-8b17-9ab75535a80c.png)

Thanks in advance,
Regards

**Comment by yinchang0626** [comment] 2020-03-06 12:14
@Znow 
maybe you should do it in your repository like
``csharp
public override IQueryable<IdentityUser> WithDetails()
{
    return GetQueryable()
        .Include(x => x.Roles)
        .Include(x => x.Logins)
        .Include(x => x.Claims)
        .Include(x => x.Tokens); // Uses the extension method defined above
}
```
pls ref this article
https://github.com/abpframework/abp/blob/dev/docs/en/Best-Practices/Entity-Framework-Core-Integration.md

**Comment by Znow** [comment] 2020-03-06 12:17
@yinchang0626 - Seems very weird, since I don't have custom repositories for my entities, but relying on the generic repository implementation: IRepository<SomeEntity>

**Comment by yinchang0626** [comment] 2020-03-06 12:25
@Znow 
maybe it can help you,but I think create a custom repository for `AggregateRoot` entity is better.
```csharp
    public class MyEntityFrameworkCoreModule : AbpModule
    {
        public override void ConfigureServices(ServiceConfigurationContext context)
        {
            context.Services.AddAbpDbContext<WmsDbContext>(options =>
            {
                options.Entity<DashboardCategory>(opt => opt.DefaultWithDetailsFunc = q => q.Include(m => m.Dashboards ));
                /* Add custom repositories here. Example:
                 * options.AddRepository<Question, EfCoreQuestionRepository>();
                 */
            });
        }
    }
```

**Comment by Znow** [comment] 2020-03-09 08:40
@yinchang0626 THen I would have to create a custom repository for every entity that has relations and navigation property? Not a suitable solution tbh... If it works out of the box in EF Core, then it should also work out of the box in ABP

**Comment by acjh** [comment] 2020-03-09 13:58
> Then I would have to create a custom repository for every entity that has relations and navigation property? Not a suitable solution tbh...

You don't have to.

> If it works out of the box in EF Core, then it should also work out of the box in ABP

EF Core does not eager load (nor lazy load) by default.
https://docs.microsoft.com/en-us/ef/core/querying/related-data

**Comment by Znow** [comment] 2020-03-09 14:07
@acjh Okay, your answer doesn't provide me with much more solution, sorry.

I have looked through that site, many times - without any luck.

**Comment by acjh** [comment] 2020-03-09 14:10
There is no luck involved. You have to configure it as you require.

**Comment by Znow** [comment] 2020-03-09 14:12
@acjh I dont understand your point? Where shall I configure it? Other than in my DbContext, where I already configured my relations for my entities?

**Comment by acjh** [comment] 2020-03-09 14:42
Configure `DefaultWithDetailsFunc` in your `EntityFrameworkCoreModule` as @<span></span>yinchang0626 showed above. See https://github.com/abpframework/abp/issues/616#issuecomment-443387977.

For `CrudAppService.GetListAsync`, you also need https://github.com/abpframework/abp/issues/2474#issuecomment-569508507:

> Override `CreateFilteredQuery` of the `CrudAppService` and `return Repository.WithDetails();`

**Comment by acjh** [comment] 2020-03-09 14:45
Duplicate of #2474

**Comment by Znow** [comment] 2020-03-09 21:15
@acjh Your example helped, thanks alot. It seems very tedious to get relationships working... I will document it if needed, but where should it be placed?

**Comment by acjh** [comment] 2020-03-11 15:30
> It seems very tedious to get relationships working...

That's because you should probably avoid loading relationships in `CrudAppService.GetListAsync`.

> I will document it if needed, but where should it be placed?

It doesn't seem to fit in either of these:
- Basics: https://docs.abp.io/en/abp/latest/Entity-Framework-Core
- Best practices: https://docs.abp.io/en/abp/latest/Best-Practices/Entity-Framework-Core-Integration

I'd consider it Tips & Tricks, since it's about configuring EF Core entities for Application Services.

I'm not inclined to adding it to the documents.

**Comment by Znow** [comment] 2020-05-01 10:06
This seems to be broken and is not working in latest release. My navigation properties which previously had values, dont have values now.

**Comment by liangshiw** [comment] 2020-05-01 13:14
@Znow 
You can refer to the abp module source code: https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/modules/identityserver/src/Volo.Abp.IdentityServer.EntityFrameworkCore/Volo/Abp/IdentityServer/AbpIdentityServerEfCoreQueryableExtensions.cs

**Comment by Znow** [comment] 2020-05-05 06:57
@liangshiw Which I am already using based on previos replies......

**Comment by liangshiw** [comment] 2020-05-05 07:46
Hi @Znow 
I can't reproduce this problem. Can you use cli to create a simple project to reproduce this problem?

**Comment by Znow** [comment] 2020-05-05 07:55
@liangshiw Yes I will have a look at it asap

**Closed** 2020-05-10 13:00 UTC
