### ISSUE TITLE
Angular template duplicating entries while inserting

### ISSUE THREAD

**Issue by thiag0coelho** [abpframework/abp#2091] opened 2019-11-06 02:54 UTC
Version: 1.0.2
Created template on abp.io/get-started

Creating new Tenant named "test", duplicating entries, throws unknown error probably due to unique name error (also needs a better error description)

![image](https://user-images.githubusercontent.com/6138475/68263946-1936cb00-0026-11ea-9bbf-77ffeee6c1b9.png)

Creating new role named "test", duplicating entries
![image](https://user-images.githubusercontent.com/6138475/68264143-a67a1f80-0026-11ea-8f4b-d839923ea507.png)

Same when trying to create new user.
![image](https://user-images.githubusercontent.com/6138475/68264393-7717e280-0027-11ea-97ca-135cea34e735.png)

**Comment by maliming** [comment] 2019-11-06 02:56
Duplicate of #2043

**Closed by maliming** 2019-11-06 02:56 UTC
