### ISSUE TITLE
How to include relationships in queries

### ISSUE THREAD

**Issue by thiag0coelho** [abpframework/abp#2474] opened 2019-12-26 15:27 UTC
It is not yet clear in documentation on how to include query relationships.

I'm using EfCoreRepository implementation of IRepository. For the service endpoint I'm using a default generic AppService.

Document says best practice is implement a extension method like this

 ```
   public static class ModuleExampleEfCoreQueryableExtensions
    {
        public static IQueryable<Entity> IncludeDetails(this IQueryable<Entity> queryable, bool include = true)
        {
            if (!include)
            {
                return queryable;
            }
        
            return queryable
                .Include(x => x.RelatedEntity);
        }
    }
```

I've checked EfCoreRepository source code and noticed GetList uses WithDetails

```
        public override async Task<List<TEntity>> GetListAsync(bool includeDetails = false, CancellationToken cancellationToken = default)
        {
            return includeDetails
                ? await WithDetails().ToListAsync(GetCancellationToken(cancellationToken))
                : await DbSet.ToListAsync(GetCancellationToken(cancellationToken));
        }
```

While WithDetails (with no parameter) completely ignores any include, simply uses an empty IQueryable

```
        public override IQueryable<TEntity> WithDetails()
        {
            if (AbpEntityOptions.DefaultWithDetailsFunc == null)
            {
                return base.WithDetails();
            }

            return AbpEntityOptions.DefaultWithDetailsFunc(GetQueryable());
        }
```

**Comment by maliming** [comment] 2019-12-27 01:27
Override `WithDetails `method.

https://github.com/abpframework/abp/blob/42f37c5ff01ad853a5425d15539d4222cd0dab69/modules/identity/src/Volo.Abp.Identity.EntityFrameworkCore/Volo/Abp/Identity/EntityFrameworkCore/EfCoreIdentityUserRepository.cs#L146

**Comment by thiag0coelho** [comment] 2019-12-27 03:27
Thanks for the prompt reply. I've tried overriding WithDetails exactly as implemented in IdentityResourceRepository. Somehow it does not use the overriden method, breakpoint is not being hit on WithDetails. Am I missing something? Should this method be virtual in EfCoreRepository?

`    public class TenantBancoAppService :
        CrudAppService<TenantBanco, TenantBancoDto, long, PagedAndSortedResultRequestDto,
            CreateUpdateTenantBancoDto, CreateUpdateTenantBancoDto>,
        ITenantBancoAppService
    {
        private readonly ITenantBancoRepository _tenantBancoRepository;
        protected override string CreatePolicyName => Permissions.AdministracaoPermissions.TenantBancosCreate;
        protected override string GetPolicyName => Permissions.AdministracaoPermissions.TenantBancosRead;
        protected override string GetListPolicyName => Permissions.AdministracaoPermissions.TenantBancosRead;
        protected override string UpdatePolicyName => Permissions.AdministracaoPermissions.TenantBancosUpdate;
        protected override string DeletePolicyName => Permissions.AdministracaoPermissions.TenantBancosDelete;

        public TenantBancoAppService(ITenantBancoRepository repository)
            : base(repository)
        {
            _tenantBancoRepository = repository;
        }
    }`

`    public class TenantBancoRepository : EfCoreRepository<VMPromotoraDbContext, TenantBanco, long>,
        ITenantBancoRepository
    {
        public TenantBancoRepository(IDbContextProvider<VMPromotoraDbContext> dbContextProvider) : base(
            dbContextProvider)
        {
        }
        
        public override IQueryable<TenantBanco> WithDetails()
        {
            return GetQueryable().IncludeDetails();
        }
    }`

**Comment by wakuflair** [comment] 2019-12-27 06:26
@thiag0coelho 
Try setting `DefaultWithDetailsFunc` like this:

https://github.com/abpframework/abp/blob/0c823682ae723d8999bbfd859572a0b8f098c001/framework/test/Volo.Abp.EntityFrameworkCore.Tests/Volo/Abp/EntityFrameworkCore/AbpEntityFrameworkCoreTestModule.cs#L33

**Comment by acjh** [comment] 2019-12-27 07:48
Duplicate of #616

**Comment by thiag0coelho** [comment] 2019-12-27 22:31
This approach worked fine with Get, but not GetList, that I need the most. Any ideas on how to solve?

When I make GET /tenantBancos I expect it to go through this method, but it doesn't.
 ```
       public override async Task<List<TEntity>> GetListAsync(bool includeDetails = false, CancellationToken cancellationToken = default)
        {
            return includeDetails
                ? await WithDetails().ToListAsync(GetCancellationToken(cancellationToken))
                : await DbSet.ToListAsync(GetCancellationToken(cancellationToken));
        }
```

Also, what seems strange is that I didn't want to make a custom repository for this entity, I was forced to create becasuse Autofac wasn't able to create a IRepository<TenantBanco, long>. All other entities were created with no problem. Maybe because it has "Tenant" in its name?

**Comment by thiag0coelho** [comment] 2019-12-27 22:49
Noticed that AppService GetAll with paged settings 

     ```
   public override async Task<PagedResultDto<TenantOrgaoDto>> GetListAsync(PagedAndSortedResultRequestDto input)
        {
            await CheckGetListPolicyAsync();

            var query = CreateFilteredQuery(input);

            var totalCount = await AsyncQueryableExecuter.CountAsync(query);

            query = ApplySorting(query, input);
            query = ApplyPaging(query, input);

            **// that approach do not use WithDetails
            var entities = await AsyncQueryableExecuter.ToListAsync(query);**

            // that approach below do use WithDetails
            // var entities = await Repository.GetListAsync(true);

            return new PagedResultDto<TenantOrgaoDto>(
                totalCount,
                entities.Select(MapToGetListOutputDto).ToList()
            );
        }
```

**Comment by hikalkan** [comment] 2019-12-29 14:03
Override `CreateFilteredQuery` and `return Repository.WithDetails();`

**Comment by thiag0coelho** [comment] 2019-12-29 18:28
That worked! Thanks!

**Closed** 2019-12-30 09:17 UTC
Labels: question
