### ISSUE TITLE
An error occurred When"Generic Repository without a Primary Key"

### ISSUE THREAD

**Issue by aricyu** [abpframework/abp#5586] opened 2020-09-23 11:49 UTC
* ABP Framework version：3.1.1.

Documentation：

> ### Generic Repository without a Primary Key
> If your entity does not have an Id primary key (it may have a composite primary key for instance) then you cannot use the `IRepository<TEntity, TKey>` (or basic/readonly versions) defined above. In that case, you can inject and use `IRepository<TEntity>` for your entity.

My Code:
```
        private readonly IRepository<IdentityUserOrganizationUnit> _userOrganizationUnitRepository;

        public OrganizationUnitAppService(IRepository<IdentityUserOrganizationUnit> userOrganizationUnitRepository)
        {
            _userOrganizationUnitRepository = userOrganizationUnitRepository;
        }

        public async Task<IEnumerable<Guid>> TestAsync(Guid? id)
        {
            var result = await _userOrganizationUnitRepository
                .WhereIf(id.HasValue, n => n.OrganizationUnitId == id.Value)
                .Select(n => n.UserId).ToListAsync();

            return result;
        }
```

Error:
```
2020-09-23 19:37:29.798 +08:00 [ERR] An exception was thrown while activating Castle.Proxies.OrganizationUnitAppServiceProxy.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Castle.Proxies.OrganizationUnitAppServiceProxy.
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Castle.Proxies.OrganizationUnitAppServiceProxy' can be invoked with the available services and parameters:
Cannot resolve parameter 'Volo.Abp.Domain.Repositories.IRepository`1[Volo.Abp.Identity.IdentityUserOrganizationUnit] userOrganizationUnitRepository' of constructor 'Void .ctor(Castle.DynamicProxy.IInterceptor[], Volo.Abp.Domain.Repositories.IRepository`1[Volo.Abp.Identity.IdentityUserOrganizationUnit])'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.GetValidConstructorBindings(ConstructorInfo[] availableConstructors, IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Microsoft.AspNetCore.Mvc.Controllers.ServiceBasedControllerActivator.Create(ControllerContext actionContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2020-09-23 19:37:29.802 +08:00 [ERR] ---------- Exception Data ----------
ActivatorChain = Castle.Proxies.OrganizationUnitAppServiceProxy
```

**Comment by maliming** [comment] 2020-09-23 11:51
Duplicate of #5390

**Closed as completed by maliming** 2020-09-23 11:51 UTC
