### ISSUE TITLE
About `issuer` of `OpenIddict`

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#12982] opened 2022-06-13 04:24 UTC
The **Issuer** of `OpenIddict` ends with `/`, This is different from the others.

![image](https://user-images.githubusercontent.com/25867/173016710-fb5b4a9d-afbb-4900-b094-463c3d600318.png)

Here are others:

**Google:**
![image](https://user-images.githubusercontent.com/25867/173020495-311353a6-9e06-46b7-9382-28a22639005f.png)

**Facebook:**
![image](https://user-images.githubusercontent.com/25867/173021453-c2d25baf-5953-4493-8f6b-8792733fea1a.png)

**Microsoft:**
![image](https://user-images.githubusercontent.com/25867/173021522-a7a5a82f-894e-47e2-be57-db81bde6e592.png)

**Paypal:**
![image](https://user-images.githubusercontent.com/25867/173020944-d2026739-7329-4aa2-bcfd-09907b9271ca.png)

**Comment by hikalkan** [comment] 2022-06-13 06:27
@kevinchalet can you help on that? Is that a problem, can be configured?
@maliming can you clearly write the problems caused by this kind of issuer value?

**Comment by gterdem** [comment] 2022-06-13 06:41
@hikalkan 
Currently, angular applications are having problems when the issuer is ending with a trailing slash. Furthermore, this will be a question asked to us as well.

**Comment by kevinchalet** [comment] 2022-06-13 11:59
> @kevinchalet can you help on that? Is that a problem, can be configured?

OpenIddict uses `System.Uri` to represent the `Issuer` value. As recommended by RFC3986, `System.Uri` normalizes URIs with an **empty path** to always include a trailing slash:

> In general, a URI that uses the generic syntax for authority with an empty path should be normalized to a path of "/".

https://datatracker.ietf.org/doc/html/rfc3986#section-6.2.3

Neither the OIDC discovery specification nor the newer OAuth 2.0 server metadata standard require a specific form for URIs (they just say these values must be HTTPS URLs) so both forms are actually valid.

FWIW, I encountered a similar issue while working on the OpenIddict client: I ended up tweaking the token validation process to allow both forms to ensure it's compatible with all servers.

**Comment by kevinchalet** [comment] 2022-06-13 11:59
> @hikalkan
Currently, angular applications are having problems when the issuer is ending with a trailing slash. Furthermore, this will be a question asked to us as well.

Can you tell us more about these Angular apps? Do you know whether they use a particular client?

**Comment by gterdem** [comment] 2022-06-13 20:07
Hello @kevinchalet 

I agree with everything you said about [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986#section-6.2.3) however, I think we should consider **the issuer** as a URL instead of a URI.

In OpenId Discovery standard under [OpenID Provider Configuration Request](https://openid.net/specs/openid-connect-discovery-1_0-17.html) 

> If the Issuer value contains a path component, any terminating / MUST be removed before appending /.well-known/openid-configuration.

That leads to [RFC5785](https://datatracker.ietf.org/doc/html/rfc5785) that:

> A well-known URI is a URI [[RFC3986](https://datatracker.ietf.org/doc/html/rfc3986)] whose path component begins with
>    the characters "/.well-known/"

states that the trailing slash belongs to **.well-known**, not the issuer.

This continues with all the other endpoints like `/userinfo`, `/introspect` etc.

What do you think?

**Comment by kevinchalet** [comment] 2022-06-13 20:26
Hey @gterdem 😃 

> I think we should consider the issuer as a URL instead of a URI.

By definition, all URLs are URIs so the rules that define URIs necessarily apply to URLs. The samples shown in the section of RFC3986 I mentioned are actually HTTP URLs:

![image](https://user-images.githubusercontent.com/6998306/173437361-142ef1ee-e157-40ce-96ea-1103c5d71a18.png)

> In OpenId Discovery standard under [OpenID Provider Configuration Request](https://openid.net/specs/openid-connect-discovery-1_0-17.html)

I believe you're overthinking it: it only indicates how to construct the OIDC discovery document address, it doesn't say anything about the `issuer` in the response itself.

IMO, it requires removing the trailing slash of the issuer before appending the path part - that always starts with a `/` (`/.well-known/openid-configuration` is no exception) - simply to avoid ending up with two slashes: `http://issuer.com/` + `/.well-known/openid-configuration` = `http://issuer.com//.well-known/openid-configuration`.

> states that the trailing slash belongs to .well-known, not the issuer.

Sure: the first `/` slash that follows the host/port is always part of the path. A value of `http://localhost/` - as returned by OpenIddict - indicates that the scheme is `http`, the host is `localhost`, the port is `80` (implicit) and the path is `/`. It's semantically equivalent to `http://localhost:80`, `http://localhost:80/`, `http://localhost` and even `http://localhost:` (tho' this one is almost never seen in practice).

If you've seen compat' issues with a specific Angular lib, we should inform its author ASAP so they can fix that on their side.

**Comment by gterdem** [comment] 2022-06-14 07:25
Thanks for your input @kevinchalet 

Not the Angular oidc lib but our own Angular code-base seems to use it without trailing slash (which shall be updated).
However, there can also be issues with developers already using client-credentials flow and setting issuer manually. 

In order to prevent breaking change for them and possible `Issuer mismatch` errors in multi-tenant, multi-host issuer scenarios we need to make a smooth transition from IdentityServer to OpenIddict.

I believe allowing to set the `Issuer` statically can prevent this but [OpenIddictServerOptions](https://github.com/openiddict/openiddict-core/blob/fcf3f92fe20fac9ba778afb28c4536eaf674d4a1/src/OpenIddict.Server/OpenIddictServerOptions.cs#L22) also accepts URI.

Is there a way to set it to a **string** instead of URI like in [IdentityServerOptions](https://github.com/IdentityServer/IdentityServer4/blob/5bcc2abbcf6c47200c4eb3b77e756f1bc0e04358/src/IdentityServer4/src/Configuration/DependencyInjection/Options/IdentityServerOptions.cs#L19)?

**Comment by kevinchalet** [comment] 2022-06-14 11:49
> Not the Angular oidc lib but our own Angular code-base seems to use it without trailing slash (which shall be updated).

There are basically 2 parts that will use the `issuer` value:
  - The discovery client, that is supposed to validate the returned value and ensure it's the same URL as the one used in the request.
  - The token validation part, that will typically use the `issuer` as-is to validate incoming tokens (OpenIddict also adds a trailing slash to issued tokens so the two should always match).

> Is there a way to set it to a string instead of URI like in [IdentityServerOptions](https://github.com/IdentityServer/IdentityServer4/blob/5bcc2abbcf6c47200c4eb3b77e756f1bc0e04358/src/IdentityServer4/src/Configuration/DependencyInjection/Options/IdentityServerOptions.cs#L19)?

Nope, at least not trivially: as I said, OpenIddict uses `System.Uri` to represent the issuer, not a `string`, so you always get the normalization enforced. If you think you absolutely need to remove that trailing slash, you'll need to create multiple event handlers to override the `issuer` in the configuration response and tweak the `TokenValidationParameters` so that it accepts tokens whose issuer don't end with a `/` (regarding this last point, OpenIddict 4.0 will make things easier as both `http://localhost/` and `http://localhost` will be accepted natively).

**Comment by gterdem** [comment] 2022-07-18 06:13
Closing the issue as it is by OpenIddict design.

**Closed as completed by gterdem** 2022-07-18 06:13 UTC
Labels: abp-module-openiddict

**Comment by udda** [comment] 2022-09-20 16:29
If you are using .NET 6, it's now possible to render `System.Uri`s without trailing slash, using the constructor overload with [UriCreationOptions ](https://learn.microsoft.com/en-us/dotnet/api/system.uricreationoptions)

```csharp
services.AddOpenIddict().AddServer(o =>
{
    // ...more code
    var uriString = "http://localhost"; // omit trailing slash here
    var uri = new Uri(uriString, new UriCreationOptions { DangerousDisablePathAndQueryCanonicalization = true });
    o.SetIssuer(uri);
    // ...more code
}
```

I briefly tested it and it appears to work properly. Issuer string displays without trailing slash both in discovery document and inside the generated tokens.

**Comment by kevinchalet** [comment] 2022-09-20 16:43
> If you are using .NET 6, it's now possible to render `System.Uri`s without trailing slash, using the constructor overload with [UriCreationOptions ](https://learn.microsoft.com/en-us/dotnet/api/system.uricreationoptions)

It's something I had tested but I didn't mention it in my reply because it has unexpected side effects (hence the "dangerous" part in the name 🤣). Consider the following snippet:

```csharp
var issuer = new Uri("http://mydomain.com", new UriCreationOptions
{
    DangerousDisablePathAndQueryCanonicalization = true
});

var result = new Uri(issuer, "connect/token");
```

If you don't use that flag, the result variable contains the expected value: `http://mydomain.com/connect/token`. But if you set it to `true`, path concatenations no longer work correctly: `http://mydomain.comconnect/token`

Amusingly, it works in OpenIddict because the current implementation accounts for cases where the path wouldn't end with `/` when computing absolute URLs:

```csharp
static Uri? GetEndpointAbsoluteUri(Uri? issuer, Uri? endpoint)
{
    // If the endpoint is disabled (i.e a null address is specified), return null.
    if (endpoint is null)
    {
        return null;
    }

    // If the endpoint address is already an absolute URL, return it as-is.
    if (endpoint.IsAbsoluteUri)
    {
        return endpoint;
    }

    // At this stage, throw an exception if the issuer cannot be retrieved.
    if (issuer is not { IsAbsoluteUri: true })
    {
        throw new InvalidOperationException();
    }

    // Ensure the issuer ends with a trailing slash, as it is necessary
    // for Uri's constructor to correctly compute correct absolute URLs.
    if (!issuer.OriginalString.EndsWith("/", StringComparison.Ordinal))
    {
        issuer = new Uri(issuer.OriginalString + "/", UriKind.Absolute);
    }

    // Ensure the endpoint does not start with a leading slash, as it is necessary
    // for Uri's constructor to correctly compute correct absolute URLs.
    if (endpoint.OriginalString.StartsWith("/", StringComparison.Ordinal))
    {
        endpoint = new Uri(endpoint.OriginalString.Substring(1, endpoint.OriginalString.Length - 1), UriKind.Relative);
    }

    return new Uri(issuer, endpoint);
}
```

That said, it's an implementation detail and not a guarantee. Should the use of this flag become "official", a global pass in OpenIddict would have to be made to ensure nothing breaks unexpectedly.

**Comment by blushmaq** [comment] 2023-07-04 06:21
![image](https://github.com/abpframework/abp/assets/16643315/a3f2fa5d-ff9a-4d20-8cf3-d77a89dfb69f)
This seems to be an issue when I try to deploy it on Azure App services. 

I'm on a Tiered ABP App, with all 3 apps (Http.Host, AuthServer, Angular frontend) hosted on azure app services independently.
Gives me the trailing slash issue when angular app tries to communicate to identityserver app


> If you are using .NET 6, it's now possible to render `System.Uri`s without trailing slash, using the constructor overload with [UriCreationOptions ](https://learn.microsoft.com/en-us/dotnet/api/system.uricreationoptions)
> 
> ```cs
> services.AddOpenIddict().AddServer(o =>
> {
>     // ...more code
>     var uriString = "http://localhost"; // omit trailing slash here
>     var uri = new Uri(uriString, new UriCreationOptions { DangerousDisablePathAndQueryCanonicalization = true });
>     o.SetIssuer(uri);
>     // ...more code
> }
> ```
> 
> I briefly tested it and it appears to work properly. Issuer string displays without trailing slash both in discovery document and inside the generated tokens.

The above code worked for me. Thanks

**Comment by rsoulard** [comment] 2025-04-15 19:56
This still is not configured correctly out of the box and needs to be addressed.
