### ISSUE TITLE
Commercial Login Broken

### ISSUE THREAD

**Issue by michaelsudnik** [abpframework/abp#3418] opened 2020-03-30 12:46 UTC
I just tried to register / login and received an http 500 server error.
https://commercial.abp.io/signin-oidc
https://commercial.abp.io/Account/Login

**Comment by maliming** [comment] 2020-03-30 13:38
Have you tried in Chrome's incognito mode?

**Comment by michaelsudnik** [comment] 2020-03-30 13:53
Yes


-------- Original message --------

**Comment by maliming** [comment] 2020-03-30 14:03
But I can't reproduce your problem.

**Comment by michaelsudnik** [comment] 2020-03-30 14:39
It is not working on both of my laptops in incognito mode, both of my phones and my wife's phone. 

When we clicked the login link in the top right-hand corner of the page https://commercial.abp.io/ I saw a login screen. I then proceeded to register and it subsequently redirected me to https://commercial.abp.io/signin-oidc which showed an HTTP 500 error. 

In incognito mode, I was able to get to the login screen, but after inputting my login details, it redirected me again to https://commercial.abp.io/signin-oidc and displayed the HTTP 500 error. 

Do you not have access to any trace logs that you can take a look at to confirm it?

**Comment by maliming** [comment] 2020-03-31 01:48
@ismcagdas  I remember someone who had feedback on a similar issue, although I can't reproduce it, but we can check the log. 

![image](https://user-images.githubusercontent.com/6908465/77978418-b0355400-7334-11ea-8aad-f981e653cc1d.png)

**Comment by maliming** [comment] 2020-03-31 01:51
hi @michaelsudnik What is your chrome version? Have you tried other browsers?  eg: Firefox, Edge.

**Comment by maliming** [comment] 2020-03-31 08:57
Will be fixed in v2.4.

**Closed** 2020-04-15 07:09 UTC
Labels: abp-io
