### ISSUE TITLE
where can I know the release plan?

### ISSUE THREAD

**Issue by xyfy** [abpframework/abp#1559] opened 2019-07-31 07:55 UTC
I got a json serializersetting bug  same as #1487 

I searched the issues , you fixed the bug in 0.19

but I do not know when will the version will release.

I am a newbie, but I want to participate in your development and do what I can
 what should I do or how I do?

**Comment by maliming** [comment] 2019-07-31 08:04
Duplicate of https://github.com/abpframework/abp/issues/1506#issuecomment-516743190

**Closed by maliming** 2019-07-31 08:04 UTC
