### ISSUE TITLE
blazor start can't  get CurrentUser, CurrentUser is null

### ISSUE THREAD

**Issue by guolianyu** [abpframework/abp#8593] opened 2021-04-13 09:11 UTC
![image](https://user-images.githubusercontent.com/29138525/114527997-2aecbb00-9c7b-11eb-9be6-ceb6ee03662d.png)

**Comment by guolianyu** [comment] 2021-04-13 09:14
when I reloaded page,currentUser is not null; 
version:4.2.1 or 4.3.0-rc.2  has problem

**Comment by maliming** [comment] 2021-04-13 09:20
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by realLiangshiwei** [comment] 2021-04-13 09:50
Duplicate of https://github.com/abpframework/abp/issues/8240

**Closed as completed by realLiangshiwei** 2021-04-13 09:50 UTC
