### ISSUE TITLE
Problem with staticclient generation.

### ISSUE THREAD

**Issue by CherryGoose** [abpframework/abp#14851] opened 2022-11-28 09:33 UTC
I have tiered project with modules and im having a problem with creating static api endpoints. When i generate proxy endpoints in client (as per https://docs.abp.io/en/abp/latest/API/Static-CSharp-API-Clients) only command generates all of the proxys to my services in main project. Also when i try to use them on my page only services from main project can by called. Those that are in module are not found.
Steps to reproduce the issue:
- Create tiered solution with sqlite as dbms called "Base.App"
- Add module called "NewModule" - (names don't matter) 
- Change configs to static api clients as per guide
- Create custom name for module 
 private void ConfigureConventionalControllers()
        {
            Configure<AbpAspNetCoreMvcOptions>(options =>
            {
                options.ConventionalControllers.Create(typeof(NewModuleApplicationModule).Assembly, opts =>
                {
                    opts.RootPath = "new-module";
                    opts.RemoteServiceName =NewModuleRemoteServiceConsts.RemoteServiceName;
                });
}}
- Create service in base app and newmodule with interfaces and all that is necessary
- Generate proxys
- Inject service from module on main page model
- Try calling service.

Can someone help me and point out what im doing wrong?

**Comment by berkansasmaz** [comment] 2022-12-02 07:27
Hello,

abp's `generate-proxy` command provides an extra option to specify the module. Could you please pass this parameter and try again?

For example:

`abp generate-proxy -t csharp -u https://localhost:44361 -m Cms-Kit`

**Comment by CherryGoose** [comment] 2022-12-02 07:41
Hello, yes i have tried that as well, it generates proxy files in the module (fyi some of them are the same if i generate proxys in base app for example if there is "newservice" in module, it generates newservice proxy in main app http client ) but if i try to inject service from module to main app page it gives me "not found" error. 

> Hello,
> 
> abp's `generate-proxy` command provides an extra option to specify the module. Could you please pass this parameter and try again?
> 
> For example:
> 
> `abp generate-proxy -t csharp -u https://localhost:44361 -m Cms-Kit`

**Comment by berkansasmaz** [comment] 2022-12-05 06:32
> if i try to **inject service from module to main app** page it gives me "not found" error.

I can't say I fully understand this part. Can you clarify so I can help better? If necessary, you can send a code sample.

**Comment by CherryGoose** [comment] 2022-12-05 08:13
for example here is my module service
```
public class ModuleAppService : NewModuleAppService, IModuleAppService
    {
        private string modAtt;
        public ModuleAppService()
        { 
        
        
        }


        public async Task<bool> SetModAttAsync(string m)
        { 
            modAtt = m;
            
            return true;
        }
    }
```
The way i registered module in api host

```
   private void ConfigureConventionalControllers()
    {
        Configure<AbpAspNetCoreMvcOptions>(options =>
        {
            options.ConventionalControllers.Create(typeof(TestProjectApplicationModule).Assembly);

            options.ConventionalControllers.Create(typeof(NewModuleApplicationModule).Assembly, opts =>
            {
                opts.RootPath = "new-module";
                opts.RemoteServiceName = "NewModule";

            });
        });
    }
```


Here is generated controller

```
namespace NewModule.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IModuleAppService), typeof(ModuleClientProxy))]
public partial class ModuleClientProxy : ClientProxyBase<IModuleAppService>, IModuleAppService
{
    public virtual async Task<bool> SetModAttAsync(string m)
    {
        return await RequestAsync<bool>(nameof(SetModAttAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), m }
        });
    }
}
```


When i call this method in IndexModel of main web project i get not found error

```
public class IndexModel : TestProjectPageModel
{

    private IModuleAppService _moduleAppService;
    public IndexModel(IModuleAppService moduleAppService) 
    {
    _moduleAppService = moduleAppService;
    }
public async void OnGet()
    {
       var res =await _moduleAppService.SetModAttAsync("1");
    }
}
```

**Comment by berkansasmaz** [comment] 2022-12-06 08:45
I think there is something you missed.

You probably added a static http client proxy in the configure service of the `**HttpApiClientModule` as follows.

 ```csharp
    public override void ConfigureServices(ServiceConfigurationContext context)
    {
        context.Services.AddStaticHttpClientProxies(
            typeof(MyProjectNamePublicApplicationContractsModule).Assembly,
            MyProjectNamePublicRemoteServiceConsts.RemoteServiceName
        );
    }
```


But I think you didn't add `**HttpApiClientModule` to Virtual file system.

```csharp
    public override void ConfigureServices(ServiceConfigurationContext context)
    {
        context.Services.AddStaticHttpClientProxies(
            typeof(MyProjectNamePublicApplicationContractsModule).Assembly,
            MyProjectNameRemoteServiceConsts.RemoteServiceName
        );

        // add virtual file system
        Configure<AbpVirtualFileSystemOptions>(options =>
        {
            options.FileSets.AddEmbedded<MyProjectNamePublicHttpApiClientModule>();
        });
    }
```

**Comment by CherryGoose** [comment] 2022-12-06 10:01
> ```cs
> AbpVirtualFileSystemOptions
> ```


nope, all here

namespace TestProject;

[DependsOn(
    typeof(TestProjectApplicationContractsModule),
    typeof(AbpAccountHttpApiClientModule),
    typeof(AbpIdentityHttpApiClientModule),
    typeof(AbpPermissionManagementHttpApiClientModule),
    typeof(AbpTenantManagementHttpApiClientModule),
    typeof(AbpFeatureManagementHttpApiClientModule),
    typeof(AbpSettingManagementHttpApiClientModule)
)]
[DependsOn(typeof(NewModuleHttpApiClientModule))]
    public class TestProjectHttpApiClientModule : AbpModule
{
    public const string RemoteServiceName = "Default";

    public override void ConfigureServices(ServiceConfigurationContext context)
    {
        context.Services.AddStaticHttpClientProxies(
            typeof(TestProjectApplicationContractsModule).Assembly,
            RemoteServiceName
        );

        Configure<AbpVirtualFileSystemOptions>(options =>
        {
            options.FileSets.AddEmbedded<TestProjectHttpApiClientModule>();
        });
    }
}

and the module as well 

namespace NewModule;

[DependsOn(
    typeof(NewModuleApplicationContractsModule),
    typeof(AbpHttpClientModule))]
public class NewModuleHttpApiClientModule : AbpModule
{
    public override void ConfigureServices(ServiceConfigurationContext context)
    {
        context.Services.AddStaticHttpClientProxies(
            typeof(NewModuleApplicationContractsModule).Assembly,
            NewModuleRemoteServiceConsts.RemoteServiceName
        );

        Configure<AbpVirtualFileSystemOptions>(options =>
        {
            options.FileSets.AddEmbedded<NewModuleHttpApiClientModule>();
        });

    }
}

**Comment by berkansasmaz** [comment] 2022-12-07 06:14
Got it, it would be great if you could post a minimal reproducible example so I can help you better. Because the test application I created works when I add the last thing I said.

**Comment by CherryGoose** [comment] 2022-12-07 06:49
> I think there is something you missed.
> 
> You probably added a static http client proxy in the configure service of the `**HttpApiClientModule` as follows.
> 
> ```cs
>    public override void ConfigureServices(ServiceConfigurationContext context)
>    {
>        context.Services.AddStaticHttpClientProxies(
>            typeof(MyProjectNamePublicApplicationContractsModule).Assembly,
>            MyProjectNamePublicRemoteServiceConsts.RemoteServiceName
>        );
>    }
> ```
> 
> But I think you didn't add `**HttpApiClientModule` to Virtual file system.
> 
> ```cs
>     public override void ConfigureServices(ServiceConfigurationContext context)
>     {
>         context.Services.AddStaticHttpClientProxies(
>             typeof(MyProjectNamePublicApplicationContractsModule).Assembly,
>             MyProjectNameRemoteServiceConsts.RemoteServiceName
>         );
> 
>         // add virtual file system
>         Configure<AbpVirtualFileSystemOptions>(options =>
>         {
>             options.FileSets.AddEmbedded<MyProjectNamePublicHttpApiClientModule>();
>         });
>     }
> ```

its all there


namespace NewModule;

[DependsOn(
    typeof(NewModuleApplicationContractsModule),
    typeof(AbpHttpClientModule))]
public class NewModuleHttpApiClientModule : AbpModule
{
    public override void ConfigureServices(ServiceConfigurationContext context)
    {
        context.Services.AddStaticHttpClientProxies(
            typeof(NewModuleApplicationContractsModule).Assembly,
            NewModuleRemoteServiceConsts.RemoteServiceName
        );

        Configure<AbpVirtualFileSystemOptions>(options =>
        {
            options.FileSets.AddEmbedded<NewModuleHttpApiClientModule>();
        });

    }
}

namespace TestProject;

[DependsOn(
    typeof(TestProjectApplicationContractsModule),
    typeof(AbpAccountHttpApiClientModule),
    typeof(AbpIdentityHttpApiClientModule),
    typeof(AbpPermissionManagementHttpApiClientModule),
    typeof(AbpTenantManagementHttpApiClientModule),
    typeof(AbpFeatureManagementHttpApiClientModule),
    typeof(AbpSettingManagementHttpApiClientModule)
)]
[DependsOn(typeof(NewModuleHttpApiClientModule))]
    public class TestProjectHttpApiClientModule : AbpModule
{
    public const string RemoteServiceName = "Default";

    public override void ConfigureServices(ServiceConfigurationContext context)
    {
        context.Services.AddStaticHttpClientProxies(
            typeof(TestProjectApplicationContractsModule).Assembly,
            RemoteServiceName
        );

        Configure<AbpVirtualFileSystemOptions>(options =>
        {
            options.FileSets.AddEmbedded<TestProjectHttpApiClientModule>();
        });
    }
}

**Comment by CherryGoose** [comment] 2022-12-08 07:17
> Got it, it would be great if you could post a minimal reproducible example so I can help you better. Because the test application I created works when I add the last thing I said.


https://github.com/CherryGoose/proxyRepo

here you go.

**Comment by berkansasmaz** [comment] 2022-12-08 08:31
Thank you for the sample application and your understanding throughout the process.

I reviewed your application and ran it.

The application ran smoothly even though you used [IModuleAppService](https://github.com/CherryGoose/proxyRepo/blob/9310078f512ffb96a021a853cfa4406a6dc07c7f/src/TestProject.Web/Pages/Index.cshtml.cs#L10) on the home page.

Later, on the same page, I inject and used [ISampleAppService](https://github.com/CherryGoose/proxyRepo/blob/main/modules/NewModule/src/NewModule.Application.Contracts/Samples/ISampleAppService.cs), and then when I ran it, I started getting an error as you said.

<img width="1679" alt="Screenshot 2022-12-08 at 11 19 54" src="https://user-images.githubusercontent.com/31216880/206396089-d2276a0a-8331-4c55-b1df-d9fd3ccf31df.png">

As a result, I found that the proxies that you have already created in the `**.HttpApi.Client` of the module are recreated in the `**.HttpApi.Client` module of the final application. After making the changes as in the picture below, the application continued to work without any problems.

<img width="668" alt="Screenshot 2022-12-08 at 11 19 42" src="https://user-images.githubusercontent.com/31216880/206397157-18c0b1e2-fd3a-4be9-acef-0e453c3a1532.png">

<img width="1679" alt="Screenshot 2022-12-08 at 11 34 21" src="https://user-images.githubusercontent.com/31216880/206398158-182909bc-f296-4920-b093-541595b4345b.png">

**Comment by berkansasmaz** [comment] 2022-12-15 06:44
Closing the issue. Feel free to re-open or create a new issue if you have further questions.

**Closed as completed by berkansasmaz** 2022-12-15 06:44 UTC

**Comment by CherryGoose** [comment] 2022-12-15 07:47
> Thank you for the sample application and your understanding throughout the process.
> 
> I reviewed your application and ran it.
> 
> The application ran smoothly even though you used [IModuleAppService](https://github.com/CherryGoose/proxyRepo/blob/9310078f512ffb96a021a853cfa4406a6dc07c7f/src/TestProject.Web/Pages/Index.cshtml.cs#L10) on the home page.
> 
> Later, on the same page, I inject and used [ISampleAppService](https://github.com/CherryGoose/proxyRepo/blob/main/modules/NewModule/src/NewModule.Application.Contracts/Samples/ISampleAppService.cs), and then when I ran it, I started getting an error as you said.
> 
> <img alt="Screenshot 2022-12-08 at 11 19 54" width="1679" src="https://user-images.githubusercontent.com/31216880/206396089-d2276a0a-8331-4c55-b1df-d9fd3ccf31df.png">
> 
> As a result, I found that the proxies that you have already created in the `**.HttpApi.Client` of the module are recreated in the `**.HttpApi.Client` module of the final application. After making the changes as in the picture below, the application continued to work without any problems.
> 
> <img alt="Screenshot 2022-12-08 at 11 19 42" width="668" src="https://user-images.githubusercontent.com/31216880/206397157-18c0b1e2-fd3a-4be9-acef-0e453c3a1532.png">
> 
> <img alt="Screenshot 2022-12-08 at 11 34 21" width="1679" src="https://user-images.githubusercontent.com/31216880/206398158-182909bc-f296-4920-b093-541595b4345b.png">

Yes, thank you that seems to fix the problem of calling module service but after deleting those file i can not call service located in base project i.e. MainAppService in TestProject.Application. It gives me Volo.Abp.Http.Client.AbpRemoteCallException internal  error. It Seems to me that there can only be proxys for modules of for main project. To test that i added second module and created proxys for it. Then called second module service. It worked fine, but MainAppService is still gives me an error stated above.

I have tried to set options for main services as if it was a module

            options.ConventionalControllers.Create(typeof(TestProjectApplicationModule).Assembly, opts =>
            {
                opts.RootPath = "main-module";
                opts.RemoteServiceName = "MainModule";

            });

 and regenerate proxys but result is the same.

I have pushed changes to repo, if you can advice on how to set up proxys for main project and modules it would be wonderful.
