### ISSUE TITLE
Audit log datetime arabic problem

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#5738] opened 2020-10-08 08:53 UTC
"In 3.1 While changing language into Arabic it's throwing exception. In AuditLog it was like a datetime issue. You can reproduce easily: 1. Simple Dto one you have to create. 2. Declare one variable as not nullable and type is datetime. 3. Get the records using that dto without datetime. 4. Now change your language into Arabic it will throw error. Thanks Abp Framework team."

(copied from https://blog.abp.io/abp/ABP-Framework-v3.2-Final-Has-Been-Released)

**Comment by cotur** [comment] 2020-10-08 17:25
I've detailed test it and could not reproduce this.
I will left open this issue for some days to get response the user that write the comment.

![image](https://user-images.githubusercontent.com/20099739/95492714-30073f80-09a4-11eb-9833-0814c88ff480.png)

**Comment by rasmani795** [comment] 2020-11-01 09:56
You can reproduce this issue:
1. Write simple linq query API for getting users details.
2. Create one Dto for getting records with AuditedEntityDto. 
3. Now get the record of user. Simply you take only username that's enough. 
4. So, Now from the angular create one component to call the API. And put console you can check that record is coming or not. 
5. Now you have the record of users. 
6. Switch your language to Arabic. It will shows error.

Its seems like time conversion issue but why its breaking I don't know. If still you can't reproduce let me know, I will provide each one screenshot the you can understand that issue.

**Comment by cotur** [comment] 2020-11-01 09:59
Hi @rasmani795, Thanks, I will investigate.

**Comment by cotur** [comment] 2020-11-06 11:06
Hi @rasmani795,

After that issue (https://github.com/abpframework/abp/issues/5606) is completed, the problem should be fixed. Please try to reproduce this problem at `4.0` version. 

I close this issue now, if you will get still same result (at `4.0` version), please write a comment with detailed screenshots, example project etc. then we will investigate again.

**Closed as completed by cotur** 2020-11-06 11:06 UTC
Labels: problem, abp-module-audit-logging, effort-1
