### ISSUE TITLE
CQRS Pattern with  mediatr package with Rabbitmq bus implementation

### ISSUE THREAD

**Issue by pranavpatil19** [abpframework/abp#1912] opened 2019-10-14 15:27 UTC
CQRS Pattern with mediatr package with Rabbitmq bus implementation..  please add this feature in this project

**Comment by hikalkan** [comment] 2019-10-14 16:39
Duplicate of https://github.com/abpframework/abp/issues/57

**Closed by hikalkan** 2019-10-14 16:39 UTC
