### ISSUE TITLE
Identity management > Users > Not all Actions are visible and disappear under paginator

### ISSUE THREAD

**Issue by joffies** [abpframework/abp#2783] opened 2020-02-08 12:04 UTC
Hi Guys

Downloaded the startup template for ASP.NET Core MVC (Razor pages UI) and can see an issue out of the box with the Actions button.

When clicking on the Actions button not all actions are visible and seem to disappear under the grid paginator. See attached example.
![Users Actions Button Actions Disapearing](https://user-images.githubusercontent.com/13243938/74084848-0ab7df80-4a6b-11ea-85bc-daec0fa29606.PNG)

Cheers

**Comment by johnnba** [comment] 2020-02-08 17:28
oh yes, in the latest version 2.0.1, i encountered the same problem.

**Comment by maliming** [comment] 2020-02-09 14:05
This problem occurs when we enable `scrollX `for datatables https://github.com/abpframework/abp/search?q=scrollX&unscoped_q=scrollX

Related issue: https://datatables.net/forums/discussion/comment/145791/#Comment_145791

**Comment by hikalkan** [comment] 2020-02-09 17:45
Duplicate of https://github.com/abpframework/abp/issues/2710
Add a custom CSS for now (see https://github.com/abpframework/abp/commit/c2518fd7f4f7c0d892496b62ad615555b58e796d)
Will be fixed with v2.1.

**Closed by hikalkan** 2020-02-09 17:45 UTC
Labels: problem, ui-mvc
