### ISSUE TITLE
DisableAuditing does not affect AuditLogs

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#4244] opened 2020-06-06 20:20 UTC
I made this controller reproduce the problem:
```
    public class HomeController : DisableAuditingTestController
    {
        [HttpHead]
        [Route("")]
        [DisableAuditing]
        public void Head()
        {
        }
        
        [HttpPost]
        [Route("")]
        [DisableAuditing]
        public void Post()
        {
        }
    }
```

1. Tried to access https://localhost:44382 with the **POST** or the **HEAD** method, I could still find a record in the AbpAduitLogs table, **DisableAuditing** attribute didn't seem to work.

1. Tried to access https://localhost:44382 with the **GET** method, AbpAduitLogs didn't have a new record, **IsEnabledForGetRequests** option worked.

Please pull this repository and try: https://github.com/gdlcf88/DisableAuditingTest/blob/master/src/DisableAuditingTest.HttpApi/Controllers/HomeController.cs

The ABP version is 2.9.0.

**Comment by gdlcf88** [comment] 2020-06-07 10:24
I found this method:

https://github.com/abpframework/abp/blob/decf4c7d34496ecf89661d9e184c22ba31b4aa47/framework/src/Volo.Abp.AspNetCore/Volo/Abp/AspNetCore/Auditing/AbpAuditingMiddleware.cs#L58-L82

It doesn't seem to be affected by **DisableAuditing** but affected by **IsEnabledForGetRequests**.

The **DisableAuditing** attribute only affects the action log, is it designed intentionally?

Relate to: https://github.com/abpframework/abp/issues/4010#issuecomment-631140840

**Comment by gdlcf88** [comment] 2020-06-07 10:42
Hello @hikalkan, I saw [your comment](https://github.com/abpframework/abp/issues/4010#issuecomment-631140840) about creating a ShouldCreateAuditLog() method to control the audit logs.

But I have a question about **DisableAuditing**: if it is designed to only affect the action log, its exact name may be **DisableAuditingAction** or it should also affect the AuditLogs as **IsEnabledForGetRequests** do?

**Comment by liangshiw** [comment] 2020-06-08 13:03
See https://github.com/abpframework/abp/issues/3662

**Comment by hikalkan** [comment] 2020-06-14 14:48
@gdlcf88 audit log not only contains controller actions. So, even if you disable for an action, it still write other auditing info.
`DisableAuditing` naming is fine since it does what it promise: disables auditing for the declated method & properties (you know it is also usable for DTO/entity properties).

It is not true to control (enable/disable) the behavior of a middleware by an attribute on a controller method or application service method (notice that a web request may container more than one app service methods - so which one should be considered in case of only one have disable attribute?). Attbitutes should control for the element it is declared for.

https://github.com/abpframework/abp/issues/4010#issuecomment-631140840 will solve your problem.

**Comment by hikalkan** [comment] 2020-06-14 14:48
I am closing this since it is by design.

**Closed by hikalkan** 2020-06-14 14:48 UTC

**Comment by gdlcf88** [comment] 2020-06-14 14:55
It's a clever design. Thank you for your explanation.
