### ISSUE TITLE
scriptUrl cannot be loaded on the second request via modal manager

### ISSUE THREAD

**Issue by viewtance** [abpframework/abp#2849] opened 2020-02-17 17:30 UTC
On a list page, such as the index page, the first time open a createModal or a editModal, the request scriptUrl could be loaded, but the second time, it cannot load the scriptUrl option, is it related with below code:

```
         if (typeof options === 'string') {
                options = {
                    viewUrl: options
                };
            }

            var _options = options;

            var _$modalContainer = null;
            var _$modal = null;
            var _$form = null;
```
The viewUrl be defined again, but the scriptUrl not.

**Comment by maliming** [comment] 2020-02-18 02:53
This is by design. 

https://github.com/abpframework/abp/blob/dce585c40d0306664ed69df3e353c2eff2db1508/npm/packs/jquery/src/abp.jquery.js#L345-L352

**Comment by viewtance** [comment] 2020-02-18 08:02
If this is by design, then initial a DOM element in the modal when it is be opened will not be implemented, such as bind a datepicker or a rich editor to a DOM element.

**Comment by maliming** [comment] 2020-02-18 08:09
Please share some code to explain your problem.

**Comment by viewtance** [comment] 2020-02-18 08:14
`
var abp = abp || {};

abp.modals.categoryEditModal = function () {
    var initModal = function (publicApi, args) {

        $('input.datepicker').datepicker({
            todayBtn: "linked",
            autoclose: true,
            language: abp.localization.currentCulture.cultureName
        }).on('hide', function (e) { e.stopPropagation(); });
        tinymce.init({
            selector: '#Category_Description'
        });

    };

    return {
        initModal: initModal
    };
};
`
In the above code snippet, the datepicker and the tinymce rich editor will not work as expected.

**Comment by maliming** [comment] 2020-02-18 08:55
Refer to the code of abp.

https://github.com/abpframework/abp/blob/dev/modules/docs/src/Volo.Docs.Admin.Web/Pages/Docs/Admin/Projects/Index.cshtml#L20
https://github.com/abpframework/abp/blob/dev/modules/docs/src/Volo.Docs.Admin.Web/Pages/Docs/Admin/Projects/index.js

However `scriptUrl `should be executed multiple times. I will try to fix it.

**Comment by ebicoglu** [comment] 2020-02-19 07:02
fixed in https://github.com/abpframework/abp/pull/2854

**Closed by ebicoglu** 2020-02-19 07:02 UTC
Labels: abp-framework, effort-0.5, problem

**Comment by viewtance** [comment] 2020-02-22 02:45
It seems this approach not fix the problem.
