### ISSUE TITLE
Data Migration Issue on macOS

### ISSUE THREAD

**Issue by xunqinbo** [abpframework/abp#9248] opened 2021-06-05 08:11 UTC
I created a project from template on abp.io.
When I run 'dotnet run' command under DbMigrator/

`ABP CLI (https://abp.io)
[15:39:21 INF] Version 4.3.2 (Stable)
[15:39:22 ERR] DbMigrator is not found!
System.Exception: DbMigrator is not found!
   at Volo.Abp.Cli.Commands.CreateMigrationAndRunMigratorCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\CreateMigrationAndRunMigratorCommand.cs:line 34
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 59
`

**Comment by berkansasmaz** [comment] 2021-10-13 11:23
I got the same error for `v5.0.0-beta.1`, fyi @yekalkan.

```txt
[14:14:35 INF] ABP CLI (https://abp.io)
[14:14:35 INF] Version 5.0.0-beta.1 (Prerelease)
[14:14:36 ERR] DbMigrator is not found!
System.Exception: DbMigrator is not found!
   at Volo.Abp.Cli.Commands.CreateMigrationAndRunMigratorCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\CreateMigrationAndRunMigratorCommand.cs:line 34
```

My steps: 

OS: `macOS`

1. `abp new Mvc.EfCoreNonTier435 -t app-pro -u mvc --mobile none --database-provider ef -csf --preview`
2. Change directory to `*.DbMigrator`
3. `dotnet run`

**Comment by berkansasmaz** [comment] 2021-10-13 11:55
By the way, the problem goes away when I create the database using `*.EntityFrameworkCore` project and then run `*.DbMigrator`.

**Comment by ebicoglu** [comment] 2021-11-12 19:22
> 
> 
> I got the same error for `v5.0.0-beta.1`, fyi @yekalkan.
> 
> ```
> [14:14:35 INF] ABP CLI (https://abp.io)
> [14:14:35 INF] Version 5.0.0-beta.1 (Prerelease)
> [14:14:36 ERR] DbMigrator is not found!
> System.Exception: DbMigrator is not found!
>    at Volo.Abp.Cli.Commands.CreateMigrationAndRunMigratorCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\CreateMigrationAndRunMigratorCommand.cs:line 34
> ```
> 
> My steps:
> 
> OS: `macOS`
> 
>     1. `abp new Mvc.EfCoreNonTier435 -t app-pro -u mvc --mobile none --database-provider ef -csf --preview`
> 
>     2. Change directory to `*.DbMigrator`
> 
>     3. `dotnet run`

I couldn't reproduce it for `app-pro` template

![image](https://user-images.githubusercontent.com/9526587/141523242-5752eb81-a7dd-4b43-9178-44ff6f22de60.png)

**Comment by ebicoglu** [comment] 2021-11-12 19:28
and this is  a test for app template with MongoDB.
I need the reproduce steps!


![image](https://user-images.githubusercontent.com/9526587/141523899-b128a171-140e-4401-b1c7-028017188176.png)

**Comment by ebicoglu** [comment] 2021-11-12 19:29
I'm closing the issue.
If you reproduce it, reopen it pls.

**Closed as completed by ebicoglu** 2021-11-12 19:29 UTC
Labels: problem, abp-cli
