### ISSUE TITLE
Why get user's permission need request 31 times?

### ISSUE THREAD

**Issue by abllyboy** [abpframework/abp#2777] opened 2020-02-07 03:33 UTC
When I get the user's permission in "BackendAdminApp.Host" ,it was very very slowly,when I go to look the logs I found it request 31 times,Why?
<img width="884" alt="2" src="https://user-images.githubusercontent.com/57399417/73998634-353b6700-499d-11ea-852a-6c57144e07d0.png">
<img width="921" alt="1" src="https://user-images.githubusercontent.com/57399417/73998638-37052a80-499d-11ea-8a3e-d8dba14f0cab.png">

**Comment by maliming** [comment] 2020-02-07 05:39
Duplicate of #2437

**Closed by maliming** 2020-02-07 05:39 UTC
