### ISSUE TITLE
can't use admin login 

### ISSUE THREAD

**Issue by hzxyb** [abpframework/abp#1468] opened 2019-07-10 12:26 UTC
Hi, I found that the new version can't use the admin to login.
the latest password was changed?  not "1q2w3E*" ?

**Comment by yekalkan** [comment] 2019-07-10 12:35
probably duplicate of https://github.com/abpframework/abp/issues/1265

You need to run *.DbMigrator project for seed data.

**Closed** 2019-07-11 05:18 UTC
