### ISSUE TITLE
Blazor UI: Removed Permissions still available 

### ISSUE THREAD

**Issue by barbarosyurttagul** [abpframework/abp#7699] opened 2021-02-11 11:58 UTC
Hi, I follow the tutorial Web Application Development Acme.BookStore for Blazor UI/EfCore. I am on the part 5 permissions. The removed permissions from the admin are still enabled unless I refresh the page. For example, I remove the edit permission for books for admin, then I try to edit a book and it still works. But the tutorial says as below:

> "If you don't refresh and try to use the prohibited action you get an HTTP 403 (forbidden) response from the server."

* My ABP Framework version 4.2.
* My User Interface type Blazor
* My database provider(EF Core)

**Comment by maliming** [comment] 2021-02-14 04:56
@stsrki  Can you help to check this?

**Comment by realLiangshiwei** [comment] 2021-02-18 03:02
Duplicate of https://github.com/abpframework/abp/issues/5526

**Closed as completed by realLiangshiwei** 2021-02-18 03:02 UTC
