### ISSUE TITLE
Proxy Generator: Recursive types cause infinite loop

### ISSUE THREAD

**Issue by happygb21** [abpframework/abp#5335] opened 2020-09-08 07:55 UTC
//[HttpGet]
        //[Route("www/{folder}/{name}")]
        //public async Task< FileResult > GetForWebAsync(string folder, string name) //TODO: output cache would be good
        //{
        //    var file = await _fileAppService.GetAsync(folder,name);
        //    return File(
        //        file.Bytes,
        //        MimeTypes.GetByExtension(Path.GetExtension(name))
        //    );
        //}
Maximum call stack size exceeded

**Comment by maliming** [comment] 2020-09-08 08:02
**Please provide more details.**


* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

**Comment by happygb21** [comment] 2020-09-08 08:25
version:3.1 
User Interface type Angular
Any service that adds this method and executes ABP generate proxy will report an error of "maximum call stack size exceeded"

**Comment by hikalkan** [comment] 2020-09-09 09:41
Move this to a dedicated controller and add `[RemoteService(false)]` to disable it.

@maliming is [RemoteService(false)] working in method level? Can you check it and implement it possible.

**Comment by hikalkan** [comment] 2020-09-09 11:07
@happygb21 can you try to add `[ApiExplorerSettings(IgnoreApi = true)]` to the method.

**Comment by maliming** [comment] 2020-09-10 02:03
`[ApiExplorerSettings(IgnoreApi = true)]` is works.

> Maximum call stack size exceeded

@armanozak Maybe we should handle this situation to prevent the error, what do you think?

**Comment by armanozak** [comment] 2020-09-11 09:28
@maliming This was fixed by #5295 and recursive types should not cause an infinite loop as of v3.1.1.

**Closed as completed** 2020-09-11 10:05 UTC
Labels: duplicate, problem
