### ISSUE TITLE
Index was outside the bounds of the array  11

### ISSUE THREAD

**Issue by zengnanhua** [abpframework/abp#15591] opened 2023-02-03 06:57 UTC
![image](https://user-images.githubusercontent.com/22017107/216532708-80159199-88a2-4e17-ad84-76e895d96e6d.png)

![image](https://user-images.githubusercontent.com/22017107/216532915-754daa8e-48c0-479a-9f6e-27912aa6a076.png)

**Comment by maliming** [comment] 2023-02-03 07:17
Duplicate of #15590

**Closed as completed by maliming** 2023-02-03 07:17 UTC
