### ISSUE TITLE
gRPC support - not yet planned

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2731] opened 2020-01-30 17:46 UTC
Hi,

I wish to know if you plan to add gRPC support one day ?

I know that it is not the first time you have this topic, but any update ?

BTW, there is an implementation here (but not an official one)
https://github.com/GameBelial/Abp.Grpc

**Comment by acjh** [comment] 2020-01-30 23:37
Duplicate of #605

**Closed by acjh** 2020-01-30 23:37 UTC
