### ISSUE TITLE
BackgroundJob store error

### ISSUE THREAD

**Issue by SarcoZ** [abpframework/abp#867] opened 2019-03-11 11:20 UTC
when I use Volo.Abp.BackgroundJobs.MongoDB as BackgroundJobs store, record can write to mongo,but job status flush to mongo cause error:
Database operation expected to affect 1 row but actually affected 0 row. Data may have been modified or deleted since entities were loaded. This exception has been thrown on optimistic concurrency check.

````csharp
    /// <summary>
    /// Represents a background job info that is used to persist jobs.
    /// </summary>
    public class BackgroundJobInfo
    {
        public Guid Id { get; set; }

        /// <summary>
        /// Type of the job.
        /// It's AssemblyQualifiedName of job type.
        /// </summary>
        public virtual string JobName { get; set; }

        /// <summary>
        /// Job arguments as serialized to string.
        /// </summary>
        public virtual string JobArgs { get; set; }
````

JobName is job type ,but Volo.Abp.BackgroundJobs.MongoDB store args name as JobName

**Comment by SarcoZ** [comment] 2019-03-11 11:31
public virtual async Task<string> EnqueueAsync<TArgs>(TArgs args, BackgroundJobPriority priority = BackgroundJobPriority.Normal, TimeSpan? delay = null)
        {
            var jobName = BackgroundJobNameAttribute.GetName<TArgs>();
            var jobId = await EnqueueAsync(jobName, args, priority, delay);
            return jobId.ToString();
        }

I find code,this api use BackgroundJobNameAttribute as job name,I try later again

**Comment by hikalkan** [comment] 2019-06-16 20:44
JobName is not assembly qualified name.  `BackgroundJobNameAttribute.GetName` is the true implementation. I will fix the property summary.

**Comment by hikalkan** [comment] 2019-06-16 20:50
@maliming can you test this? You can temporary change [Volo.Abp.BackgroundJobs.DemoApp](https://github.com/abpframework/abp/tree/master/modules/background-jobs/app/Volo.Abp.BackgroundJobs.DemoApp) project to use MongoDB and see if it works.

**Comment by maliming** [comment] 2019-06-17 01:12
ok, I will check it out.

**Comment by maliming** [comment] 2019-06-17 03:47
@SarcoZ 
Didn't reproduce the problem you mentioned, can you provide some steps?

> Database operation expected to affect 1 row but actually affected 0 row. Data may have been modified or deleted since entities were loaded. This exception has been thrown on optimistic concurrency check.

This seems to be a unique error of EF.

**Comment by hikalkan** [comment] 2019-06-17 05:34
Closing this. Please reopen if you have it again.

**Closed** 2019-11-12 11:48 UTC
Labels: problem
