### ISSUE TITLE
Oracle 11g: the identifier name can not more than 30 characters

### ISSUE THREAD

**Issue by jack-gaojz** [abpframework/abp#2704] opened 2020-01-22 23:29 UTC
When I use the Oracle 11g to generate the database, the error message as below:
'Column name 'AlwaysIncludeUserClaimsInIdToken' in table "IdentityServerClients" is too long (32 characters). An identifier with more than 30 characters was specified.'

**Comment by maliming** [comment] 2020-01-23 00:42
Duplicate of #1920

**Closed by maliming** 2020-01-23 00:42 UTC

**Comment by Monodytheone** [comment] 2024-04-25 13:36
@jack-gaojz-zz  Could you please explain your solution to me? I'm unable to understand it just from issue #1920 . I would greatly appreciate.
