### ISSUE TITLE
Client permissions check fail

### ISSUE THREAD

**Issue by EpsilonRepo** [abpframework/abp#2800] opened 2020-02-10 17:13 UTC
Hi,

I try to Authorize my api endpoints but the client permissions aren't loaded properly. 
I could set them through the web application and find them in the AbpPermissionGrants table.

When they get loaded, I see that the providerKey used in the query is the client_id, instead of the generated guid that is stored in the the table (and visible in the web interface).
Of course, it can't find the grants, what am I doing wrong?

Thank you and best regards,

**Comment by maliming** [comment] 2020-02-14 05:42
hi

Is your project tiered?

Please share some screenshots and code to explain your problem.

**Comment by EpsilonRepo** [comment] 2020-02-14 14:21
Hi,

Yes the project is tiered. I just try to access my api endpoints with postman.
Without permissions, it works fine.

But when I add the `[Authorize]` header and set permissions on the client (see printscreen below) I get a 403.

![image](https://user-images.githubusercontent.com/5107594/74538307-3be95180-4f3c-11ea-8bd9-fee1018d2d95.png)

In the log file I can see that the database request to check the permissions is wrong:

SELECT a.Id, a.Name, a.ProviderKey, a.ProviderName, a.TenantId
FROM AbpPermissionGrants a
WHERE (0= 1) OR a.TenantId IS NULL) AND (((a.Name = 'Parking.Handlers') AND (a.ProviderName = 'C')) AND (a.ProviderKey = '**MyClientId**'))
FETCH FIRST 1 ROWS ONLY

ProviderKey in the Database is **995ee703-ddc1-d7cd-995f-39f3271281d4** not **MyClientId**

**Comment by maliming** [comment] 2020-02-17 02:11
Can you provide steps for me to reproduce your problem? :)

**Comment by EpsilonRepo** [comment] 2020-02-17 07:07
1. Create a controller
2. Add new PermissionDefinition
3. Add corresponding [Authorize] attribute on controller method
4. Give permissions through angular app (Administration/Identity Server/Clients/Manage Permissions)
5. Call the service 

--> 403

**Comment by maliming** [comment] 2020-02-17 07:59
hi @EpsilonRepo

Please share the detailed steps, **starting with creating a project using cli.**
Because I need to reproduce the problem. Thanks!

**Comment by EpsilonRepo** [comment] 2020-02-17 09:51
Hi,

 I really did nothing more that what I described.
1. Created a new project with: `abp new Debug.Apb -t app-pro -u angular --tiered`
2. Added this line to my PermissionDefinitionProvider: `myGroup.AddPermission(ApbProPermissions.Dashboard.Debug, L("Permission:Debug"));`
3. add new Controller
` [RemoteService]
    [Authorize(ApbProPermissions.Dashboard.Debug)]
    public class SystemController : AbpController
    {
        [HttpGet]
        [Route("hello")]
        public async Task<string> GetHelloAsync()
        {
            return "Hello";
        }
    }`

4. Then I give the newly created permission to the client used to get the token through the angular client.

Results in a 403

**Comment by maliming** [comment] 2020-02-17 10:08
I know your situation now, I will check it,

**Comment by maliming** [comment] 2020-02-17 13:00
hi @mehmet-erim 

Here `clientId `should be used instead of `id`.

https://github.com/volosoft/volo/blob/dev/abp/npm/ng-packs/packages/identity-server/src/lib/components/clients/clients.component.html#L77

**Comment by maliming** [comment] 2020-02-18 06:14
Version 2.1 will fix this problem and will be released around February 20.

**Closed by maliming** 2020-02-18 06:14 UTC
Labels: problem
