### ISSUE TITLE
Mysql：Specified key was too long; max key length is 3072 bytes

### ISSUE THREAD

**Issue by 344089386** [abpframework/abp#2058] opened 2019-11-01 08:28 UTC
This error occurs when the length of a string type primary key is added to exceed 768.

Failed executing DbCommand (46ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE `IdentityServerClientSecrets` (
    `Type` varchar(250) NOT NULL,
    `Value` varchar(500) NOT NULL,
    `ClientId` char(36) NOT NULL,
    `Description` varchar(2000) NULL,
    `Expiration` datetime(6) NULL,
    CONSTRAINT `PK_IdentityServerClientSecrets` PRIMARY KEY (`ClientId`, `Type`, `Value`),
    CONSTRAINT `FK_IdentityServerClientSecrets_IdentityServerClients_ClientId` FOREIGN KEY (`ClientId`) REFERENCES `IdentityServerClients` (`Id`) ON DELETE CASCADE
);
MySql.Data.MySqlClient.MySqlException (0x80004005): Specified key was too long; max key length is 3072 bytes

36+250+500 > 768 。

**Comment by 344089386** [comment] 2019-11-01 08:30
As far as I know in Oracle foreign key names longer than a certain length are also reported incorrectly.
Such as: FK_IdentityServerClientScopes_IdentityServerClients_ClientId
I'm going to overestimate the length, although it's a very nice way to name it.

**Comment by maliming** [comment] 2019-11-01 08:33
Duplicate of https://github.com/abpframework/abp/issues/1920#issuecomment-543551659

**Closed by maliming** 2019-11-01 08:33 UTC

**Comment by 344089386** [comment] 2019-11-01 08:46
@maliming It's settled. Thank you
