### ISSUE TITLE
The 'new' and 'login' commands of Abp Cli throws exception

### ISSUE THREAD

**Issue by iyilm4z** [abpframework/abp#15747] opened 2023-02-19 23:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi, 
First of all, I hope this is not a duplicate issue and that I'm not spending your time on an already-known issue. I saw some similar issues to this but they were old ones. So I wanted to create a new issue.

Well... I'm just following the docs to create an ABP app and I got the exception logs below on the ss.

![image](https://user-images.githubusercontent.com/9105939/219982030-680f2cae-7d70-4a45-bb63-c906104df8ad.png)

I also can't log in to my ABP account and I got the exception logs below.
```
[02:34:02 INF] ABP CLI 7.0.1
[02:34:03 WRN] 1. HTTP request attempt failed to https://abp.io/api/license/check-multiple-organizations?username=iyilm4z with an error: An error occurred while sending the request.. Waiting 2 secs for the next try...
[02:34:05 WRN] 2. HTTP request attempt failed to https://abp.io/api/license/check-multiple-organizations?username=iyilm4z with an error: An error occurred while sending the request.. Waiting 4 secs for the next try...
[02:34:10 WRN] 3. HTTP request attempt failed to https://abp.io/api/license/check-multiple-organizations?username=iyilm4z with an error: An error occurred while sending the request.. Waiting 7 secs for the next try...
[02:34:17 ERR] An error occurred while sending the request.
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The read operation failed, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ReplyOnReAuthenticationAsync[TIOAdapter](Byte[] buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendAsync>g__Core|5_0(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendAsync>g__Core|5_0(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Volo.Abp.Cli.Http.CliHttpClientExtensions.<>c__DisplayClass1_0`1.<<GetHttpResponseMessageWithRetryAsync>b__2>d.MoveNext() in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Http\CliHttpClientExtensions.cs:line 81
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Volo.Abp.Cli.Http.CliHttpClientExtensions.GetHttpResponseMessageWithRetryAsync[T](HttpClient httpClient, String url, Nullable`1 cancellationToken, ILogger`1 logger, IEnumerable`1 sleepDurations) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Http\CliHttpClientExtensions.cs:line 58
   at Volo.Abp.Cli.Commands.LoginCommand.CheckMultipleOrganizationsAsync(String username) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\LoginCommand.cs:line 177
   at Volo.Abp.Cli.Commands.LoginCommand.HasMultipleOrganizationAndThisNotSpecified(CommandLineArgs commandLineArgs, String organization) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\LoginCommand.cs:line 113
   at Volo.Abp.Cli.Commands.LoginCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\LoginCommand.cs:line 58
   at Volo.Abp.Cli.CliService.RunInternalAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 168
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 76
```

### Reproduction Steps

-Run `abp new Acme.BookStore -dbms MySQL --theme basic ` command
-Run `abp login yourAbpUser -p yourAbpPass` command

### Expected behavior

-A new ABP project should be created.
-The abp.io registered user should log in. 

### Actual behavior

- The **new** command throws an exception.
- The **login** command also throws an exception.

### Known Workarounds

Using  ABP CLI 7.0.0

### Version

 ABP CLI 7.0.1(the latest)

### User Interface

MVC

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by maliming** [comment] 2023-02-20 01:41
hi

Can you try again?

It works for me now.

**Comment by iyilm4z** [comment] 2023-02-20 05:40
Hi @maliming,
I'm out of office and i'll check it asap. However could you please also check abp.io, I can't access it.

**Comment by maliming** [comment] 2023-02-20 05:44
https://downforeveryoneorjustme.com/abp.io

**Comment by iyilm4z** [comment] 2023-02-20 05:48
Currently, I'm using a mobile phone browser, probably it's related to it.

**Comment by iyilm4z** [comment] 2023-02-20 05:50
![image](https://user-images.githubusercontent.com/9105939/220020184-cf531d35-6551-4705-98e2-a9ea7516349b.jpeg)
![image](https://user-images.githubusercontent.com/9105939/220020211-ac60ca49-71a5-4d81-9bf5-128e3631a4f0.jpeg)

**Comment by iyilm4z** [comment] 2023-02-20 05:59
Btw, I tested it with someone else's mobile phone browser to check if it's related to my phone. But the same access issue seemed.

**Comment by maliming** [comment] 2023-02-20 06:16
I'm guessing it's a DNS issue.

<img width="395" alt="image" src="https://user-images.githubusercontent.com/6908465/220025593-280d2258-8c9c-4203-b215-202c390036a3.png">

**Comment by berkansasmaz** [comment] 2023-02-20 07:27
It works for me as well, FYI.

**Comment by iyilm4z** [comment] 2023-02-20 10:34
Unfortunately, The result is the same with the "new" and "login" commands.
Do you have any recommendations?

**Comment by berkansasmaz** [comment] 2023-02-20 11:03
It's hard to say for sure as we couldn't reproduce the problem. However, when you open your mobile hotspot and connect from your computer, you can try if anything changes in the result to identify the problem.

**Comment by salihozkara** [comment] 2023-02-20 15:47
If you cannot access abp.io from your browser, I suspect it may not work in your CLI either. If there is a DNS error on your browser, I suggest changing your computer's DNS settings. My recommendation is to use Google's DNS settings.

**Comment by berkansasmaz** [comment] 2023-02-21 09:04
Closing the issue. Feel free to re-open or create a new issue if you have further questions.

**Closed as completed by berkansasmaz** 2023-02-21 09:04 UTC

**Comment by iyilm4z** [comment] 2023-04-23 21:07
Hello again, 
Actually, this problem was still occurring to me, but I didn't want to bother you because I understood it was related to my environment. Finally, I found that the problem was with enabling TLS 1.3 in Windows 10. Disabling TLS 1.3 fixed the issue. 
I wanted to share this with the community and other potential people who might have the same issue, thanks.
