### ISSUE TITLE
Import excel data abp framework

### ISSUE THREAD

**Issue by slm-w** [abpframework/abp#7199] opened 2021-01-13 21:22 UTC
Hello

Does abp have import data from excel example ?

Thank you.

**Comment by davidzwa** [comment] 2021-01-13 21:37
Duplicate of https://github.com/abpframework/abp/issues/6987
For the rest I've implemented it using a csv importer library called `CsvHelper`. The rest is up to you until the example is published.

**Closed as completed** 2021-01-14 01:27 UTC
