### ISSUE TITLE
I can not use AbpCachingStackExchangeRedisModule with redis-server 3.0.504 for windows

### ISSUE THREAD

**Issue by xdqa01** [abpframework/abp#12199] opened 2022-04-07 03:03 UTC
When i use any code to set a cache to redis ,there is an error 'StackExchange.Redis.RedisServerException: ERR Error running script (call to f_3915ee22fda531a1d5661f2523d0443fd35ff0a4): @user_script:2: @user_script: 2: Wrong number of args calling Redis command From Lua script'.
Abp version :5.2.0
dotnet:6.0
Redis:3.0.504
Configure:`  
"Redis": {
    "IsEnabled": true,
    "Configuration": "127.0.0.1:63791,password=*******,defaultDatabase=1"
  },
`
Code:
`
[DependsOn(typeof(AbpCachingStackExchangeRedisModule))]
public class GSHostSharedModule : AbpModule
{
     public override Task OnPostApplicationInitializationAsync(ApplicationInitializationContext context)
  {
    var cache = context.ServiceProvider.GetRequiredService<IDistributedCache<string,string>>();
    cache.Set("Hello", "world!");
    return base.OnPostApplicationInitializationAsync(context);
  }
}
`

**Comment by xdqa01** [comment] 2022-04-07 03:06
When i use StackExchange.Redis ,it has no error.
`
using var con= ConnectionMultiplexer.Connect("127.0.0.1:63791,password=*******,defaultDatabase=1");
var db=con.GetDatabase(1);
db.SetAdd("Hello", "world!");
Console.WriteLine("Hello, World!");
`

**Comment by maliming** [comment] 2022-04-07 03:15
Duplicate of #12150

**Closed as completed by maliming** 2022-04-07 03:15 UTC
