### ISSUE TITLE
Any React sample?

### ISSUE THREAD

**Issue by HappyNinja2** [abpframework/abp#9135] opened 2021-05-22 23:27 UTC
Is there any plan to release a React sample to be used as the front end? I find it hard to re-write the front end from angular since some auth packages are not included. It would be wise to focus on React since it has gained more popularity than angular as well

**Comment by maliming** [comment] 2021-05-23 03:55
Duplicate of #1638

**Closed as completed by maliming** 2021-05-23 03:55 UTC

**Comment by tudoujun43** [comment] 2021-05-27 06:23
[react template](https://github.com/potatoabp/abp-vnext-react)
