### ISSUE TITLE
CLI 2.0: abp new command failed

### ISSUE THREAD

**Issue by wakuflair** [abpframework/abp#2630] opened 2020-01-14 02:47 UTC
![image](https://user-images.githubusercontent.com/3471718/72309778-e0b50c80-36ba-11ea-92d0-472a2ffce0fc.png)

Is this a bug or the CLI won't be available in the community edition anymore?

**Comment by maliming** [comment] 2020-01-14 03:08
hi @ebicoglu
Can you help explain this?
https://github.com/abpframework/abp/commit/a4e20048afff06b9bb3006e936f4e9b3a1d7f9ff#diff-50feea38706bda8de3534ad632148050R87-R90

**Comment by yekalkan** [comment] 2020-01-14 06:18
> Is this a bug or the CLI won't be available in the community edition anymore?

It's a bug or misimplemented code.

also, duplicate of https://github.com/abpframework/abp/issues/2626

**Closed** 2020-01-14 06:18 UTC
