### ISSUE TITLE
Language Management 

### ISSUE THREAD

**Issue by recruitans** [abpframework/abp#7793] opened 2021-02-21 08:45 UTC
![2021-02-21_11-42-22](https://user-images.githubusercontent.com/28866278/108620054-4df8ac80-743a-11eb-90ec-73fbe4e10c23.jpg)

**Comment by maliming** [comment] 2021-02-22 03:32
Have you tried to refresh the page?

**Comment by recruitans** [comment] 2021-02-22 11:52
Yes. I experienced this situation when I first logged in after the change in languages. Then it worked properly. I did not understand.

**Comment by ebicoglu** [comment] 2021-02-22 15:28
if we cannot reproduce, I'll close the issue?

**Closed as completed** 2021-02-23 00:53 UTC

**Comment by recruitans** [comment] 2021-02-23 14:13
still going on...
![image](https://user-images.githubusercontent.com/28866278/108855786-69aab100-75fa-11eb-86e5-895804574c48.png)
