### ISSUE TITLE
BookStore Sample - Roles\index.js error TypeError: Cannot read property 'identityRole' of undefined

### ISSUE THREAD

**Issue by 274188A** [abpframework/abp#2173] opened 2019-11-15 02:42 UTC
I have fetched code up to latested : `e597d1e - Merge pull request #2172 from cnAbp/Translate`

Steps
1. dotnet clean
2. dotnet build
3. start debugging 
4. Login
5. Navigate to Roles using menu

Expected Result: see a list of Roles
Actual Result:

![image](https://user-images.githubusercontent.com/40014477/68912758-18273b80-0794-11ea-8df1-ceef0af0b826.png)

**Comment by maliming** [comment] 2019-11-15 03:02
Duplicate of #1991

**Closed by maliming** 2019-11-15 03:02 UTC

**Comment by 274188A** [comment] 2019-11-15 03:04
why close?  dotnet clean, dotnet build which did resolve 1991, does not resolve this issue

**Comment by 274188A** [comment] 2019-11-15 03:04
i have tried different browsers as well - same error.
