### ISSUE TITLE
Row Level Authorization

### ISSUE THREAD

**Issue by gdirikgil** [abpframework/abp#7392] opened 2021-01-21 18:28 UTC
Will Abp supports row level authorization in the future?
I mean I want to restrict access to the rows of one or more entities based on the rights or the role of the current user.

**Comment by realLiangshiwei** [comment] 2021-01-22 01:22
Duplicate of https://github.com/abpframework/abp/issues/236

**Closed as completed by realLiangshiwei** 2021-01-22 01:22 UTC

**Comment by gdirikgil** [comment] 2021-01-24 05:57
Could you give me the of link of duplicated issue?

**Comment by realLiangshiwei** [comment] 2021-01-24 09:30
See https://github.com/abpframework/abp/issues/236
