### ISSUE TITLE
Duplicate records getting created or internal error shows in abp.io .netcore + angular template

### ISSUE THREAD

**Issue by vineethjvenattu** [abpframework/abp#2065] opened 2019-11-02 17:52 UTC
I'm new to abp.io and created a new project using abp cli with angular front-end. After logged in using admin, I started by adding a tenant and it started creating the tenant twice or it is throwing internal error. I believe it is due to multiple create request happening from the angular ui part. Screenshots are provided below. Please help!!!

![Screenshot (1)](https://user-images.githubusercontent.com/23413508/68074966-9adced80-fdc7-11e9-9f17-f76171ec66e0.png)
![Screenshot (2)](https://user-images.githubusercontent.com/23413508/68074967-9adced80-fdc7-11e9-8ab2-63abd689d8e7.png)
![Screenshot (3)](https://user-images.githubusercontent.com/23413508/68074965-9a445700-fdc7-11e9-965b-6fde88fa6a5d.png)

Gamma created twice and Test created once but the second request got some delay so it throws internal error 500.

**Comment by maliming** [comment] 2019-11-03 01:39
Duplicate of #2042

**Closed by maliming** 2019-11-03 01:39 UTC
