### ISSUE TITLE
Unexpected decrease of memory

### ISSUE THREAD

**Issue by xiangxingxing** [abpframework/abp#2889] opened 2020-02-22 13:37 UTC
With the update of abpframework recently,  I've attempt to upgrade the packages of abp to the latest version in our projects. A problem about memory was found during auto-tests.
1. The memory tends to be stable finally after handling various affairs

**Comment by acjh** [comment] 2020-02-22 14:28
Duplicate of #2891

**Closed by acjh** 2020-02-22 14:28 UTC
