### ISSUE TITLE
Automatic database generation for tenant with dedicated database in multitenant application

### ISSUE THREAD

**Issue by AppBotTech** [abpframework/abp#1925] opened 2019-10-16 11:56 UTC
It seems that ABP vNext makes provision for specifying a connection string for a new tenant when creating a tenant via a ASP.Net Core 3, EF Core, Angular startup template. 

After the connection string is specified for the specific tenant, the database is not automatically created and seeded as is currently the case with ASP.Net Boilerplate. I am missing something or will this feature only be available in the version 1 release of ABP vNext?

**Comment by hikalkan** [comment] 2019-10-17 16:11
We haven't implemented this yet. However, this code is not in the framework, but in the startup template. You can change the code you already have to add the behavior.

This is duplicate of https://github.com/abpframework/abp/issues/1371

**Closed by hikalkan** 2019-10-17 16:11 UTC
