### ISSUE TITLE
how to debug into abp source code when reference abp in my own project?

### ISSUE THREAD

**Issue by derily** [abpframework/abp#2580] opened 2020-01-08 09:13 UTC

**Comment by derily** [comment] 2020-01-08 09:15
any one can help me ,many thanks !!^_^

**Comment by maliming** [comment] 2020-01-08 09:24
Duplicate of #1039

**Closed by maliming** 2020-01-08 09:24 UTC

**Comment by gdlcf88** [comment] 2020-01-08 09:47
IDE recommendation: Jetbrains Rider. 😃 
You can debug into abp framework without any configuration, and it is better than VS in performance.
