### ISSUE TITLE
bugs in the identity module?

### ISSUE THREAD

**Issue by zsanhong** [abpframework/abp#2859] opened 2020-02-19 08:25 UTC
when I click the Identity/Roles page of Action button ,I can't see the drop menu ,like this:
![action](https://user-images.githubusercontent.com/5259153/74815251-dc23e980-5333-11ea-8dc8-20dcd1e0e752.png)
but when I use my own page, I can see the drop menu like this:
![myaction](https://user-images.githubusercontent.com/5259153/74815481-46d52500-5334-11ea-9a45-409767ea85f6.png)

so , is this a bug?

**Comment by maliming** [comment] 2020-02-19 08:32
Duplicate of #2710

**Closed by maliming** 2020-02-19 08:32 UTC
