### ISSUE TITLE
  Doc Module Is Incomplete

### ISSUE THREAD

**Issue by pranavpatil19** [abpframework/abp#2876] opened 2020-02-21 05:15 UTC
https://docs.abp.io/en/abp/latest/Modules/Docs

I done Process till 6 step. In Step 7 not mension whrere create .md file and write code in taht.

 after click on document local file and git file i got 400 errror please help

**Comment by maliming** [comment] 2020-02-21 05:25
Duplicate of #2864

**Closed by maliming** 2020-02-21 05:25 UTC
