### ISSUE TITLE
Show "Preview" on the version list in the docs module

### ISSUE THREAD

**Issue by hikalkan** [abpframework/abp#5934] opened 2020-10-25 16:20 UTC
For example, we should show `3.3 (preview)` in the image below, instead of `3.3`

![image](https://user-images.githubusercontent.com/1210527/97112740-044fbd80-16f7-11eb-9137-18096477288c.png)

**Comment by yekalkan** [comment] 2020-10-26 07:54
duplicate of https://github.com/abpframework/abp/issues/5562

**Closed as completed by yekalkan** 2020-10-26 07:54 UTC
Labels: duplicate
