### ISSUE TITLE
ServiceProxyScript Takes forever to respond....and crashes eventually.

### ISSUE THREAD

**Issue by SoloHam** [abpframework/abp#3363] opened 2020-03-25 21:16 UTC
I have an EmployeeAppService with the following method:

public List<Employee_Dto> GetAllEmployees(Func<Employee, bool> Selector = null)
{

            var result = Repository.WithDetails().Where(Selector ?? new Func<Employee, bool>(x => true));

            return result.Select(MapToGetListOutputDto).ToList();

        }

Removing the Func<> parameter fixes everything but with that the GET request to ServiceProxyScript (Sent on nearly every page and on app initiation by the framework (obvio)) takes ages and never responds.

Please look into this.

**Comment by liangshiw** [comment] 2020-03-26 00:42
Check your logs. In addition, cannot be used `Func<Employee, bool>` as a parameter

**Comment by SoloHam** [comment] 2020-03-26 00:54
Why can't it be?. I mean it works but causes the ServiceProxy a headache.
I've checked the logs, can't seem to find the issue there, here they are:

  ``` 
```

**Comment by liangshiw** [comment] 2020-03-26 05:24
Because AspNetCore does not support delegate types as parameters. You can try with a simple webapi project(of course it is not feasible).

**Comment by maliming** [comment] 2020-03-26 05:51
Duplicate of https://github.com/abpframework/abp/issues/2174

**Closed by maliming** 2020-03-26 05:51 UTC
