### ISSUE TITLE
Is there a way to merge api-definition for micro services?

### ISSUE THREAD

**Issue by lht6** [abpframework/abp#10475] opened 2021-10-29 07:10 UTC
I use Ocelot as gateway for two micro services behind. I guess the idea way is to request API-definition to gateway, like https://{gateway-host}/api/abp/api-definition, and the gateway will get api-definition from micorserviceA and microserviceB and merge them before returning to client.
I wonder what would be the best way to achieve this? Should I write some codes in gateway to call micoservices to get api-definition, or is there some existing method I can use?  Thanks

**Comment by maliming** [comment] 2021-10-29 07:16
Duplicate of #9405

**Closed as completed by maliming** 2021-10-29 07:16 UTC
