### ISSUE TITLE
CLI abp udate logs an error error

### ISSUE THREAD

**Issue by sturlath** [abpframework/abp#7345] opened 2021-01-19 14:54 UTC
I had created a v4.2.0-rc.1 solution and now I want to try to update so I  ran `abp update` and get the error below

I can run the code and I can´t see that it affects anything but I thought you should know about it if you dont.

`[14:50:26 INF] Updating package "Volo.Abp.Authorization" from v4.2.0-rc.1 to v4.2.0-rc.2.
[14:50:26 INF] Volo packages are updated in EventOrganizer solution.
[14:50:26 INF] Checking installed npm global packages...
[14:50:31 ERR] One or more errors occurred. (Additional text encountered after finished reading JSON content: (. Path '', line 32, position 0.)
System.AggregateException: One or more errors occurred. (Additional text encountered after finished reading JSON content: (. Path '', line 32, position 0.)
 ---> Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: (. Path '', line 32, position 0.
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Volo.Abp.Cli.ProjectModification.NpmPackagesUpdater.GetPackageVersionList(JProperty package) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\NpmPackagesUpdater.cs:line 348
   at Volo.Abp.Cli.ProjectModification.NpmPackagesUpdater.GetLatestVersion(JProperty package, Boolean includeReleaseCandidates) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\NpmPackagesUpdater.cs:line 285
   at Volo.Abp.Cli.ProjectModification.NpmPackagesUpdater.TryUpdatingPackage(String filePath, JProperty package, Boolean includePreviews, Boolean includeReleaseCandidates, Boolean switchToStable, String specifiedVersion) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\NpmPackagesUpdater.cs:line 246
   at Volo.Abp.Cli.ProjectModification.NpmPackagesUpdater.UpdatePackagesInFile(String filePath, Boolean includePreviews, Boolean includeReleaseCandidates, Boolean switchToStable, String specifiedVersion) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\NpmPackagesUpdater.cs:line 196
   at Volo.Abp.Cli.ProjectModification.NpmPackagesUpdater.<>c__DisplayClass11_0.<<Update>g__UpdateAsync|0>d.MoveNext() in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\NpmPackagesUpdater.cs:line 57
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Volo.Abp.Cli.ProjectModification.NpmPackagesUpdater.Update(String rootDirectory, Boolean includePreviews, Boolean includeReleaseCandidates, Boolean switchToStable, String version)
   at Volo.Abp.Cli.Commands.UpdateCommand.UpdateNpmPackages(String directory, String version) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\UpdateCommand.cs:line 52
   at Volo.Abp.Cli.Commands.UpdateCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\UpdateCommand.cs:line 46
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 59
PM> `

**Comment by ilkayilknur** [comment] 2021-01-19 16:18
I'm not able to reproduce the issue. Can you try again and let us know if the problem still exists?

**Comment by sturlath** [comment] 2021-01-20 08:41
I just created a brand new project `abp new BlazorCLITest -o BlazorCLITest -u blazor` and just ran the update `abp update` and I get the following. 

`[08:37:46 INF] ABP CLI (https://abp.io)
[08:37:47 INF] Version 4.1.2 (Stable)
[08:37:49 INF] Package: "Volo.Abp.Account.Application-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.Identity.Application-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.PermissionManagement.Application-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.TenantManagement.Application-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.FeatureManagement.Application-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.ObjectExtending-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.Account.Application.Contracts-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.Identity.Application.Contracts-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.PermissionManagement.Application.Contracts-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.TenantManagement.Application.Contracts-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.FeatureManagement.Application.Contracts-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.Autofac.WebAssembly-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.AspNetCore.Components.WebAssembly.BasicTheme-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.Identity.Blazor-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.TenantManagement.Blazor-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.Autofac-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.Emailing-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.Identity.Domain-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.PermissionManagement.Domain.Identity-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.IdentityServer.Domain-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.PermissionManagement.Domain.IdentityServer-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.BackgroundJobs.Domain-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.AuditLogging.Domain-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.TenantManagement.Domain-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.FeatureManagement.Domain-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.SettingManagement.Domain-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.Identity.Domain.Shared-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.IdentityServer.Domain.Shared-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.BackgroundJobs.Domain.Shared-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.AuditLogging.Domain.Shared-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.TenantManagement.Domain.Shared-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.FeatureManagement.Domain.Shared-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.PermissionManagement.Domain.Shared-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.SettingManagement.Domain.Shared-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.EntityFrameworkCore.SqlServer-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.PermissionManagement.EntityFrameworkCore-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.SettingManagement.EntityFrameworkCore-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.Identity.EntityFrameworkCore-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.IdentityServer.EntityFrameworkCore-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.BackgroundJobs.EntityFrameworkCore-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.AuditLogging.EntityFrameworkCore-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.TenantManagement.EntityFrameworkCore-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.FeatureManagement.EntityFrameworkCore-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.Account.HttpApi-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.Identity.HttpApi-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.PermissionManagement.HttpApi-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.TenantManagement.HttpApi-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.FeatureManagement.HttpApi-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.Account.HttpApi.Client-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.Identity.HttpApi.Client-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.PermissionManagement.HttpApi.Client-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.TenantManagement.HttpApi.Client-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.FeatureManagement.HttpApi.Client-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.AspNetCore.MultiTenancy-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.Autofac-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.AspNetCore.Authentication.JwtBearer-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.AspNetCore.Serilog-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.Swashbuckle-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.Account.Web.IdentityServer-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.EntityFrameworkCore.Sqlite-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.Http.Client.IdentityModel-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.TestBase-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.Autofac-v4.1.2" is up to date.
[08:37:49 INF] Package: "Volo.Abp.Authorization-v4.1.2" is up to date.
[08:37:49 INF] Volo packages are updated in BlazorCLITest solution.
[08:37:49 INF] Checking installed npm global packages...
[08:37:52 ERR] One or more errors occurred. (Additional text encountered after finished reading JSON content: (. Path '', line 32, position 0.)
System.AggregateException: One or more errors occurred. (Additional text encountered after finished reading JSON content: (. Path '', line 32, position 0.)
 ---> Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: (. Path '', line 32, position 0.
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Volo.Abp.Cli.ProjectModification.NpmPackagesUpdater.GetPackageVersionList(JProperty package) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\NpmPackagesUpdater.cs:line 348
   at Volo.Abp.Cli.ProjectModification.NpmPackagesUpdater.GetLatestVersion(JProperty package, Boolean includeReleaseCandidates) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\NpmPackagesUpdater.cs:line 285
   at Volo.Abp.Cli.ProjectModification.NpmPackagesUpdater.TryUpdatingPackage(String filePath, JProperty package, Boolean includePreviews, Boolean includeReleaseCandidates, Boolean switchToStable, String specifiedVersion) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\NpmPackagesUpdater.cs:line 250
   at Volo.Abp.Cli.ProjectModification.NpmPackagesUpdater.UpdatePackagesInFile(String filePath, Boolean includePreviews, Boolean includeReleaseCandidates, Boolean switchToStable, String specifiedVersion) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\NpmPackagesUpdater.cs:line 196
   at Volo.Abp.Cli.ProjectModification.NpmPackagesUpdater.<>c__DisplayClass11_0.<<Update>g__UpdateAsync|0>d.MoveNext() in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\NpmPackagesUpdater.cs:line 57
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Volo.Abp.Cli.ProjectModification.NpmPackagesUpdater.Update(String rootDirectory, Boolean includePreviews, Boolean includeReleaseCandidates, Boolean switchToStable, String version)
   at Volo.Abp.Cli.Commands.UpdateCommand.UpdateNpmPackages(String directory, String version) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\UpdateCommand.cs:line 52
   at Volo.Abp.Cli.Commands.UpdateCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\UpdateCommand.cs:line 46
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 59

C:\Dev\BlazorCLITest>`

**Comment by ilkayilknur** [comment] 2021-01-20 11:38
It could be related to `npm`. Can you take a look at this, please? @yekalkan

**Comment by yekalkan** [comment] 2021-01-20 11:49
I'm not able to reproduce as well.

@sturlath Can you run `npm show @abp/aspnetcore.mvc.ui.theme.basic versions` command (in any directory) and show the result?

**Comment by sturlath** [comment] 2021-01-20 13:18
Here the result

C:\Dev\BlazorCLITest>npm` show @abp/aspnetcore.mvc.ui.theme.basic versions
(node:41812) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

[
  '0.2.0',                 '0.2.1',      '0.2.2',
  '0.2.3',                 '0.3.0',      '0.3.1',
  '0.3.2',                 '0.3.4',      '0.3.5',
  '0.4.1',                 '0.4.3',      '0.4.4',
  '0.4.7',                 '0.4.8',      '0.4.9',
  '0.5.3',                 '0.6.1',      '0.6.2',
  '0.6.3',                 '0.6.4',      '0.6.5',
  '0.6.6',                 '0.7.6',      '0.8.0',
  '0.9.0',                 '0.9.2',      '1.0.0',
  '1.0.2',                 '1.0.3',      '1.1.0',
  '1.1.1',                 '2.0.0',      '2.0.1',
  '2.1.0-preview20200213', '2.1.0',      '2.2.0',
  '2.3.0',                 '2.4.0',      '2.4.1',
  '2.5.0',                 '2.6.0',      '2.6.1',
  '2.6.2',                 '2.7.0',      '2.8.0',
  '2.9.0',                 '3.0.0',      '3.0.1',
  '3.0.2',                 '3.0.3',      '3.0.4',
  '3.0.5',                 '3.1.0-rc.1', '3.1.0-rc.2',
  '3.1.0-rc.3',            '3.1.0-rc.4', '3.1.0',
  '3.1.1',                 '3.1.2',      '3.2.0-rc.1',
  '3.2.0-rc.2',            '3.2.0',      '3.2.1',
  '3.3.0-rc.1',            '3.3.0-rc.2', '3.3.0',
  '3.3.1',                 '3.3.2',      '4.0.0-rc.1',
  '4.0.0-rc.2',            '4.0.0-rc.3', '4.0.0-rc.4',
  '4.0.0-rc.5',            '4.0.0',      '4.0.1',
  '4.0.2',                 '4.1.0-rc.1', '4.1.0-rc.2',
  '4.1.0',                 '4.1.1',      '4.1.2',
  '4.2.0-rc.1',            '4.2.0-rc.2'
]

**Comment by yekalkan** [comment] 2021-01-20 13:37
@sturlath i see. You have to remove `(node:41812)` warning. (Warning itself doesn't matter btw, but it prevents CLI from reading the version list.)

Can you try `npm show @abp/aspnetcore.mvc.ui.theme.basic versions --loglevel=error` ?

**Comment by sturlath** [comment] 2021-01-20 13:48
The same message I think. But how do I remove this error btw?

C:\Dev\BlazorCLITest>npm show @abp/aspnetcore.mvc.ui.theme.basic versions --loglevel=error
(node:13868) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

[
  '0.2.0',                 '0.2.1',      '0.2.2',
  '0.2.3',                 '0.3.0',      '0.3.1',
  '0.3.2',                 '0.3.4',      '0.3.5',
  '0.4.1',                 '0.4.3',      '0.4.4',
  '0.4.7',                 '0.4.8',      '0.4.9',
  '0.5.3',                 '0.6.1',      '0.6.2',
  '0.6.3',                 '0.6.4',      '0.6.5',
  '0.6.6',                 '0.7.6',      '0.8.0',
  '0.9.0',                 '0.9.2',      '1.0.0',
  '1.0.2',                 '1.0.3',      '1.1.0',
  '1.1.1',                 '2.0.0',      '2.0.1',
  '2.1.0-preview20200213', '2.1.0',      '2.2.0',
  '2.3.0',                 '2.4.0',      '2.4.1',
  '2.5.0',                 '2.6.0',      '2.6.1',
  '2.6.2',                 '2.7.0',      '2.8.0',
  '2.9.0',                 '3.0.0',      '3.0.1',
  '3.0.2',                 '3.0.3',      '3.0.4',
  '3.0.5',                 '3.1.0-rc.1', '3.1.0-rc.2',
  '3.1.0-rc.3',            '3.1.0-rc.4', '3.1.0',
  '3.1.1',                 '3.1.2',      '3.2.0-rc.1',
  '3.2.0-rc.2',            '3.2.0',      '3.2.1',
  '3.3.0-rc.1',            '3.3.0-rc.2', '3.3.0',
  '3.3.1',                 '3.3.2',      '4.0.0-rc.1',
  '4.0.0-rc.2',            '4.0.0-rc.3', '4.0.0-rc.4',
  '4.0.0-rc.5',            '4.0.0',      '4.0.1',
  '4.0.2',                 '4.1.0-rc.1', '4.1.0-rc.2',
  '4.1.0',                 '4.1.1',      '4.1.2',
  '4.2.0-rc.1',            '4.2.0-rc.2'
]


C:\Dev\BlazorCLITest>

**Comment by yekalkan** [comment] 2021-01-20 14:19
> @sturlath But how do I remove this error btw?

I don't know. I've made CLI ignore them, this issue will be fixed in v4.2.0.

**Comment by ebicoglu** [comment] 2021-01-21 15:50
https://github.com/abpframework/abp/pull/7361/files must fix it

**Closed as completed by ebicoglu** 2021-01-21 15:50 UTC
Labels: problem, effort-1, abp-cli
