### ISSUE TITLE
ngbDatepicker is not working

### ISSUE THREAD

**Issue by cbaille** [abpframework/abp#10767] opened 2021-11-29 06:51 UTC
ABP Framework version: 5.0.0-rc1
User Interface: Angular
database provider: EF Core

1- Create a new solution

2- Create an entity with a field on type DateTime

When you open the view of the entity, either on the filter area or on the modal view to create record, the DateTime ngbDatepicker is not working

![image](https://user-images.githubusercontent.com/27866600/143820283-cce6647c-2b66-4009-9a34-6b0c48245db6.png)

When click on the element, I get the error `ERROR TypeError: componentFactory.create is not a function`

![image](https://user-images.githubusercontent.com/27866600/143820527-c50218c9-27c6-4471-b736-29ee8a368d1b.png)

**Comment by cbaille** [comment] 2021-11-29 06:54
Maybe same issue as this one? 

https://github.com/abpframework/abp/issues/10743

**Comment by bnymncoskuner** [comment] 2021-11-29 07:26
@cbaille yes it's the same issue. We are working on it. I'll close this one.

**Comment by bnymncoskuner** [comment] 2021-11-29 07:26
Duplicate of #10743

**Closed as completed by bnymncoskuner** 2021-11-29 07:26 UTC
