### ISSUE TITLE
v7.1.1 gives AbpException: Could not find the bundle file '/libs/flag-icon-css/css/flag-icons.min.css' for the bundle 'Blazor.LeptonXTheme.Global'!

### ISSUE THREAD

**Issue by brauerj-gc** [abpframework/abp#16303] opened 2023-04-18 21:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

ABP Framework version: Upgrade from v7.0.3 to v7.1.1

UI type: Blazor Server

After upgrade I receive the error message:

AbpException: Could not find the bundle file '/libs/flag-icon-css/css/flag-icons.min.css' for the bundle 'Blazor.LeptonXTheme.Global'!
Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpTagHelperResourceService.ProcessAsync(ViewContext viewContext, TagHelper tagHelper, TagHelperContext context, TagHelperOutput output, List<BundleTagHelperItem> bundleItems, string bundleName)
Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpBundleTagHelperService<TTagHelper, TService>.ProcessAsync(TagHelperContext context, TagHelperOutput output)
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, int i, int count)
GcIprs.Main.Blazor.Pages.Pages__Host.<ExecuteAsync>b__16_0() in _Host.cshtml
+
<abp-style-bundle name="@BlazorLeptonXThemeBundles.Styles.Global" />
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
GcIprs.Main.Blazor.Pages.Pages__Host.ExecuteAsync() in _Host.cshtml
+
<html lang="@CultureInfo.CurrentCulture.Name" dir="@rtl">
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)

### Reproduction Steps

abp new Acme.BookStore -t app-pro -u blazor-server

Then run the app

### Expected behavior

It should run

### Actual behavior

AbpException: Could not find the bundle file '/libs/flag-icon-css/css/flag-icons.min.css' for the bundle 'Blazor.LeptonXTheme.Global'!
Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpTagHelperResourceService.ProcessAsync(ViewContext viewContext, TagHelper tagHelper, TagHelperContext context, TagHelperOutput output, List<BundleTagHelperItem> bundleItems, string bundleName)
Volo.Abp.AspNetCore.Mvc.UI.Bundling.TagHelpers.AbpBundleTagHelperService<TTagHelper, TService>.ProcessAsync(TagHelperContext context, TagHelperOutput output)
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, int i, int count)

### Regression?

7.0.3 worked fine

### Known Workarounds

unknown

### Version

7.1.1 and 7.2.0-rc

### User Interface

Blazor Server

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by brauerj-gc** [comment] 2023-04-18 21:55
also running abp update I get:

Could not parse package "Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonX" version v2.1.*-*. Skipped.
Could not parse package "Volo.Abp.AspNetCore.Components.Server.LeptonXTheme" version v2.1.*-*. Skipped.

**Comment by brauerj-gc** [comment] 2023-04-18 21:57
[3/4] Linking dependencies...
warning "@volo/abp.aspnetcore.mvc.ui.theme.leptonx > @volo/abp.aspnetcore.mvc.ui.theme.commercial > @abp/aspnetcore.mvc.ui.theme.shared > @abp/bootstrap > bootstrap@5.2.3" has unmet peer dependency "@popperjs/core@^2.11.6".
warning "@volo/abp.aspnetcore.mvc.ui.theme.leptonx > @volo/abp.aspnetcore.mvc.ui.theme.commercial > @abp/aspnetcore.mvc.ui.theme.shared > @abp/jquery-validation-unobtrusive > @abp/jquery-validation > jquery-validation@1.19.5" has unmet peer dependency "jquery@^1.7 || ^2.0 || ^3.1".

**Comment by brauerj-gc** [comment] 2023-04-18 22:11
I get the same thing when I run abp new Acme.BookStore -u blazor-server

**Comment by brauerj-gc** [comment] 2023-04-18 22:30
doing "yarn add flag-icons" and changing abp.resourcemapping.js to the following and running abp install-libs fixes it but why is this needed?

module.exports = {
    aliases: {
        "@node_modules": "./node_modules",
        "@libs": "./wwwroot/libs"
    },
    clean: [
        "@libs",
        "!@libs/**/foo.txt"
    ],
    mappings: {
        "@node_modules/flag-icon-css/css/*.min.css": "@libs/flag-icon-css/css/",
    }
};

**Comment by EngincanV** [comment] 2023-04-19 05:34
Hi, what is your LeptonX Theme version?

**Comment by hitaspdotnet** [comment] 2023-04-19 08:47
`flag-icon-css` is renamed to `flag-icon` and the @abp/flag-icon-css doesn't have abp.resourcemapping.js for install-libs task. If you force to continue with @abp/flag-icon-css you need to create abp.resourcemapping.js manually at YouProjectRoot/node_modules/@abp/flag-icon-css with this content:
```js
module.exports = {
    mappings: {
        "@node_modules/flag-icon-css/css/*": "@libs/flag-icon-css/css",
        "@node_modules/flag-icon-css/flags/1x1/*": "@libs/flag-icon-css/flags/1x1"
    }
}
```

**Comment by brauerj-gc** [comment] 2023-04-19 11:10
But I didn’t make any changes. I just ran the template as is!  Why would I have this problem?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Mostafa F ***@***.***>
Sent: Wednesday, April 19, 2023 4:48:05 AM
To: abpframework/abp ***@***.***>
Cc: Brauer, Jonathan ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [abpframework/abp] v7.1.1 gives AbpException: Could not find the bundle file '/libs/flag-icon-css/css/flag-icons.min.css' for the bundle 'Blazor.LeptonXTheme.Global'! (Issue #16303)


flag-icon-css is renamed to flag-icon and the @abp/flag-icon-css doesn't have abp.resourcemapping.js for install-libs task. If you force to continue with @abp/flag-icon-css you need to create abp.resourcemapping.js manually at ***@***.***/flag-icon-css with this content:

module.exports = {
    mappings: {
        ***@***.***_modules/flag-icon-css/css/*": ***@***.***/flag-icon-css/css",
        ***@***.***_modules/flag-icon-css/flags/1x1/*": ***@***.***/flag-icon-css/flags/1x1"
    }
}

**Comment by brauerj-gc** [comment] 2023-04-19 11:43
here is my package.json this morning still having the problem:

{
  "version": "1.0.0",
  "name": "my-app",
  "private": true,
  "dependencies": {
    "@volo/abp.aspnetcore.mvc.ui.theme.leptonx": "~2.1.0",
    "@volo/account": "~7.2.0",
    "@volo/aspnetcore.components.server.leptonxtheme": "~2.1.0",
    "@volo/cms-kit-pro.admin": "~7.2.0",
    "@volo/language-management": "~7.2.0"
  }
}

**Comment by justinb9909** [comment] 2023-04-25 18:14
So as a new ABP user that can't generate a working startup project, what is the recommended course of action? Downgrade to 7.0.3?

**Comment by EngincanV** [comment] 2023-04-25 18:44
> So as a new ABP user that can't generate a working startup project, what is the recommended course of action? Downgrade to 7.0.3?

If you are creating a new startup template, you will not get any problems. Actually, this is also valid for older versions, the only problem is in v7.1.1. BTW, we have fixed the problem and you will not be effected by new versions.

**Comment by justinb9909** [comment] 2023-04-25 18:57
> If you are creating a new startup template, you will not get any problems. Actually, this is also valid for older versions, the only problem is in v7.1.1. BTW, we have fixed the problem and you will not be effected by new versions.

Unfortunately, that doesn't appear to be the case. I was experiencing the issue when creating a new startup template via v7.1.1 (how I found this post). I figured it was fixed in 7.2.0-rc.2 so I just tried the following:

abp suite remove
abp cli remove
dotnet tool install -g Volo.Abp.Cli --version 7.2.0-rc.2
abp suite install --version 7.2.0-rc.2
abp suite

Result: 
ABP CLI 7.2.0-rc.2
Starting Suite v7.2.0-rc.2 ...
Opening http://localhost:3000
Press Ctrl+C to shut down.
[13:49:13 ERR] Connection id "0HMQ5NN1KM71T", Request id "0HMQ5NN1KM71T:00000001": An unhandled exception was thrown by the application.
Volo.Abp.AbpException: Could not find the bundle file '/libs/abp/core/abp.css' for the bundle 'Lepton.Global'!

So now I'm experiencing a similar issue when launching abp suite, before I even create a project. I will try 7.0.3 next.

**Comment by justinb9909** [comment] 2023-04-25 19:42
abp suite remove
abp cli remove
dotnet tool install -g Volo.Abp.Cli --version 7.0.3
abp suite install --version 7.0.3
abp suite

Abp suite works now, but I have the same subject issue when attempting to run the project. I'm not sure how to proceed. Am I failing to remove something before generating the new project solution?

**Comment by EngincanV** [comment] 2023-04-26 10:01
> abp suite remove abp cli remove dotnet tool install -g Volo.Abp.Cli --version 7.0.3 abp suite install --version 7.0.3 abp suite
> 
> Abp suite works now, but I have the same subject issue when attempting to run the project. I'm not sure how to proceed. Am I failing to remove something before generating the new project solution?

Are you creating a new project and if so in which version?

**Comment by justinb9909** [comment] 2023-04-26 12:49
Yes, all attempts are completely new projects, Blazor Server, Lepton-X. I've tried 7.0.3, 7.1.1, and 7.2.0-rc.2. Essentially doing the OP's reproduction steps.

**Comment by brauerj-gc** [comment] 2023-04-26 15:07
Glad I'm not the only one having problems.  I've given up for now and just use my work around via abp.resourcemapping.js

**Comment by justinb9909** [comment] 2023-04-26 20:11
I can confirm 7.2.0-rc.2 does work. I never actually generated a project under 7.2.0-rc.2 because I had been using suite to do so and suite is broken in 7.2.0-rc.2. When I generated via CLI, everything worked as expected. I will create a new issue for the suite problem if it isn't identified already.

**Comment by EngincanV** [comment] 2023-04-27 05:10
> I can confirm 7.2.0-rc.2 does work. I never actually generated a project under 7.2.0-rc.2 because I had been using suite to do so and suite is broken in 7.2.0-rc.2. When I generated via CLI, everything worked as expected. I will create a new issue for the suite problem if it isn't identified already.

Thanks @justinb9909 🙏

**Closed as completed by EngincanV** 2023-04-27 05:10 UTC
