### ISSUE TITLE
 Oracle inserts or update data exception  will not be processed by global exception function?

### ISSUE THREAD

**Issue by crashsol** [abpframework/abp#9189] opened 2021-05-30 06:15 UTC
when  use oracle provider , insert  or update records , if it throw  DbUpdateException，eq: 

`Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-12899: 列 "SYSTEM"."COMMENT_CON_TASK_TYPE"."ISUPLOAD" 的值太大 (实际值: 6, 最大值: 1)
`

this  excepiton will not processed by global exception handler, because  the response has already started!

`14:13:39 WRN] The response has already started, the error page middleware will not be executed.
[14:13:39 ERR] Connection id "0HM93687KA9FA", Request id "0HM93687KA9FA:00000002": An unhandled exception was thrown by the application.`

but if i remove ` app.UseUnitOfWork();`  in OnApplicationInitialization ,the exception will be `handled,`
This makes me very confused. What is the problem?

**Comment by maliming** [comment] 2021-05-30 06:19
Duplicate of #8740

**Closed as completed by maliming** 2021-05-30 06:19 UTC
