### ISSUE TITLE
Text templates with snake camel properties not work

### ISSUE THREAD

**Issue by gdlcf88** [abpframework/abp#6738] opened 2020-12-21 14:13 UTC
I tested it in ABP 3.2.1 and 4.0.2, got the same result:
![image](https://user-images.githubusercontent.com/30018771/102785134-6f0c3500-43d8-11eb-865c-5775343ab89b.png)

Following [the doc](https://github.com/abpframework/abp/blob/4.0.2/docs/en/Text-Templating.md#pascalcase-vs-camelcase):
> PascalCase property names (like UserName) is used as camelCase (like userName) in the templates.

My inputted model is:
```csharp
new {UserName = "gdlcf88"}
```

This template not works:
```
Welcome, {{model.userName}}
```
and this one works:
```
Welcome, {{model.user_name}}
```

I created apps for the problem:
https://github.com/gdlcf88/TextTemplatingTest

Please run `TextTemplatingTests` to reproduce it:
[ABP v3.2.1](https://github.com/gdlcf88/TextTemplatingTest/blob/master/3.2.1/aspnet-core/test/TextTemplatingTest.Application.Tests/TextTemplating/TextTemplatingTests.cs)
[ABP v4.0.2](https://github.com/gdlcf88/TextTemplatingTest/blob/master/4.0.2/aspnet-core/test/TextTemplatingTest.Application.Tests/TextTemplating/TextTemplatingTests.cs)

**Comment by yekalkan** [comment] 2020-12-21 14:25
duplicate of https://github.com/abpframework/abp/issues/6188

also fixed in documents https://github.com/abpframework/abp/commit/9ba0c01b0db390aecf3124aa3bf7cd4e7f654d31 (v4.1)
https://docs.abp.io/en/abp/4.1/Text-Templating

**Closed as completed by yekalkan** 2020-12-21 14:25 UTC
Labels: duplicate, invalid
