### ISSUE TITLE
TablePrefix Not Being Used

### ISSUE THREAD

**Issue by wayneboyles** [abpframework/abp#915] opened 2019-03-25 17:04 UTC
I have a test project in which my DbContext's `OnModelCreating` method configures the table prefix for each module:

`modelBuilder.ConfigureSettingManagement("MyPrefix");`

When I create a Migration the table is created as `MyPrefixSettings` as expected.  However, when running the project I get an error that `AbpSettings `is an invalid object - which it is since I've changed the prefix.

Should I be defining the prefix elsewhere in the code?  Is there a global setting somewhere to override the `TablePrefix `for all Abp Entities like in the previous version?

Thanks.

**Comment by maliming** [comment] 2019-03-26 02:52
https://github.com/abpframework/abp/blob/287f71d805cef27a221e6eead02fec59b6e62187/modules/setting-management/src/Volo.Abp.SettingManagement.EntityFrameworkCore/Volo/Abp/SettingManagement/EntityFrameworkCore/SettingManagementDbContext.cs#L22-L27

It seems to be overriding the configuration of the custom table prefix.

**Comment by hikalkan** [comment] 2019-03-26 08:49
Try to set `SettingManagementDbContext.TablePrefix` property in your ConfigureServices method.

**Comment by wayneboyles** [comment] 2019-03-26 14:30
> Try to set SettingManagementDbContext.TablePrefix property in your ConfigureServices method. It is not constant, it is static.

This works.  I updated my code to use `SettingManagementDbContext.TablePrefix = "MyPrefix"` and it no longer fails to find the table so that's honoring the value correctly.  I did the same for other modules such as `PermissionManagementDbContext.TablePrefix` and seems to be working correctly.

**Comment by hikalkan** [comment] 2019-03-26 14:45
I'm closing because this is by design :)

**Closed by hikalkan** 2019-03-26 14:45 UTC
