### ISSUE TITLE
Micro service demo, when I logout, backendadminapp.host site is still accessible, to manually clear cookies will exit.

### ISSUE THREAD

**Issue by 344089386** [abpframework/abp#2167] opened 2019-11-14 01:36 UTC
Micro service demo, when I logout, backendadminapp.host site is still accessible, to manually clear cookies will exit.

**Comment by hikalkan** [comment] 2019-11-16 20:16
Duplicate of https://github.com/abpframework/abp/issues/835

**Closed by hikalkan** 2019-11-16 20:16 UTC
