### ISSUE TITLE
Add QueueAsync Method with MailMessage Parameter to IEmailSender Interface

### ISSUE THREAD

**Issue by salihozkara** [abpframework/abp#17552] opened 2023-09-04 11:52 UTC
In scenarios where we need to enqueue emails, the existing method signature might be insufficient. To allow for more customization of emails based on specific use cases, we should add a method with a MailMessage parameter to the IEmailSender interface, similar to the [SendAsync](https://github.com/abpframework/abp/blob/dev/framework/src/Volo.Abp.Emailing/Volo/Abp/Emailing/IEmailSender.cs#L46-L49) method.

```cs
Task QueueAsync(
        MailMessage mail,
        bool normalize = true
    );
```

**Comment by EngincanV** [comment] 2023-09-04 12:45
duplicate of https://github.com/abpframework/abp/issues/7705 ?

**Closed as completed** 2023-09-04 12:47 UTC
Labels: duplicate
