### ISSUE TITLE
ABP DB migration doesn't work with Oracle

### ISSUE THREAD

**Issue by imabdulsal** [abpframework/abp#7787] opened 2021-02-20 18:47 UTC
## Issue Summary
DB migration would not work with Oracle database, because ABP has many database's object names that break the following [Oracle Object Naming Rule](https://docs.oracle.com/cd/B19306_01/server.102/b14200/sql_elements008.htm):
> Names must be from 1 to 30 bytes long

That obviously means **all the ABP database's objects (i.e., tables, columns, indexes, and constraints) MUST NOT exceed that number of bytes, which is equivalent to 30 characters**. Exceeding that number of characters would produce this common error message: `ORA-00972: identifier is too long`

### Examples

- **Table name**: IdentityServerClientPostLogoutRedirectUris **(42 characters)**
- **Column name**: AllowedAccessTokenSigningAlgorithms **(35 characters)**
- **Index name**: IX_AbpLinkUsers_SourceUserId_SourceTenantId_TargetUserId_TargetTenantId **(71 characters)**
- **Constraint name**: FK_IdentityServerApiResourceClaims_IdentityServerApiResources_ApiResourceId **(75 characters)**

### Note
**Actually, this issue isn't specifically related to Migration process, but it's more about aligning ABP database's object names with [Oracle Object Naming Rules](https://docs.oracle.com/cd/B19306_01/server.102/b14200/sql_elements008.htm).**

## Steps to reproduce the issue
- Create a new DB migration
- Update the Oracle DB

**Comment by maliming** [comment] 2021-02-21 03:16
Duplicate of #1920

**Closed as completed by maliming** 2021-02-21 03:16 UTC

**Comment by Monodytheone** [comment] 2024-04-25 13:25
Could you please let me know if you have a solution to this issue? I would greatly appreciate your help. @abdullahsalem
