### ISSUE TITLE
Docs: Problems on images

### ISSUE THREAD

**Issue by onurpicakci** [abpframework/abp#15561] opened 2023-01-31 12:58 UTC
Some images are not showing up. This is because the paths of the images are `tutorials`, but they are in the `Tutorials` folder in the repo on Github.

![Ekran Resmi 2023-01-31 15 51 29](https://user-images.githubusercontent.com/98148844/215765739-a2c9ad4e-0af1-4d1c-aa6b-d28c118cc277.png)

![Ekran Resmi 2023-01-31 15 52 33](https://user-images.githubusercontent.com/98148844/215765746-435cd52f-0247-478c-baef-8103fb4bed4b.png)

**Note:** Deleting the cache of the relevant document solves temporarily the problem.

**Comment by EngincanV** [comment] 2023-02-27 09:00
Could not reproduce the problem, so closing the issue.

**Closed as completed by EngincanV** 2023-02-27 09:00 UTC
Labels: abp-module-docs, test, effort-xs
