### ISSUE TITLE
NX Proxy Generator failed to generate generic / template dto

### ISSUE THREAD

**Issue by puschie286** [abpframework/abp#19373] opened 2024-03-21 09:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Dtos with generic parameter failed to generate correct proxy dto. 

we have a simple dto (almost identical to Volo.Abp.Applcation.Dtos.EntityDto) that we used as base for almost all dtos.
```c#
[Serializable]
public abstract class ConcurrencyEntityDto : EntityDto, IHasConcurrencyStamp
{
	public string ConcurrencyStamp { get; set; } = null!;
}

[Serializable]
public abstract class ConcurrencyEntityDto<TKey> : EntityDto<TKey>, IHasConcurrencyStamp
{
	public string ConcurrencyStamp { get; set; } = null!;
}
```
but the fails to generate correct proxy classes. this is generated:
```ts
import type { EntityDto } from '@abp/ng.core';
import type { TKey } from '../../../models';

export interface ConcurrencyEntityDto extends EntityDto {
  concurrencyStamp?: string;
}

export interface ConcurrencyEntityDto<TKey> extends EntityDto<TKey> {
  concurrencyStamp?: string;
}
```
there are two problems:
1. generated import of generic type 
2. two version are generated (not valid for typescript)

### Known Workarounds

Manual removing generic type import, remove non generic version and define type (like string) as generic default

### Version

8.0.5

### User Interface

Angular

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by steffbeckers** [comment] 2024-05-23 12:04
Related to https://github.com/abpframework/abp/issues/19656

**Comment by realLiangshiwei** [comment] 2024-05-24 00:46
Duplicate of https://github.com/abpframework/abp/issues/18956

**Closed as completed by realLiangshiwei** 2024-05-24 00:46 UTC
