### ISSUE TITLE
How to implement like AbpSession.Use(userId,tenantId) in ABP

### ISSUE THREAD

**Issue by LGinC** [abpframework/abp#2200] opened 2019-11-18 07:18 UTC
I can find this function in vNext.
AbpSession.Use(useId, tenantId)
UnitOfWorkManager.Current.SetTenantId(tenantId)

ICurrentUser, ICurrentTenant   are both readonly, no set func. So how change it temporily

**Comment by LGinC** [comment] 2019-11-18 07:28
just find ICurrentTenant.Change ...

**Comment by maliming** [comment] 2019-11-18 07:35
Duplicate of #887

**Closed by maliming** 2019-11-18 07:35 UTC

**Comment by hikalkan** [comment] 2020-06-09 12:35
see https://github.com/abpframework/abp/blob/dev/docs/en/CurrentUser.md#changing-the-current-principle
