### ISSUE TITLE
when I run abp cli  :abp add-module Volo.CmsKit --with-source-code,find the error

### ISSUE THREAD

**Issue by indexlang** [abpframework/abp#9472] opened 2021-07-01 03:33 UTC
abp add-module Volo.CmsKit --with-source-code
[11:28:17 INF] ABP CLI (https://abp.io)
[11:28:17 INF] Version 4.4.0-rc.1 (Prerelease)
[11:28:21 INF] Installing module 'Volo.CmsKit' to the solution 'Txlcinfo.AgriMachineNav'
[11:28:21 INF] Checking installed npm global packages...
[11:28:27 INF] Downloading source code of Volo.CmsKit
[11:28:27 INF] Version: 4.4.0-rc.1
[11:28:27 INF] Output folder: H:\projects\AgriMachineNav\modules\Volo.CmsKit
[11:28:28 INF] Using cached module: Volo.CmsKit, version: 4.4.0-rc.1
[11:28:28 ERR] Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Volo.Abp.Cli.ProjectBuilding.Building.Steps.CreateAppSettingsSecretsStep.Execute(ProjectBuildContext context) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\Building\Steps\CreateAppSettingsSecretsStep.cs:line 15
   at Volo.Abp.Cli.ProjectBuilding.Building.ProjectBuildPipeline.Execute() in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\Building\ProjectBuildPipeline.cs:line 19
   at Volo.Abp.Cli.ProjectBuilding.ModuleProjectBuilder.BuildAsync(ProjectBuildArgs args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectBuilding\ModuleProjectBuilder.cs:line 76
   at Volo.Abp.Cli.Commands.Services.SourceCodeDownloadService.DownloadModuleAsync(String moduleName, String outputFolder, String version, String gitHubAbpLocalRepositoryPath, String gitHubVoloLocalRepositoryPath, AbpCommandLineOptions options) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\Services\SourceCodeDownloadService.cs:line 40
   at Volo.Abp.Cli.ProjectModification.SolutionModuleAdder.DownloadSourceCodesToSolutionFolder(ModuleWithMastersInfo module, String modulesFolderInSolution, String version, Boolean newTemplate, Boolean newProTemplate) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\SolutionModuleAdder.cs:line 446
   at Volo.Abp.Cli.ProjectModification.SolutionModuleAdder.AddAsync(String solutionFile, String moduleName, String version, Boolean skipDbMigrations, Boolean withSourceCode, Boolean addSourceCodeToSolutionFile, Boolean newTemplate, Boolean newProTemplate) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\ProjectModification\SolutionModuleAdder.cs:line 107
   at Volo.Abp.Cli.Commands.AddModuleCommand.ExecuteAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\Commands\AddModuleCommand.cs:line 54
   at Volo.Abp.Cli.CliService.RunInternalAsync(CommandLineArgs commandLineArgs) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 158
   at Volo.Abp.Cli.CliService.RunAsync(String[] args) in D:\ci\Jenkins\workspace\abp-framework-release\abp\framework\src\Volo.Abp.Cli.Core\Volo\Abp\Cli\CliService.cs:line 66

**Comment by maliming** [comment] 2021-07-01 03:37
Duplicate of #9458

**Closed as completed by maliming** 2021-07-01 03:37 UTC
