### ISSUE TITLE
Documenting how we got ABP to work with Microsoft.AspNetCore.OData

### ISSUE THREAD

**Issue by tinonetic** [abpframework/abp#4132] opened 2020-05-28 19:57 UTC
Hi there,

Not sure how to go about this, but we got ABP working with Microsoft.AspNetCore.OData (https://github.com/OData/odata.net).

Would you be interested in us contributing a page documenting that? 
Justification being that OData is still heavily adopted and the Microsoft.AspNetCore.OData project is an active & growing project (by updates, contribution and downloads 

- https://www.nuget.org/packages/Microsoft.AspNetCore.OData)
- https://docs.microsoft.com/en-us/odata/

From my side, we chose OData from the 3 most widely used methods for querying RESTful APIs (OData, GraphQL, ORDS). Contributing OData implementation under ABP would help us get scrutiny and review from ABP team. Since we are invested in both, this would help give back, get mindshare and also get feedback from contributor expertise.

If not, I understand.

Happy to still contribute to other ABP bugs and feature requests

Thanks for the awesome product!!!

**Comment by liangshiw** [comment] 2020-05-29 01:56
Duplicate of https://github.com/abpframework/abp/issues/990

Integrating OData into abp is easyly, I created an example: https://github.com/liangshiw/AbpOdataDemo

**Closed by liangshiw** 2020-05-29 01:56 UTC

**Comment by antonGritsenko** [comment] 2023-03-17 00:19
@realLiangshiwei not sure why you say "is easyly", because actually its a bit pain. The default FullAggregation model can't be used in OData, it generates wrong LINQ query:
```
System.InvalidOperationException: The LINQ expression 'DbSet<IdentityUser>()
    .Where(i => __ef_filter__p_0 || !(EF.Property<bool>(i, "IsDeleted")) && __ef_filter__p_1 || (Guid?)EF.Property<Guid>(i, "TenantId") == __ef_filter__CurrentTenantId_2)
    .Where(i => (string)i.ExtraProperties.ContainsKey("UserName") ? i.ExtraProperties["UserName"] : null == __TypedProperty_0)' could not be translated. Additional information: Translation of method 'System.Collections.Generic.Dictionary<string, object>.ContainsKey' failed. If this method can be mapped to your custom function, see https://go.microsoft.com/fwlink/?linkid=2132413 for more information. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

```

So the only way is to create models manually, which is really the pain.
