### ISSUE TITLE
API Rate Limiting

### ISSUE THREAD

**Issue by dicksonkimeu** [abpframework/abp#12422] opened 2022-05-02 16:58 UTC
This would be great.

Especially is there is a per tenant setting.

**Comment by berkansasmaz** [comment] 2022-05-17 07:02
Thanks for your feature request. You can follow the developments on the subject [here](https://github.com/abpframework/abp/issues/389).

Duplicate of #389

**Closed as completed by berkansasmaz** 2022-05-17 07:02 UTC
Labels: duplicate, feature
