### ISSUE TITLE
Oracle Migration Error

### ISSUE THREAD

**Issue by skywalkers2012** [abpframework/abp#6205] opened 2020-11-15 15:56 UTC
OracleRelationalCommand.ExecuteReaderAsync() :  Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00972: 标识符过长
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
[21:57:43 ERR] Failed executing DbCommand (401ms) [Parameters=[:ef_filter__p_0='?' (DbType = Byte), :name_1='?' (Size = 200)], CommandType='Text', CommandTimeout='0']
SELECT CASE
    WHEN EXISTS (
        SELECT 1
        FROM "IdentityServerIdentityResources" "i"
        WHERE (((((((:ef_filter__p_0 = 1)) OR (("i"."IsDeleted" <> 1))))) AND (("i"."Name" = :name_1))))) THEN 1
    ELSE 0
END FROM DUAL

**Comment by maliming** [comment] 2020-11-16 00:55
Duplicate of #1920

**Closed as completed by maliming** 2020-11-16 00:55 UTC
