### ISSUE TITLE
Issue adding navigation property to IdentityUser

### ISSUE THREAD

**Issue by SoloHam** [abpframework/abp#3460] opened 2020-04-03 03:55 UTC
I needed a reference to the Employee Entity in the AppUser. I added only 
the `public virtual Guid? EmployeeId` and it works fine but when I also add `public virtual Employee Employee { get; set; }` it gives the following error:

### Error:
```
The navigation property 'Employee' cannot be added to the entity type 'IdentityUser' because there is no corresponding CLR property on the underlying type and navigations properties cannot be added to shadow state.
``` 

### Entity:
```
public class AppUser : FullAuditedAggregateRoot<Guid>, IUser
    {
        #region Base properties

        /* These properties are shared with the IdentityUser entity of the Identity module.
         * Do not change these properties through this class. Instead, use Identity module
         * services (like IdentityUserManager) to change them.
         * So, this properties are designed as read only!
         */

        public virtual Guid? TenantId { get; private set; }

        public virtual string UserName { get; private set; }

        public virtual string Name { get; private set; }

        public virtual string Surname { get; private set; }

        public virtual string Email { get; private set; }

        public virtual bool EmailConfirmed { get; private set; }

        public virtual string PhoneNumber { get; private set; }

        public virtual bool PhoneNumberConfirmed { get; private set; }

        #endregion

        /* Add your own properties here. Example:
         *
         * public virtual string MyProperty { get; set; }
         */
        [ForeignKey("EmployeeId")]
        public virtual Employee Employee { get; set; }
        public virtual Guid? EmployeeId { get; set; }

        private AppUser()
        {
            
        }
    }
```

### Configurations:
```
        public static void ConfigureCustomUserProperties<TUser>(this EntityTypeBuilder<TUser> b)
            where TUser: class, IUser
        {
            b.Property<Guid?>(nameof(AppUser.EmployeeId));
            b.HasOne<Employee>(nameof(AppUser.Employee)).WithOne().OnDelete(DeleteBehavior.Restrict);
        }
```

**Comment by maliming** [comment] 2020-04-03 05:08
Duplicate of #https://github.com/abpframework/abp/issues/2857

**Closed by maliming** 2020-04-03 05:08 UTC
