### ISSUE TITLE
Swagger Authorize With Keycloak Get Message "we are sorry"

### ISSUE THREAD

**Issue by malikmasis** [abpframework/abp#15183] opened 2022-12-21 08:54 UTC
related https://github.com/abpframework/eShopOnAbp/issues/145

**Comment by haithambasim** [comment] 2022-12-21 13:31
the problem is when you try to authorize from swagger, it redirects to
[http://localhost:8080/realms/master/connect/authorize](http://localhost:8080/realms/master/connect/authorize)
instead of redirecting to 
[http://localhost:8080/realms/master/protocol/openid-connect/auth](http://localhost:8080/realms/master/protocol/openid-connect/auth)

![image](https://user-images.githubusercontent.com/20759893/208923488-5a1b3c9f-fddf-44eb-ab6d-97a24f11c4f0.png)

**Comment by gterdem** [comment] 2022-12-21 14:39
This has been fixed with https://github.com/abpframework/abp/pull/14409
We'll update the version for swagger in eShopOnAbp.
Related issue can be found at : https://github.com/abpframework/abp/issues/14806

I am closing this issue to follow it under the main issue.

**Closed as completed** 2022-12-21 14:39 UTC
Labels: bug, eShopOnAbp

**Comment by alihdev** [comment] 2022-12-21 15:14
Yes, this right the problem in AuthorizationUrl and TokenUrl 
We changed it directly to :
http://localhost:8080/realms/master/protocol/openid-connect/auth

![image](https://user-images.githubusercontent.com/97635301/208937634-77516023-093b-4584-82ac-3519ad65d7ef.png)

So, There is another problem when we auth using swagger : 
"We are sorry... Invalid parameter: redirect_uri"

![image](https://user-images.githubusercontent.com/97635301/208938497-26298a48-44db-4c81-9ca1-b70d83ab5bfb.png)

The problem in Clients and Scopes - in DbMigrator

**Comment by alihdev** [comment] 2022-12-21 17:30
https://github.com/abpframework/abp/issues/15183#issuecomment-1361465705

Solved By Add **WebGateway_Swagger** Client with Scopes In **MERP.Keycloak.DbMigrator.KeycloakDataSeeder**

![image](https://user-images.githubusercontent.com/97635301/208967060-5d41c3a0-a4bc-4b94-a23e-d38a17aa733c.png)
