### ISSUE TITLE
Feature: Entity Level Localization support

### ISSUE THREAD

**Issue by a-patel** [abpframework/abp#4166] opened 2020-06-01 08:06 UTC
Feature: Entity Level Localization support

e.g. Entity: Product
User/Admin can add product details (fields: Name, Description) for different languages.

Existing: Localization is supported for display field labels only using resource files.

**Comment by liangshiw** [comment] 2020-06-01 11:32
Duplicate of https://github.com/abpframework/abp/issues/1754

**Closed by liangshiw** 2020-06-01 11:32 UTC
Labels: duplicate
