### ISSUE TITLE
System.Diagnostics.PerformanceCounter、Pages__ViewImports 、Views__ViewImports”

### ISSUE THREAD

**Issue by ThreeLambs** [abpframework/abp#5021] opened 2020-08-11 01:01 UTC
```shell
 $ dotnet run
C:\Program Files\dotnet\sdk\3.1.302\Microsoft.Common.CurrentVersion.targets(2081,5): warning MSB3277: 发现“System.Diagnostics.PerformanceCounter”的不同版本间存在无法解
决的冲突。当日志详细程度设置为“详细”时，这些引用冲突将会在生成日志中列出。 [D:\TcpChina\TcpChina\src\TcpChina.Web\TcpChina.Web.csproj]
Menus\TcpChinaMenuContributor.cs(40,17): warning CS0162: 检测到无法访问的代码 [D:\TcpChina\TcpChina\src\TcpChina.Web\TcpChina.Web.csproj]
obj\Debug\netcoreapp3.1\Razor\Pages\_ViewImports.cshtml.g.cs(4,100): warning CS0436: “D:\TcpChina\TcpChina\src\TcpChina.Web\obj\Debug\netcoreapp3.1\Razor\Pages\_ViewImp orts.cshtml.g.cs”中的类型“Pages__ViewImports”与“Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic.Views, Version=3.0.5.0, Culture=neutral, PublicKeyToken=null”中的导入类型“Pa
ges__ViewImports”冲突。请使用“D:\TcpChina\TcpChina\src\TcpChina.Web\obj\Debug\netcoreapp3.1\Razor\Pages\_ViewImports.cshtml.g.cs”中定义的类型。 [D:\TcpChina\TcpChina\
src\TcpChina.Web\TcpChina.Web.csproj]
obj\Debug\netcoreapp3.1\Razor\Views\_ViewImports.cshtml.g.cs(4,100): warning CS0436: “D:\TcpChina\TcpChina\src\TcpChina.Web\obj\Debug\netcoreapp3.1\Razor\Views\_ViewImp orts.cshtml.g.cs”中的类型“Views__ViewImports”与“Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic.Views, Version=3.0.5.0, Culture=neutral, PublicKeyToken=null”中的导入类型“Vi
ews__ViewImports”冲突。请使用“D:\TcpChina\TcpChina\src\TcpChina.Web\obj\Debug\netcoreapp3.1\Razor\Views\_ViewImports.cshtml.g.cs”中定义的类型。 [D:\TcpChina\TcpChina\
src\TcpChina.Web\TcpChina.Web.csproj]
```
这个怎么处理?

**Comment by maliming** [comment] 2020-08-11 01:02
* Your **ABP Framework version**.
* Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
* Exception message and **stack trace** if available (check the logs).
* Steps needed to **reproduce** the problem.

Please **write in English**.

**Comment by ThreeLambs** [comment] 2020-08-11 01:08
> * Your **ABP Framework version**.
> * Your **User Interface** type (Angular/MVC/React... etc.) if the issue is related to a specific UI
> * Exception message and **stack trace** if available (check the logs).
> * Steps needed to **reproduce** the problem.
> 
> Please **write in English**.

 
The latest version just downloaded。 MVC Tiered Application
problems:
System.Diagnostics.PerformanceCounter、Pages__ViewImports 、Views__ViewImports conflict

**Comment by NecatiMeral** [comment] 2020-09-02 08:03
Duplicate of #4778?

**Closed as completed** 2020-09-02 08:26 UTC
