### ISSUE TITLE
need RabbitMqEventBus advanced configuration

### ISSUE THREAD

**Issue by NikitaUsefi** [abpframework/abp#3367] opened 2020-03-26 08:16 UTC
Hi,
I have a scenario in which I need to send a huge amount of data in rabbitmq event bus and then use a handler to process it. Since the data I'm using in the bus is quite bulky, the prefetchCount configuration should not set to max level as it would use up all the space in memory.(this config can be set in channel.BasicQos)
is there a way for me to set such value, in this version?
thanks in advance

**Comment by hikalkan** [comment] 2020-04-23 23:19
duplicate of https://github.com/abpframework/abp/issues/3512

**Closed by hikalkan** 2020-04-23 23:19 UTC
