### ISSUE TITLE
Volo.Abp.Http.Client, RemoteServiceErrorInfo, Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by cethink** [abpframework/abp#19587] opened 2024-04-21 04:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

```shell
[11:53:19 ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "对不起，在处理您的请求期间产生了一个服务器内部错误！！",
  "details": null,
  "data": {},
  "validationErrors": null
}

[11:53:19 ERR] Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Volo.Abp.Http.Client.DynamicProxying.ApiDescriptionFinder.FindActionAsync(HttpClient client, String baseUrl, Type serviceType, MethodInfo method)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.GetActionApiDescriptionModel(IAbpMethodInvocation invocation)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1.InterceptAsync(IAbpMethodInvocation invocation)   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at ES_ProductService.Controllers.ProductController.GetListAsync(PagedAndSortedResultRequestDto input) in D:\EcommerceSeckills\middles\ES_WebSite_Aggregate\Controllers\ProductController.cs:line 36
   at lambda_method1003(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

### Version

8.1.1

### User Interface

Common (Default)

### Database Provider

EF Core (Default)

### Tiered or separate authentication server

None (Default)

### Operation System

Windows (Default)

**Comment by realLiangshiwei** [comment] 2024-04-21 04:11
Please provider a small project to reproduce this.

**Comment by cethink** [comment] 2024-04-21 04:27
> Please provider a small project to reproduce this.

@realLiangshiwei [EcommerceSeckills.zip](https://github.com/abpframework/abp/files/15050650/EcommerceSeckills.zip)

![image](https://github.com/abpframework/abp/assets/756512/bcdded0a-a1ef-44d1-8e0b-f69395c27902)

![image](https://github.com/abpframework/abp/assets/756512/12c79fd5-6e2a-423e-a4a0-3df233c28030)

```json
"RemoteServices": {
  "productservice": {
    "BaseUrl": "https://localhost:44385"
  }
}
```

```csharp
context.Services.AddHttpClientProxy<IProductService>("productservice");
```

**Comment by realLiangshiwei** [comment] 2024-04-21 05:25
First:

`context.Services.AddHttpClientProxy<IProductService>("productservice");`

The application uses `productservice` as the service name, but you have not configured it for the controller. The default service name is `app` and `default`.

<img width="849" alt="image" src="https://github.com/abpframework/abp/assets/16813853/975c3d61-cf87-41e1-918b-a448247c388c">

<img width="735" alt="image" src="https://github.com/abpframework/abp/assets/16813853/af1b66c5-e228-4535-81be-4cae3fcaddc2">

Second:

You changed the the default json `PropertyNamingPolicy`.
You need to change the `JsonSerializerOptions` of the `ApiDescriptionFinder` as well.

```csharp
public override void OnApplicationInitialization(ApplicationInitializationContext context)
{
     .....
     ApiDescriptionFinder.DeserializeOptions.PropertyNamingPolicy = null;
}
```

**Comment by cethink** [comment] 2024-04-21 05:57
@realLiangshiwei I'm sorry, I tried what you said, but it doesn't work. Can you upload the modified success code zip pack? Thanks

**Comment by cethink** [comment] 2024-04-21 06:26
Thanks, I made a mistake, it works now! 👍

**Comment by cethink** [comment] 2024-05-23 09:57
@realLiangshiwei Can you help to solve this questions? Thanks.
https://flowus.cn/cethink/share/397dd530-2e8e-4699-8df6-71429e6b38c8
[EcommerceSeckills.zip](https://github.com/abpframework/abp/files/15415089/EcommerceSeckills.zip)

**Comment by realLiangshiwei** [comment] 2024-05-23 16:07
I think this is your usage problem,  you should check it first.
I'm closing this,because this original question has been solved

**Closed as completed by realLiangshiwei** 2024-05-23 16:07 UTC
