### ISSUE TITLE
Username not showing in header in Blazor WebAssembly

### ISSUE THREAD

**Issue by D4ngeresque** [abpframework/abp#8741] opened 2021-04-21 21:05 UTC
* **ABP Framework version**: 4.3.0-rc.2
* **User Interface**: Blazor WebAssembly
* **Database Provider**: EF Core/SQL Server
* **Separate Identity Server**: Yes

### Steps needed to reproduce the problem:
1. Download new startup template from [https://abp.io/get-started](https://abp.io/get-started) with below options and follow startup steps as outlined in documentation.
2. Login as admin.
3. After logging in, the username and the associated dropdown in the header will be blank and the login link on the home screen will still be showing. Administrative options will still be available in the header.
4. After refreshing the page the issue is corrected.

![image](https://user-images.githubusercontent.com/40548678/115620306-01f3a800-a2c3-11eb-827a-746e1c41b43a.png)
![image](https://user-images.githubusercontent.com/40548678/115620754-952cdd80-a2c3-11eb-9340-6b2dbcd842b2.png)
![image](https://user-images.githubusercontent.com/40548678/115620811-a5dd5380-a2c3-11eb-9432-3e029b8c3346.png)

**Comment by maliming** [comment] 2021-04-22 01:01
Duplicate of #8683

**Closed as completed by maliming** 2021-04-22 01:01 UTC
