### ISSUE TITLE
chrome 80+ not login in

### ISSUE THREAD

**Issue by qqzhw** [abpframework/abp#3318] opened 2020-03-23 14:37 UTC
chrome 80+ not login in  , is not save Cookies 
  V2.2 v2.3

**Comment by lanpin** [comment] 2020-03-23 21:02
I uninstalled and reinstalled chrome and the issue was resolved.
but,
Only abp related applications have problems, other websites are good.

**Comment by maliming** [comment] 2020-03-24 00:04
Duplicate of #3227

**Closed by maliming** 2020-03-24 00:04 UTC

**Comment by lanpin** [comment] 2020-03-25 01:03
@maliming
The url you quoted is not the final solution to the problem, because before I reinstalled Chrome, abp.io also failed to log in, and it used https. This issue may recur at some time in the future, and if it happens again, I will record and issue the issue again.

**Comment by maliming** [comment] 2020-03-25 01:16
@lanpin What version of chrome can't log in in abp.io?

**Comment by qqzhw** [comment] 2020-03-25 01:19
80

**Comment by maliming** [comment] 2020-03-25 01:47
Google Chrome Version 80.0.3987.149 (Official Build) (64-bit) can't reproduce.
