### ISSUE TITLE
Blazor UI: The old page header still exists after switching pages

### ISSUE THREAD

**Issue by realLiangshiwei** [abpframework/abp#21544] opened 2024-12-05 06:24 UTC
<img width="2028" alt="image" src="https://github.com/user-attachments/assets/2d3b0c06-c4d0-4dea-8d8b-2de33a98e1df">

**Comment by maliming** [comment] 2024-12-05 06:27
Duplicate of #https://github.com/abpframework/abp/issues/21185

**Closed as completed by maliming** 2024-12-05 06:27 UTC
