### ISSUE TITLE
Could not find the bundle file '/libs/luxon/luxon.min.js' from IWebContentFileProvider

### ISSUE THREAD

**Issue by maliming** [abpframework/abp#5456] opened 2020-09-17 13:11 UTC
`abp new Angular.NonSeperatedEfCore -t app -u angular --mobile none  --database-provider ef --preview`

**Comment by maliming** [comment] 2020-09-17 13:16
https://github.com/abpframework/abp/commit/ae9f593b5e990a27f40b67eadcfb15f24d54d5cb#diff-8d7bacdeb0620aad6ca081e59ae42a11R1-R6

**Comment by hikalkan** [comment] 2020-09-17 13:18
Duplicate of https://github.com/abpframework/abp/issues/5457

**Closed as completed by hikalkan** 2020-09-17 13:18 UTC
Labels: duplicate
