### ISSUE TITLE
How to filter data with ExtraProperties fields ?

### ISSUE THREAD

**Issue by khanhtranchi** [abpframework/abp#9920] opened 2021-08-30 05:50 UTC
I have create a new field and name it is phone
ModelData data= new ModelData();
data.SetProperty("phone", "account phone");          

But when I query, it always return null:
  return await (await GetMongoQueryableAsync(cancellationToken))
                .FirstOrDefaultAsync(x => x.ExtraProperties["phone"] == "account phone");

I search all of the document, but don't find the info show us how to query data with ExtraProperties. Could you point us the related document ?

Thanks.

**Comment by maliming** [comment] 2021-08-30 06:03
Duplicate of #8009

**Closed as completed by maliming** 2021-08-30 06:03 UTC
