### ISSUE TITLE
Missing Page : Forgot password

### ISSUE THREAD

**Issue by vd3d** [abpframework/abp#2714] opened 2020-01-25 19:24 UTC
Hi,

In the Identity (Account) module, you allow to register with an email, but there is no "Forgot password" page !

This feature is really part of the basic features set ... to be coherent !

**Comment by hikalkan** [comment] 2020-01-26 20:38
Duplicate of https://github.com/abpframework/abp/issues/2608 (see [my comment](https://github.com/abpframework/abp/issues/2608#issuecomment-572883146))

**Closed by hikalkan** 2020-01-26 20:38 UTC
