### ISSUE TITLE
Following the tutorial causes a compile error: Error CS0115 'Pages_Books_Index.ExecuteAsync()': no suitable method found to override. 

### ISSUE THREAD

**Issue by julianlaudat** [abpframework/abp#4393] opened 2020-06-18 10:11 UTC
ABP Framework version 2.9.
MVC UI

I am following the BookStore tutorial. A problem arises with the example code seem to cause a problem.

@page
@using Acme.BookStore.Web.Pages.Books
@inherits Acme.BookStore.Web.Pages.**BookStorePageModel**
@model IndexModel

"Error CS0115 'Pages_Books_Index.ExecuteAsync()': no suitable method found to override". 

I am following the tutorial and only found abp.io yesterday but I get the above error. It is probably something simple to fix or am I missing something in the documentation.

**Comment by maliming** [comment] 2020-06-18 10:14
Duplicate of #4333

**Closed by maliming** 2020-06-18 10:14 UTC
