### ISSUE TITLE
The property 'AppUser.ExtraProperties' could not be mapped

### ISSUE THREAD

**Issue by souselesslove** [abpframework/abp#3882] opened 2020-05-09 01:45 UTC
I have a class named AAA:
```
public class AAA : FullAuditedAggregateRoot<Guid>
    {
        public virtual Guid? BBBId { get; private set; }
        public virtual Guid? BBBId1 { get; private set; }
        public virtual Guid? BBBId2 { get; private set; }
        [NotNull]
        public virtual string Title { get; private set; }
        protected AAA()
        {
        }
    }
```
then 
```
builder.Entity<AAA>(a =>
            {
                a.ToTable(GuideConsts.DbTablePrefix + nameof(AAA), GuideConsts.DbSchema);
                a.ConfigureByConvention();
                a.HasKey(x => x.Id);
            });
            builder.Entity<AAA>().HasOne<AppUser>().WithMany().IsRequired(false).HasForeignKey(x => x.CreatorId);
```
when i use "add-migration test"
> The property 'AppUser.ExtraProperties' could not be mapped, because it is of type 'Dictionary<string, object>' which is not a supported primitive type or a valid entity type. Either explicitly map this property, or ignore it using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

But I create another class named BBB, and also inherit from "FullAuditedAggregateRoot<Guid>"
```
public class BBB : FullAuditedAggregateRoot<Guid>
    {
        public virtual int Capacity { get; private set; }

        protected BBB()
        {
        }

    }
```
then config
```
builder.Entity<AAA>(a =>
            {
                a.ToTable(GuideConsts.DbTablePrefix + nameof(AAA), GuideConsts.DbSchema);
                a.ConfigureByConvention();
                a.HasKey(x => x.Id);
            });
            builder.Entity<AAA>().HasOne<BBB>().WithMany().HasForeignKey(x => x.BBBId);
            builder.Entity<AAA>().HasOne<BBB>().WithMany().HasForeignKey(x => x.BBBId1);
            builder.Entity<AAA>().HasOne<BBB>().WithMany().HasForeignKey(x => x.BBBId2);
```
it works...

@hikalkan , can you help me?

**Comment by liangshiw** [comment] 2020-05-09 10:42
Duplicate of  https://github.com/abpframework/abp/issues/1414

**Closed by liangshiw** 2020-05-09 10:42 UTC

**Comment by souselesslove** [comment] 2020-05-10 03:11
> Duplicate of #1414

It's not same question.

**Comment by liangshiw** [comment] 2020-05-10 03:44
Try https://github.com/abpframework/abp/issues/1414#issuecomment-507395552 or https://github.com/abpframework/abp/issues/1414#issuecomment-508818941

**Comment by souselesslove** [comment] 2020-05-26 19:53
> Try [#1414 (comment)](https://github.com/abpframework/abp/issues/1414#issuecomment-507395552) or [#1414 (comment)](https://github.com/abpframework/abp/issues/1414#issuecomment-508818941)

AppUser  ==>  Volo.Abp.Identity.IdentityUser
builder.Entity<Volo.Abp.Identity.IdentityUser>().HasOne<AppUser>().WithMany().IsRequired(false).HasForeignKey(x => x.CreatorId);

it works...
